### ISSUE TITLE
React Native warnings

### ISSUE THREAD

**Issue by montogeek** [gcanti/tcomb-form-native#101]
Hi!
I am using:
```
"react-native": "^0.17.0",
"tcomb-form-native": "^0.3.3"
```

When creating a new form with a field Date type I am getting these warnings:
![screen shot 2016-01-13 at 20 56 18](https://cloud.githubusercontent.com/assets/1002461/12313750/37327cea-ba38-11e5-859b-cc670703881d.png)
![screen shot 2016-01-13 at 20 56 10](https://cloud.githubusercontent.com/assets/1002461/12313751/374c8126-ba38-11e5-81b8-857235674aaa.png)

**Comment by alvaromb** [comment]
Hi @montogeek!

This is a know react native issue. I'll post here the issue number when I get to the office. Anyway, those warnings do no affect the date picker behavior.

**Comment by alvaromb** [comment]
Take a look here https://github.com/facebook/react-native/issues/4547
