### ISSUE TITLE
Support for select component in Android

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#103]
Now it's only ``PickerIOS``.

**Comment by alvaromb** [comment]
@gcanti we can wait for this and https://github.com/gcanti/tcomb-form-native/issues/67 for the complete Android support. It's not going to be done this week, so maybe we can release Switch support before.

**Comment by gcanti** [comment]
@alvaromb As you wish. I prepared a PR for 0.4 https://github.com/gcanti/tcomb-form-native/pull/104

**Comment by alvaromb** [comment]
https://developer.android.com/guide/topics/ui/controls/spinner.html is not yet supported in ``react-native`` and it's more or less the equivalent component to iOS' ``UIPickerView``. We can roll a custom solution using Android's ``Dialog`` with a pure js picker inside or wait until ``Spinner`` is supported (it's in the RN roadmap).

**Comment by alvaromb** [comment]
``Spinner`` landed in RN 0.18.0.

Will wait for it to release 0.4.0.

**Comment by kanerogers** [comment]
I'm running 0.18.0 and I don't think `Spinner` has been merged in just yet. Fingers crossed for `0.19.0`?

**Comment by alvaromb** [comment]
True @kanerogers, it seems that ``Spinner`` will land into 0.19. @gcanti meanwhile we should't release 0.4. The only component we're not going to support natively for Android is the ``DatePicker``, it should be distributed through a separate factory, as stated here https://github.com/gcanti/tcomb-form-native/issues/67#issuecomment-172865248.

Just a quick update for @all, I'm actively working on 0.4 release and Android support. We will have all the changes ready for RN 0.19 and it will be the minimum version required in order to work with Android.

**Comment by kanerogers** [comment]
I'm really excited to be able to give my Android users some love. Great
work guys!

**Comment by gcanti** [comment]
@alvaromb Great, thanks for your work. In the next few days I'll try to setup my machine with a valid android dev environment. Hopefully I'll be able to came back and give you active support.

**Comment by kanerogers** [comment]
Hey @alvaromb! We now have a cross-platform picker in 2.0 http://facebook.github.io/react-native/releases/0.20/docs/picker.html#content :grin:

**Comment by alvaromb** [comment]
Thanks for the info @kanerogers!!

``DatePicker`` will also be released https://github.com/gcanti/tcomb-form-native/issues/67#issuecomment-184103463

Expect 0.4 when RN 0.20 gets published.

**Comment by kanerogers** [comment]
I've done a test myself, works great! 😊

**Comment by alvaromb** [comment]
Finally RN 0.20 is out https://github.com/facebook/react-native/releases/tag/v0.20.0.

I'll finish the 0.4 release with full Android support this week. If I can't work on this until weekend, expect a release next week.

**Comment by kanerogers** [comment]
Yahoo! 😊

Picker is super easy - it's a drop in replacement for the iOS component.
DateTimePicker is a little bit annoying though. 😝

**Comment by alvaromb** [comment]
Ok, this PR adds the Android picker component https://github.com/gcanti/tcomb-form-native/pull/117

However, we need first some consensus about the Android date picker here https://github.com/gcanti/tcomb-form-native/issues/67.

Please feel free to comment how would you prefer the date picker to be implemented in Android.

**Comment by alvaromb** [comment]
Closed by https://github.com/gcanti/tcomb-form-native/releases/tag/v0.4.0.
