### ISSUE TITLE
Error: Naming collision detected

### ISSUE THREAD

**Issue by notlose** [gcanti/tcomb-form-native#105]
encountering this error
[12:00:36] <START> Building (deprecated) Asset Map
[12:00:37] <END>   Building (deprecated) Asset Map (1519ms)
Error building DependencyGraph:
 Error: Naming collision detected: /project/node_modules/tcomb-form-native/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/Array.prototype.es6.js collides with /project/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/Array.prototype.es6.js

**Comment by alvaromb** [comment]
Hello @notlose!

Which version of RN and ``tcomb-form-native`` are you using?

**Comment by alvaromb** [comment]
Please indicate RN version and ``tcomb-form-native`` version: https://github.com/gcanti/tcomb-form-native/blob/master/CONTRIBUTING.md#issues-request-guidelines

Will reopen once you provide the info :smiley_cat:
