### ISSUE TITLE
Question: Material design

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#11]
Google Material design is having a huge design impact. How would I implement Material Design for tcomb? Also given the fact that there are some projects that supply the design and animations for react and for bootstrap?

**Comment by gcanti** [comment]
You can customize the look and feel changing the default stylesheet and the default templates:

https://github.com/gcanti/tcomb-form-native#stylesheets

https://github.com/gcanti/tcomb-form-native#templates
