### ISSUE TITLE
Is there a property that makes label on the left side of textbox

### ISSUE THREAD

**Issue by liukepeng** [gcanti/tcomb-form-native#110]
How am I to do ?

**Comment by alvaromb** [comment]
You can drop a custom ``stylesheet`` https://github.com/gcanti/tcomb-form-native#stylesheets

And here https://github.com/gcanti/tcomb-form-native/blob/master/lib/stylesheets/bootstrap.js#L29-L41 you can set the label style.

**Comment by gcanti** [comment]
@liukepeng see here, there's a basic example with label on the left side

https://github.com/gcanti/tcomb-form-native/issues/106
