### ISSUE TITLE
need help getting form values

### ISSUE THREAD

**Issue by texas697** [gcanti/tcomb-form-native#114]
I am unsure how to get the input values when using the custom templates. I believe I am setting it up correctly?
`var Form = t.form.Form;

var loginObj = t.struct({
  userName: t.String,
  password: t.String,

});

function userNameTemplate(locals) {
  return (
    <View style={login.containerStyle}>
      <TextInput
      style={login.textInput}
      placeholder={'EMAIL'}
      placeholderTextColor={'rgba(255, 255, 255, 0.7'}/>
        <Icon name="person" size={27} color="rgba(255,255,255,0.8)" style={{position:'absolute',top:6, left: 6}}/>
    </View>
  );
}

function passwordTemplate(locals) {
  return (
    <View style={login.containerStyle}>
      <TextInput
      style={login.textInput}
      placeholder={'PASSWORD'}
      secureTextEntry={true}
      placeholderTextColor={'rgba(255, 255, 255, 0.7'}/>
        <Icon name="ios-unlocked-outline" size={27} color="rgba(255,255,255,0.8)" style={{position:'absolute',top:6, left: 6}}/>
    </View>
  );
}

var options = {
  fields: {
    userName: {
      error: 'Insert a valid email',
      template: userNameTemplate
    },
    password: {
      template: passwordTemplate
    }
  }
};
var Login = React.createClass({
getInitialState() {
     return { value: null };
   },
onChange(value) {
     this.setState({ value });
   },
 clearForm() {
     this.setState({ value: null });
   },
  onPress: function () {
    var value = this.refs.form.getValue();
   if (value) {
     console.log(value);
      this.clearForm();
    }
  },
   render: function() {
    return (
      <View style={login.color}>
          <Image source={require('../Common/Img/glow2.png')} style={login.container}>
              <Image source={require('../Common/Img/shadow.png')} style={login.shadow}>
                  <View style={login.bg}>
                      <Form
                        ref="form"
                        type={loginObj}
                        options={options}
                      />
                      <ButtonRounded
                          onPress={this.onPress}
                          text="Login" />
                  </View>
              </Image>
          </Image>
      </View>
    );
  }
});`

**Comment by kanerogers** [comment]
Hey, @texas697! Sorry to hear you're having issues.

Your form looks fine to me at first glance (although you might want to edit your comment to fix the backticks to make the code a little more readable :smile:).

As listed in the documentation, `form.getValue()` will return `null` if the form is invalid - are any validation errors being highlighted when the button is pressed? Have you tried simply doing a `console.log(this.refs.form.getValue())` to see what's being outputted?

**Comment by texas697** [comment]
thanks for the quick reply! sorry about the formatting. i put the console.log and only thing is null value. now before i tried the custom template the error message was showing up in the view. after moving the to the custom template if i click the submit button with empty inputs it triggers the function. so is it possible something went wrong?

**Comment by gcanti** [comment]
@texas697 please fix the formatting of your first comment. It seems that in your templates there's no handling of error messages, check out https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L26 for an example.
