### ISSUE TITLE
Support for unions (aka better dynamic forms)

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form-native#118]
`tcomb-form` v0.8.2 just added support for [unions](https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-union-combinator), which allow a more compact way to define dynamic forms. In particular they allow to define different structs based on a selected value.

**Anyone interested in this feature?** I could try my hand to port this feature from `tcomb-form` to `tcomb-form-native`.

## Example

**Problem:**

Say you have a predefined group of account types but you allow the user to select Other if the account type they want is not available. If they select other they should then be given a textbox where they can input the name of the account type, but this should only happen if they select Other.

**Solution in tcomb-form v0.8.2:**

```js
const AccountType = t.enums.of([
  'type 1',
  'type 2',
  'other'
], 'AccountType')

const KnownAccount = t.struct({
  type: AccountType
}, 'KnownAccount')

// UnknownAccount extends KnownAccount so it owns also the type field
const UnknownAccount = KnownAccount.extend({
  label: t.String,
}, 'UnknownAccount')

// the union
const Account = t.union([KnownAccount, UnknownAccount], 'Account')
```

Generally `tcomb`'s unions require a `dispatch` implementation in order to select the suitable type constructor for a given value and this would be the key in this use case:

```js
// if account type is 'other' return the UnknownAccount type
Account.dispatch = value => value && value.type === 'other' ? UnknownAccount : KnownAccount
```

The complete example:

```js
import React from 'react'
import t from 'tcomb-form'

const AccountType = t.enums.of([
  'type 1',
  'type 2',
  'other'
], 'AccountType')

const KnownAccount = t.struct({
  type: AccountType
}, 'KnownAccount')

const UnknownAccount = KnownAccount.extend({
  label: t.String,
}, 'UnknownAccount')

const Account = t.union([KnownAccount, UnknownAccount], 'Account')

Account.dispatch = value => value && value.type === 'other' ? UnknownAccount : KnownAccount

const App = React.createClass({

  getInitialState() {
    return {}
  },

  onChange(value) {
    this.setState({value})
  },

  onSubmit(evt) {
    evt.preventDefault()
    const v = this.refs.form.getValue()
    if (v) {
      console.log(v) // eslint-disable-line
    }
  },

  render() {
    return (
      <t.form.Form
        ref="form"
        type={Account}
        value={this.state.value}
        onChange={this.onChange}
      />
    )
  }

})
```

**Comment by alvaromb** [comment]
I think I've implemented a similar behaviour in one of our apps. I had a ``Select`` field with three values, one of them needed an extra ``Date`` field in the form. Does the unions try to solve this kind of problems?

**Comment by gcanti** [comment]
> Does the unions try to solve this kind of problems?

Yep. The example above seems pretty similar to your use case

**Comment by gcanti** [comment]
Hi @miqmago

> Is there any prevision to develop this functionality?

After https://github.com/gcanti/tcomb-form/issues/319 is fixed.

> depending on country value from another form I should show one address type or another

not sure unions are what you need though

**Comment by miqmago** [comment]
@gcanti so what would be the solution? Right now I've implemented a method that by brute force changes the tcomb object:
```javascript
export const changeAddressType = (tType, country) => {
    const newTType = tType;
    if (country === 'ESP') {
        newTType.AddressInSpain = t.maybe(AddressType);
        newTType.OverseasAddress = undefined;
    } else {
        newTType.AddressInSpain = undefined;
        newTType.OverseasAddress = t.maybe(OverseasAddressType);
    }
    return newTType;
};
```

Is there a better way (performance etc)? Can this method cause errors?
Thinking deeper, dispatch only depends on tcom value, isn't it? So there is no option to adapt tcomb object depending on an external value?

**Comment by gcanti** [comment]
If I understand correctly you have to handle this flow:

```
form1 onChange triggers => country is changed? => yes => then change the address type in form 2
```

So maybe something like this (basically is what unions would do under the hood)?

```js
const Country = t.enums.of(['US', 'ES'])

const Type1 = t.struct({
  country: Country
})

const AddressInSpain = t.struct({
  town: t.String
})

const OverseasAddress = t.struct({
  city: t.String,
  zip: t.String
})

const getAddressTypeByCountry = country => country === 'ES' ? AddressInSpain : OverseasAddress

const App = React.createClass({

  getInitialState() {
    return {
      value1: {},
      type2: AddressInSpain
    }
  },

  onChange(value1) {
    if (value1.country !== this.state.value1.country) {
      this.setState({ value1, type2: getAddressTypeByCountry(value1.country) })
    } else {
      this.setState({ value1 })
    }
  },

  render() {
    return (
      <...>
        <t.form.Form
          ref="form1"
          type={Type1}
          value={this.state.value1}
          onChange={this.onChange}
        />
        <t.form.Form
          ref="form2"
          type={this.state.type2}
        />
      </...>
    )
  }

})
```

**Comment by miqmago** [comment]
Yes thanks. In my case, the data structure is the following:

```javascript
const Type1 = t.struct({
  country: Country
})

const LegalEntityTypeBase = {
    CorporateName: TextMax80Type,
    TradeName: t.maybe(TextMax40Type),
    RegistrationData: t.maybe(RegistrationDataType),
    AddressInSpain: t.maybe(AddressType),
    // OverseasAddressType: t.maybe(OverseasAddressType),
    ContactDetails: t.maybe(ContactDetailsType),
};

const LegalEntityType = t.struct(LegalEntityTypeBase);

```

Then, depending on the value of country, I should ask for `AddressInSpain` or `OverseasAddressType`. Also I've been thinking that unions would'nt solve this problem as there is no common tag inside the type. In this case my thinking is that I should create two `LegalEntityTypes` and ask for each one in corresponding case. I'm wondering if there is any problem by using the function I posted before, to change the tcomb type:

```javascript
export const changeAddressType = (tType, country) => {
    const newTType = tType;
    if (country === 'ESP') {
        newTType.AddressInSpain = t.maybe(AddressType);
        newTType.OverseasAddress = undefined;
    } else {
        newTType.AddressInSpain = undefined;
        newTType.OverseasAddress = t.maybe(OverseasAddressType);
    }
    return newTType;
};
```

The result of this function is what I will use to get final data.

**Comment by gcanti** [comment]
If `tType` is a struct, it doesn't work (you could patch `tType.meta.props` but it's super hacky). Moreover the `Form` component doesn't detect a type change if the reference is the same.

My suggestion is to create two types.

**Comment by miqmago** [comment]
:+1: thanks!! :smile:

**Comment by miqmago** [comment]
Hi, I've seen the issue in tcomb-form is fixed, can I do something to help with this functionality here?

**Comment by gcanti** [comment]
Looks like porting the `getTypeFromUnion` function will do the trick https://github.com/gcanti/tcomb-form/commit/a643103fa5b418c4984e27c9a321a074512b7fb7
