### ISSUE TITLE
Question: using advanced form components

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#12]
External players are implementing advanced form components, e.g. using autocompleted with a tag item (https://github.com/JedWatson/react-select). Is there an easy way to integrate these external libraries with tcomb?

**Comment by gcanti** [comment]
> Is there an easy way to integrate these external libraries

I doubt it, react.js and react-native are not compatible out of the box

```
<div/> -> <View/>
<input type="text"/> -> <TextInput/>
...
```

**Comment by gcanti** [comment]
If you can afford the effort to convert a react.js component to react-native, you could write a tcomb-form-native component (extending `t.form.Component`). If you are interested, I can put up some documentation

**Comment by auser** [comment]
+1 @gcanti. I'm currently building a custom view for some selectors. This would be great

**Comment by gcanti** [comment]
@auser 

Hi,
These days I'm refactoring tcomb-form (v0.4 -> v0.5). 
Once finished, I'll port some tcomb-form's features (useful for custom views) and documentation to tcomb-form-native.

**Comment by mschipperheyn** [comment]
Putting up docs for that makes sense to me. I imagine I will be needing to do that soon.

**Comment by romanonthego** [comment]
yep, custom components will be much appreciated.

**Comment by gcanti** [comment]
> I'll port some tcomb-form's features (useful for custom views) and documentation to tcomb-form-native.

Working in this...

**Comment by gcanti** [comment]
added Transformers section to docs:

https://github.com/gcanti/tcomb-form-native#transformers

**Comment by gcanti** [comment]
Closing in favour of #28
