### ISSUE TITLE
refactor code inside customFormTemplate() to its own file

### ISSUE THREAD

**Issue by flizzer** [gcanti/tcomb-form-native#120]
Hi again.  I love how I'm able to use the customFormTemplate() method to override and gain complete freedom over how my form is presented; so, awesome work first of all!  

My code inside that method has grown to be way too long, however.  How can I refactor that code to a stand-alone template and just reference it?  Do I have to create a class which extends Component and then return the stand-alone template?

Thanks for your feedback and assistance in advance.

Brian

**Comment by alvaromb** [comment]
Hello @flizzer.

You can follow the behaviour of the bootstrap templates in the library. For instance, look at ``checkbox.js`` https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/checkbox.js

That's a template that you export and then you can use it with the ``template`` option for your fields. Look [here](https://github.com/gcanti/tcomb-form-native/blob/master/lib/components.js#L265) to see how the ``Checkbox`` component uses it or accepts one from the options.

**Comment by flizzer** [comment]
Thanks very much for this.  I did create a stand-alone template and a class that extends component.  Do I then reference that component in JSX somewhere?  Thanks.

Brian
