### ISSUE TITLE
Build fails in RN 0.21 with Error  "Failed to build DependencyGraph: Naming collision detected "

### ISSUE THREAD

**Issue by iZaL** [gcanti/tcomb-form-native#124]
Naming collision detected: /Users/NAME/React-Native/PROJECT/node_modules/react-native/Libraries/StyleSheet/ColorPropType.js collides with /Users/NAME/React-Native/PROJECT/node_modules/tcomb-form-native/node_modules/react-native/Libraries/StyleSheet/ColorPropType.js

**Comment by alvaromb** [comment]
Hello @iZaL!

Have you tried to restart the packager, clean npm cache and delete watchman watches?

**Comment by iZaL** [comment]
Yes tried everything. The only solution was to delete the node_modules directory within tomb-native folder

**Comment by alvaromb** [comment]
`tcomb-form-native` no longer depends on `react-native`. Which version of `tcomb-form-native` are you trying to install?

**Comment by gcanti** [comment]
@alvaromb AFAIK last published version (0.3.3) still depends on RN in package.json

**Comment by iZaL** [comment]
@alvaromb tried on V0.3.3

**Comment by alvaromb** [comment]
True @gcanti  https://github.com/gcanti/tcomb-form-native/blob/v0.3.3/package.json#L21

@iZaL have you tried the library under RN 0.20?

**Comment by iZaL** [comment]
it works on RN 0.20 for some odd reason .. I can hardly say whether the issue lies within the library itself

**Comment by alvaromb** [comment]
I'm pretty sure this is an upstream issue.

Have you looked at this issue, @iZaL https://github.com/facebook/react-native/issues/5390 ?

**Comment by iZaL** [comment]
@alvaromb , I'll try if the fixes mentioned in the link gonna fix the issue and get back to you. thanks

**Comment by alvaromb** [comment]
Any news @iZaL ?

**Comment by rturk** [comment]
Works in RN 0.20, fails with RN 0.21. 

At least for me it seems to be related to Navigator Experimental. This is a new feature that react native 21 introduced.

Failed to build DependencyGraph: Naming collision detected: 
/node_modules/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationRouteStack.js 
collides with 
/node_modules/tcomb-form-native/node_modules/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationRouteStack.js

**Comment by alvaromb** [comment]
The workaround seems to be removing `react-native` from `tcomb-form-native`' modules folder. This will be solved with 0.4 release.

**Comment by iZaL** [comment]
@alvaromb the steps mentioned in this link [http://github.com/facebook/react-native#5390](url) above is not solving the issue. perhaps removing the react-native folder is the only temporary solution.

**Comment by alvaromb** [comment]
Yeah, seems like 0.3.3 is not compatible with 0.21. Please wait for 0.4 release, which should be out during the following days.

**Comment by iZaL** [comment]
ok, I ran into another problem, not sure whether deleting the react-native folder is the reason for this. I am getting "**[tcomb] [tcomb-form-native] missing stylesheet config**" error. the latter **Naming collision detected** error throws exception during the build process, but this error throws only when I'm navigating to the page that is using this library.

**Comment by alvaromb** [comment]
Hello @iZaL !

`tcomb-form-native` 0.4 is out, please install that version and check if the error still occurs.

**Comment by alvaromb** [comment]
Will reopen if the error is still present. Thanks for reporting @iZaL !!!

**Comment by massimopalmieri** [comment]
I'm getting the same error with tcomb-form-native 0.4

**Comment by iZaL** [comment]
this happens only when the hot reloading is enabled
