### ISSUE TITLE
How to reference stand-alone template

### ISSUE THREAD

**Issue by flizzer** [gcanti/tcomb-form-native#125]
Per issue https://github.com/gcanti/tcomb-form-native/issues/120, I've created a stand-alone template and class in the components.js file, and exported it from the index.js file in the /templates/bootstrap directory (screenshots attached in case they might help).  My goal is to encapsulate the lengthy jsx that I'm using for my template in a separate file/component which I can reference without having to override the default template in the same file where all my other form logic is.  It's just too long.  Yet when I try to reference my new component, I get the attached error.  I'm obviously not doing something correctly, I just need a little more guidance as to how to properly reference my template within the constructs of tomb-form-native and react-native.  Sorry to open a new issue, but I need to clear this hurdle so my code is more maintainable.  Thanks in advance for any further assistance.
<img width="435" alt="attempted use of registrationform component" src="https://cloud.githubusercontent.com/assets/596833/13373509/a6e307e0-dd37-11e5-9823-123e09d3912d.png">
<img width="486" alt="custom class" src="https://cloud.githubusercontent.com/assets/596833/13373510/a6f0eaae-dd37-11e5-9608-4dc2b08cd309.png">
<img width="478" alt="custom template" src="https://cloud.githubusercontent.com/assets/596833/13373512/a6f21a64-dd37-11e5-91f4-da2a7584a101.png">
<img width="601" alt="error" src="https://cloud.githubusercontent.com/assets/596833/13373511/a6f185ea-dd37-11e5-9b60-01772a34ec2c.png">

**Comment by gcanti** [comment]
> I've created a stand-alone template and class in the components.js file, and exported it from the index.js file in the /templates/bootstrap directory

Hi, not sure I'm follow (are you changing the code *inside* the `tcomb-form-native` library??).

This is the documentation explaining how to override a default template globally and / or locally:
https://github.com/gcanti/tcomb-form-native#templates

**Comment by flizzer** [comment]
Sorry for any confusion.  I thought what I needed to do, based on the previous issue, was create a template in the bootstrap folder and create a class using it, similar to checkbox.  Does that not need to go in the components.js file?  Further, do I not need to export the template in the index.js file?  My goal is not to change the tomb-form-native library, but I thought I needed to make the changes to those files to solve my problem.  Maybe I should reset.  I was able to override the template locally thanks to your tutorial, but the code has grown quite long; so, I want to encapsulate that code in a separate template, I think.  I see this line in the section about templates in order to override the layout globally: var templates = {...}; but I don't quite understand what I'm supposed to do there to use my template.  Hope that sheds light on what I'm trying to do.  As always, your help is appreciated.  Thanks.

**Comment by alvaromb** [comment]
You can set your custom template per field inside your `options` dictionary, for instance:

```js
import YourCustomTemplate from './YourCustomTemplate'
...
options: {
  fields: {
    username: {
      template: YourCustomTemplate,
    },
  }
}
```

**Comment by alvaromb** [comment]
Just a quick reminder, you should not create any files inside the `node_modules/tcomb-form-native/` or any other npm installed module. Put those templates inside your app code and then import as if it was any other component.

**Comment by flizzer** [comment]
Thanks for this feedback.  Think I was making it harder than it really
was.  Sorry for the noob questions as this is my first go-round with
tcomb-form-native, react-native, and mobile for that matter.  Thanks again.

Brian

**Comment by alvaromb** [comment]
Happy to have helped you @flizzer!

If you need help regarding React Native, please consider to post your questions in StackOverflow. Most of the RN community is there answering.
