### ISSUE TITLE
Support for DatepickerIOS

### ISSUE THREAD

**Issue by ChangJoo-Park** [gcanti/tcomb-form-native#126]
Hello, I coded some app with tcomb-form-native.
I need only date field with my app.
How do I get only date picker? 

currently, datepicker has hours.

**Comment by gcanti** [comment]
It's already supported, you can use the `mode` option (https://facebook.github.io/react-native/docs/datepickerios.html#content)

Example

```js
var Type = t.struct({
  mydate: t.Date
});

var options = {
  fields: {
    mydate: {
      mode: 'date' // 'time' or 'datetime'
    }
  }
};
```

**Comment by ChangJoo-Park** [comment]
Thank you @gcanti
