### ISSUE TITLE
Missing docs: locals.onChange for struct templates takes fieldName & fieldValue, not just value.

### ISSUE THREAD

**Issue by dentrado** [gcanti/tcomb-form-native#127]
I tried to make a custom template for a struct (see below), but couldn't get the locals.onChange to work as expected until I looked at the source code for Struct. 
```
const Profile = t.struct({
  image: t.struct({ uri: t.String }),
  name: t.String, 
};
const options = {
  fields: {
    image: {
      template: ImagePicker,
    }
  }
};

// In the Imagepicker template
locals.onChange({uri: 'SomefileUri'}); // doesn't work
locals.onChange('uri', 'SomefileUri'); // works
```
I couldn't find this information anywhere in the documentation for tcomb-form-native (or tcomb-form).

**Comment by gcanti** [comment]
Hi @dentrado,
Admittedly the documentation regarding custom templates is a bit terse. I appreciate any contribution to the topic.

For what concerns your use case, structs' `locals.onChange` function it's not meant to be used directly, the idiomatic way to write a custom template for structs is leveraging `locals.inputs`.
