### ISSUE TITLE
Colorize or Style Switch component

### ISSUE THREAD

**Issue by jayesbe** [gcanti/tcomb-form-native#128]
How is the Switch component (Boolean type) styled ?

Its showing up as a teal color on Android and it seems to be unchangeable ?

**Comment by gcanti** [comment]
The default template contains the official `Switch` component https://facebook.github.io/react-native/docs/switch.html

**Comment by jayesbe** [comment]
There is no style example.  I have tried setting color and backgroundColor. The backgroundColor puts a box of color behind the switch. The switch remains the exact same color, grey and teal.  I have yet to see an example of a differently colorized switch.  Do you have an example ?

**Comment by jayesbe** [comment]
https://github.com/gcanti/tcomb-form-native/commit/8a4e24b715f8bc16012f94e440c32d4c5b662622

shows you removed the color setting from the checkbox style because it was throwing an error in the logs. iOS has the tint options.. but not android.. Im guessing this is a RN core issue ?

**Comment by alvaromb** [comment]
Hi @jayesbe !

Changing the `Switch` color isn't supported yet in React Native, check the props http://facebook.github.io/react-native/docs/switch.html#content

It's an upstream issue, will add support for it when the component gets updated.

**Comment by jayesbe** [comment]
Got it thanks!

**Comment by otoinsa** [comment]
<resources>
    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:windowIsTranslucent">true</item>
        
        <item name="colorControlActivated">#ffffff</item>
    </style>
</resources>


This in android native code will make all controls (checkboxes and radio buttons as well)
white; not perfect, but somewhat works

**Comment by alvaromb** [comment]
Cool @otoinsa! Thanks!
