### ISSUE TITLE
Android TextInput border not showing

### ISSUE THREAD

**Issue by ssomnoremac** [gcanti/tcomb-form-native#129]
- tcomb-form-native v0.4.0
- react-native v0.20.0

### Expected behaviour
TextInput looks the same on both platforms

### Actual behaviour
TextInput in Android only has a bottom "underline" and no border. [Known issue](https://facebook.github.io/react-native/docs/known-issues.html#text-input-border)

### Suggestion
Use a View wrapper around Android TextInputs and apply the textbox styles there --or-- apply background color instead to imply a text input area

**Comment by alvaromb** [comment]
Thanks for your feedback @ssomnoremac. Definitely the bootstrap templates look a bit weird under Android, but I encourage you to use your custom stylesheet in any app you develop.

Anyway, maybe we could slightly modify those templates for Android.

**Comment by alvaromb** [comment]
@gcanti what do you feel about this? Maybe we can put some screenshots of form customization in the README as an example of what can be done.

And speaking of this specific request @ssomnoremac, my suggestion is that you should develop two stylesheets and use `stylesheet.android.js`/ `stylesheet.ios.js` or `Platform` to set the style for both platforms. The goal of the current stylesheet included is more aligned to having a reference or example, I wouldn't recommend to use it out of the box.

**Comment by ssomnoremac** [comment]
@alvaromb, problem is it can't be accomplished with styles. Borders aren't applied even with a custom stylesheet. With the `Picker` I just wrap it in a view and give the views the styles I want. We could do the same here and then have a `containerStyle` options field.

**Comment by gcanti** [comment]
> what do you feel about this

This is clearly an upstream issue, going to tag this as Wontfix (btw it's really disappointing to see such a basic issue not yet solved upstream in 3 months).
You can use a custom template as a workaround.

**Comment by jaimecorrea** [comment]
Sorry, but I couldn't solve this issue, is there any example of how to resolve it?

**Comment by ssomnoremac** [comment]
Wrap it in a view and style the view
