### ISSUE TITLE
Multi-Select

### ISSUE THREAD

**Issue by mintotsai** [gcanti/tcomb-form-native#131]
How does one create a multi select field using tcomb-form-native?

**Comment by alvaromb** [comment]
Hello @mintotsai !!

You have to create your own factory to do that. Take this as an example https://github.com/APSL/react-native-floating-label/blob/master/FloatingLabel.js

Basically you would end with something like this (`options` are a list of possible selection options):
```js
<View>
  {locals.options.forEach(option => (
    <TouchableOpacity onPress={() => this.setState({value: this.state.value.concat(option)})}>
      <Text>{option.name}</Text>
    </TouchableOpacity>
  ))}
</View>
```

Then, you have to decide which type should back your multi-selection. That's a pure implementation decision that you should leverage, I'll leave that to you ;)

**Comment by appbeijing** [comment]
can you show a simple example about multi select field? thanks。

**Comment by mintotsai** [comment]
@appbeijing I ended up creating a factory. Here's the code:
```
// MultiSelect.js
import React, { View, Text } from 'react-native'
import t from 'tcomb-form-native'
var Checkbox = require('react-native-checkbox');

// extend the base Component
class MultiSelect extends t.form.Select {

  constructor (props) {
    console.log(props);
    super(props);
    var locals = super.getLocals();
    var isChecked = {};
    if (locals.options != null) {
      locals.options.forEach(function(item) {
        isChecked[item.text] = false;
      });
    }

    if (this.props.value != null) {
      this.props.value.forEach(function(item) {
        isChecked[item] = true;
      });
    }
    this.state = {
      isChecked: isChecked
    }
  }

  getTransformer() {
    return MultiSelect.transformer();
  }

  // this is the only required method to implement
  getTemplate() {
    let self = this;
    return function (locals) {
      console.log(locals);

      var stylesheet = locals.stylesheet;
      var formGroupStyle = stylesheet.formGroup.normal;
      var controlLabelStyle = stylesheet.controlLabel.normal;
      var checkboxStyle = stylesheet.checkbox.normal;
      var helpBlockStyle = stylesheet.helpBlock.normal;
      var errorBlockStyle = stylesheet.errorBlock;

      if (locals.hasError) {
        formGroupStyle = stylesheet.formGroup.error;
        controlLabelStyle = stylesheet.controlLabel.error;
        checkboxStyle = stylesheet.checkbox.error;
        helpBlockStyle = stylesheet.helpBlock.error;
      }

      var label = locals.label ? <Text style={controlLabelStyle}>{locals.label}</Text> : null;
      var help = locals.help ? <Text style={helpBlockStyle}>{locals.help}</Text> : null;
      var error = locals.hasError && locals.error ? <Text style={errorBlockStyle}>{locals.error}</Text> : null;

      var viewArr = [];
      locals.options.forEach(function(item) {
        viewArr.push(<Checkbox
          ref={item.text}
          label={item.text}
          checked={self.state.isChecked[item.text]}
          onChange={(checked) => {self._onChange(item, locals, checked)}}
        />);
      });

      return (
        <View style={formGroupStyle}>
          {label}
          {viewArr}
          {help}
          {error}
        </View>
      )
    }
  }

  getOptions() {
    var options = this.props.options;
    var items = options.options ? options.options.slice() : this.getOptionsOfEnum(this.getEnum());
    if (options.order) {
      items.sort(this.getComparator(options.order));
    }
    return items;
  }

  _onChange(item, locals, checked) {
    var isChecked = this.state.isChecked;
    isChecked[item.text] = checked

    var changeArr = [];
    for (var key in isChecked) {
      if (isChecked[key] == true) {
        changeArr.push(key);
      }
    }
    locals.onChange(changeArr);

    this.setState({
      isChecked: isChecked
    });

    // Not recommended. A better way?
    //this.forceUpdate();

  }
}

MultiSelect.transformer = () => {
  return {
    format: value => Array.isArray(value) ? value : [],
    parse: value => value ? value : []
  };
};

export default MultiSelect
```

This is how I'm using it:
```
item.picklist.forEach(function(picklistItem) {
    picklistOptions = picklistOptions.concat({value: picklistItem.value, text: picklistItem.label});
});
form = intakeForm.extend({[item.name]: t.maybe(t.list(t.String)) });
options.fields[item.name] = {label: item.label, factory: MultiSelect, options: picklistOptions};
```

Hope this helps!

**Comment by appbeijing** [comment]
`'use strict';
import React from 'react';
import t from 'tcomb-form-native'
import{
  StyleSheet,
  Text,
  ScrollView,
  TouchableWithoutFeedback,
  TextInput,
  Switch,
  Picker,
  TouchableHighlight,
  View,
} from 'react-native';


function StrToArr(str){//nann&nnnn
	if(str.length>0){
		return str.split("&");
	}else{
		return [];
	}
}


class MultiSelect extends t.form.Select {
	
	constructor(props){
		super(props);
		var locals = props.options;
	}
	
	_onChange(val){
		
		var arr=StrToArr(this.state.value);
		var n=arr.indexOf(val);
		
		if(n<0){
			//添加
			arr.push(val);
		}else{
			//删除
			arr.splice(n,1);
		}
		
		var value=arr.join("&");
		this.onChange(value);
		this.setState({value:value});
	}

	 getTemplate(){
		let self = this;
		return function(locals){
			var stylesheet = locals.stylesheet;
			var formGroupStyle = stylesheet.formGroup.normal;
			var controlLabelStyle = stylesheet.controlLabel.normal;
			var checkboxStyle = stylesheet.checkbox.normal;
			var helpBlockStyle = stylesheet.helpBlock.normal;
			var errorBlockStyle = stylesheet.errorBlock;
			var checkboxs=stylesheet.checkboxs;
			var bgColor=stylesheet.bgColor;
			var wrap=stylesheet.wrap;

			if(locals.hasError){
				formGroupStyle = stylesheet.formGroup.error;
				controlLabelStyle = stylesheet.controlLabel.error;
				checkboxStyle = stylesheet.checkbox.error;
				helpBlockStyle = stylesheet.helpBlock.error;
			}

			var label = locals.label ? <Text style={controlLabelStyle}>{locals.label}</Text> : null;
			var help = locals.help ? <Text style={helpBlockStyle}>{locals.help}</Text> : null;
			var error = locals.hasError && locals.error ? <Text style={errorBlockStyle}>{locals.error}</Text> : null;
			
			var arr=[];
			var options = locals.options;
			options.map(function(obj,index){
				var val=obj.value;
				var checks=[checkboxs];
				var arrs=StrToArr(locals.value);	
				if(arrs.indexOf(obj.value)<0){
					checks=[checkboxs]
				}else{
					checks=[checkboxs,bgColor]
				}
				
				var tmp=<TouchableWithoutFeedback onPress={function(){self._onChange(val)}} key={index}>
							<View style={wrap}>
								<View style={checks} ref="input"></View><Text>{obj.label}</Text>
							</View>
						</TouchableWithoutFeedback>;
				arr.push(tmp)
			})
			
			return(
				<View>
					{label}
					{arr}
					{help}
					{error}
				</View>
			)
		 }
	 }

	getOptions() {
		var options = this.props.options;
		var items = options.options;
		if (options.order) {
			items.sort(this.getComparator(options.order));
		}
		return items;
	}
}


MultiSelect.transformer = () => {
  return {
    format: value => Array.isArray(value) ? value : [],
    parse: value => value ? value : []
  };
};

module.exports=MultiSelect;`


how to use it
//创建表单
var Person = t.struct({
	position:t.String,
});

var options = {
	stylesheet:theme.defaults,
	fields: {
		position:{
			auto:"auto",
			nullOption:false,
			label:"所在地",
			options:[{value:'YDL',label:'意大利'},{value:'FLX',label: '法兰西'},{value:'YGL',label: '英格兰'}],
			factory:widget.radio,
		},
     }
}

**Comment by dyguests** [comment]
@mintotsai Could you expain that what is item,form, picklistOptions?
or give a sample.

I'm not good at react-native.

**Comment by Maksym-Vasyukov** [comment]
@mintotsai can you elaborate on the way you present the data to the factory? How do you structure your list in this case?

**Comment by Maksym-Vasyukov** [comment]
in your function 
```
getOptions() {
    var options = this.props.options;
    var items = options.options ? options.options.slice() : this.getOptionsOfEnum(this.getEnum());
    if (options.order) {
      items.sort(this.getComparator(options.order));
    }
    return items;
  }
```

you extract your data for the Multiple Select by either copying from the options, or with the `getOptionsOfEnum()` function.
Unfortunatelly you dont provide an example for the data structure when used in options.
I tried using the enum as for the simple selector, but the `getOptionsOfEnum()` function seems not to be defined. I receive the same error all along:

`
this.getOptionsOfEnum is not a function. (In 'this.getOptionsOfEnum(this.getEnum())', 'this.getOptionsOfEnum' is undefined)`

**Comment by yai111** [comment]
@mintotsai 's coding is not working for 0.47.x from my testing, so I updated code:
```
// MultiSelect.js
import React from 'react';
import { View, Text } from 'react-native';
import t from 'tcomb-form-native';
import Checkbox from 'react-native-checkbox';
import autobind from 'autobind-decorator';
import _ from 'lodash';

class TcombMultiSelect extends t.form.Select {
  constructor(props) {
    super(props);
    const locals = super.getLocals();
    const isChecked = {};
    const { options, value } = locals;
    let valuedItem = null;
    options &&
      options.map((item) => {
        valuedItem = _.find(options, value);
        isChecked[item.text] = !!valuedItem;
      });

    this.state = {
      isChecked,
    };
  }

  getTransformer() {
    return TcombMultiSelect.transformer();
  }

  getTemplate() {
    return (locals) => {
      const stylesheet = locals.stylesheet;
      let formGroupStyle = stylesheet.formGroup.normal;
      let controlLabelStyle = stylesheet.controlLabel.normal;
      let checkboxStyle = stylesheet.checkbox.normal;
      let helpBlockStyle = stylesheet.helpBlock.normal;
      const errorBlockStyle = stylesheet.errorBlock;

      if (locals.hasError) {
        formGroupStyle = stylesheet.formGroup.error;
        controlLabelStyle = stylesheet.controlLabel.error;
        checkboxStyle = stylesheet.checkbox.error;
        helpBlockStyle = stylesheet.helpBlock.error;
      }

      const label = locals.label ? <Text style={controlLabelStyle}>{locals.label}</Text> : null;
      const help = locals.help ? <Text style={helpBlockStyle}>{locals.help}</Text> : null;
      const error =
        locals.hasError && locals.error ? (
          <Text style={errorBlockStyle}>{locals.error}</Text>
        ) : null;

      const viewArr = [];

      locals.options.map((item, index) =>
        viewArr.push(<Checkbox
            key={index}
            ref={item.text}
            label={item.text}
            checked={this.state.isChecked[item.text]}
            onChange={(checked) => {
              this._onChange(item, locals, !checked);
            }}
          />, ), );

      return (
        <View style={formGroupStyle}>
          {label}
          {viewArr}
          {help}
          {error}
        </View>
      );
    };
  }

  getOptions() {
    const { options } = this.props;
    const items = options.options ? options.options.slice() : this.getOptionsOfEnum(this.getEnum());
    if (options.order) {
      items.sort(this.getComparator(options.order));
    }
    return items;
  }

  @autobind
  _onChange(item, locals, checked) {
    const { isChecked } = this.state;
    isChecked[item.text] = checked;
    const changeArr = [];

    _.forIn(isChecked, (isCheckedItem) => {
      isCheckedItem && changeArr.push(isCheckedItem);
    });

    locals.onChange(changeArr);

    this.setState({
      isChecked,
    });

    // Not recommended. A better way?
    // this.forceUpdate();
  }
}

TcombMultiSelect.transformer = () => ({
  format: value => (Array.isArray(value) ? value : []),
  parse: value => value || [],
});

export default TcombMultiSelect;

```

**Comment by Maksym-Vasyukov** [comment]
@yai111 

this part is already causing an error. I am getting a RCTFatal error on the `@autobind` line.

```javascript
  @autobind
  _onChange(item, locals, checked) {
    const { isChecked } = this.state;
    isChecked[item.text] = checked;
    const changeArr = [];

    _.forIn(isChecked, (isCheckedItem) => {
      isCheckedItem && changeArr.push(isCheckedItem);
    });

    locals.onChange(changeArr);

    this.setState({
      isChecked,
    });

    // Not recommended. A better way?
    // this.forceUpdate();
  }
```

![screenshot](https://imgur.com/eNDv8U7.png)

**Comment by yai333** [comment]
@Maksym-Vasyukov Probably you are missing babel-plugin-transform-decorators-legacy dependency 
and set 
```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```
in .babelrc

or you can remove the @autobind decorator,  add 
```
this. _onChange = this. _onChange.bind(this); 
```
in constructor

**Comment by Maksym-Vasyukov** [comment]
@yai111 great, fixed the building problem with the constructor solution.
Now I am stuck at the same problem as six days ago with the former solution.

😄

**Comment by yai333** [comment]
@Maksym-Vasyukov 
```
const fields = [
  t.struct({
    registrationLocation: t.list(t.String),
  }),
...

const options = [
  {
    fields: {
      registrationLocation: {
        label: 'Registration location *',
        factory: TcombMultiSelect,
        options: [
          { value: 'blabla..', text: 'blabla' },
          { value: 'blabla', text: 'blabla' },
        ],
      },
....
```

**Comment by anishroff** [comment]
@yai333 I have used your code for multi select options. The field is mandatory like i.e. not t.maybe but t.list so it should give error when form.getvalue is called. Its not giving error. Any idea how I can override the validate method ? Can you please assist ?
