### ISSUE TITLE
TextInput onBlur callback as option?

### ISSUE THREAD

**Issue by flyingace** [gcanti/tcomb-form-native#133]
- tcomb-form-native v0.4.0
- react-native v0.21.0

For the TextInput field type you list among other standard options onBlur, onEndEditing, onFocus and  onSubmitEditing. Can you give an example of how a callback would be indicated for these options?

```
var options = {
  fields: {
    textField: {
      onFocus: [ How do I code the callback here? ]
    }
  }
};
```

I find this library to be immensely helpful. Thanks for all of your work!

**Comment by gcanti** [comment]
Hi @flyingace,

`onFocus` will be passed to the native `TextInput` component as it is

https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L44

**Comment by alvaromb** [comment]
Basically, you can do this @flyingace 

```js
let options = {
  fields: {
    textField: {
      onFocus: () => { // Your code },
      // or
      onFocus: this._myOnFocusFunction.bind(this),
    },
  },
}

_myOnFocusFunction () {
  // Your code here
}
```

**Comment by flyingace** [comment]
Thanks to you both! That's very helpful.

**Comment by alvaromb** [comment]
Glad to have helped! :wink:

**Comment by sirwoetang** [comment]
Is there any way to scroll the focussed text component to the top of the page? I believe this should be a natural next step for most forms.
 
Something like this?

`
  onFocus (componentName) {
    if (path) {
      var component = this.refs.form1.getComponent(path)
      this.refs._requestScrollView.scrollTo({y: component.height})
    }
  }
`
