### ISSUE TITLE
how to add icon in form

### ISSUE THREAD

**Issue by HellMagic** [gcanti/tcomb-form-native#135]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.21.0

### Expected behaviour

e, i just want to add my icon on all the form field

### Actual behaviour

should we support add custom icon to form field

### Steps to reproduce
NO
1.
2.
3.

### Stack trace and console log

NO
```
```
if we support it please let me know, maybe i miss it, if we don't support now but we will, it's ok, the project also is very awesome!!! cheers ~ Thanks very much!!!

**Comment by alvaromb** [comment]
You can do it with a custom template, full docs here https://github.com/gcanti/tcomb-form-native#templates

Basically, you can do this:

```js
function myCustomTemplate(locals) {

  var containerStyle = {...};
  var labelStyle = {...};
  var textboxStyle = {...};

  return (
    <View style={containerStyle}>
      <Text style={labelStyle}>{locals.label}</Text>
     // Put your icon somewhere here
      <TextInput style={textboxStyle} />
    </View>
  );
}
```

With custom templates you can fully customise how your form looks.

**Comment by geek96** [comment]
@jaspreetsingh2701 
https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md
