### ISSUE TITLE
Password is visible on Android

### ISSUE THREAD

**Issue by Bob1993** [gcanti/tcomb-form-native#136]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.22.2
- platform Android

### Problem  
the password show visible content though I use
`password: true`
`secureTextEntry: true`.

**Comment by rogerroelofs** [comment]
I had the same problem and had to remove the keyboardtype attribute to get it to display properly.  This is technically not a tcomb-form-native problem since the lib is just passing the attributes through to RN

**Comment by gcanti** [comment]
> This is technically not a tcomb-form-native problem since the lib is just passing the attributes through to RN

Thanks @rogerroelofs for clarifying.

**Comment by alvaromb** [comment]
Does this still happen with newer RN versions? Can't reproduce it! Closing by now, please feel free to ping me if it still happens.

**Comment by Bob1993** [comment]
@alvaromb  I'm too busy to respond here recently, thanks for your help

**Comment by abuammar** [comment]
Problem

the password show visible content though I use
password: true
secureTextEntry: true.
