### ISSUE TITLE
Textbox component displays extra characters after `getValue()`

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#142]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4
- react-native v0.23.1

### Expected behaviour

`getValue()` should clear text inputs.

### Actual behaviour

`getValue()` keeps an extra character displayed.

### Steps to reproduce

1. Use RN 0.23.
2. Set-up a `Form` with some text fields.
3. Introduce some values and call `getValue()`.

This is an upstream issue that can be tracked here https://github.com/facebook/react-native/issues/6936, but I'm wondering if we should change the `Textbox` transformers:

```js
Textbox.transformer = {
  format: value => Nil.is(value) ? '' : value,    // Changing null to '' solves the issue
  parse: toNull
};

Textbox.numberTransformer = {
  format: value => Nil.is(value) ? '' : String(value),   // Changing null to '' solves the issue
  parse: parseNumber
};
```

**Comment by gcanti** [comment]
> but I'm wondering if we should change the Textbox transformers

Yep. We've done the same in the last release of `tcomb-form`: https://github.com/gcanti/tcomb-form/commit/5af241d89077b883c80a994464cc1c10ac7673be

**Comment by alvaromb** [comment]
Ok, I'm sending a PR in a moment.

**Comment by alvaromb** [comment]
There you go, @gcanti :sunglasses:

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.4.2
