### ISSUE TITLE
Styling TextInput when being enabled after being disabled

### ISSUE THREAD

**Issue by jeromegrosse** [gcanti/tcomb-form-native#144]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.2
- react-native v0.22.2

### Expected behaviour

The textinput should keep its underlining styling when enabling it after being first disabled.

### Actual behaviour

The underlining styling disappears if the text input is enabled after being disabled.

![out](https://cloud.githubusercontent.com/assets/4560899/14526409/5d5b6c12-0243-11e6-8cde-95a68a23bdd5.gif)

### Steps to reproduce

The code used to perform this action looks like this:
```javascript
import React, {
    AppRegistry,
    Component,
    StyleSheet,
    Text,
    View,
} from 'react-native';

import t from 'tcomb-form-native';

var Form = t.form.Form;
var Search = t.struct({
  field1: t.maybe(t.String),
  field2: t.maybe(t.String),
  toggle: t.Boolean
});


class MyClass extends Component {
    constructor() {
        super();
        this.state = {
            options: {
                fields: {
                    field1: {label: 'Field1'},
                    field2: {label: 'Field2'},
                    toggle: {label: 'Enable/Disable field2'},
                }
            },
            value: {},
        };
    }

    onChange(value) {
        var options = t.update(this.state.options, {
            fields: {
                field2: {
                    editable: {'$set': !value.toggle}
                }
            }
        });
        this.setState({options: options, value: value});
    }

    render() {
        return (
            <View style={styles.container}>
                <Form
                    ref="form"
                    type={Search}
                    options={this.state.options}
                    value={this.state.value}
                    onChange={(value) => this.onChange(value)}
                />
            </View>
        );
    }
}
```

### Stack trace and console log
No output or error thrown

```
```

**Comment by gcanti** [comment]
Is this an upstream issue or it happens because of tcomb-form-native?

**Comment by alvaromb** [comment]
`editable` is a `TextInput` prop, we're just passing the value to RN.

**Comment by alvaromb** [comment]
This looks to me as an upstream issue, take a look at this:

https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L41

And:

https://github.com/facebook/react-native/blob/dd8caf4cf21941aff5afc7e919ced58ec564f3a3/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java#L326-L329

Please open the issue into the `react-native` repo or better, ask how you can customize the disabled state in StackOverflow (probably you'll get an answer there faster).
