### ISSUE TITLE
autofocus seems to hide the screen behind the keyboard when set to true.

### ISSUE THREAD

**Issue by SudoPlz** [gcanti/tcomb-form-native#147]
Not sure if this is a react-native problem or a tcomb-form problem, but since it can be resolved manually I thought of opening an issue here.

I have an email form, but when I set its autofocus option to true, the keyboard DOES show up when the screen starts, but all the content is hidden behind the Android keyboard.

On the other hand if I minimize the keyboard and tap on the input text field on my own, nothing gets hidden, the whole view goes upwards and I can see both the field AND the keyboard.

**Comment by alvaromb** [comment]
Hello @SudoPlz!

Can you reproduce it _withouth_ `tcomb-form-native`? Seems more an upstream issue...

**Comment by jeromegrosse** [comment]
I encounter the same problem this week. As a temporary workaround, I used the code provided here: http://stackoverflow.com/a/32593814

**Comment by alvaromb** [comment]
Hello! 

I'm closing this by now, it looks like an upstream issue and it's been inactive for a while. Please ping me if you need further info 😉
