### ISSUE TITLE
Required field if empty error is showing but when start typing in it the error does not go away

### ISSUE THREAD

**Issue by pgmemk** [gcanti/tcomb-form-native#148]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.2
- react-native v0.18

### Expected behaviour

When start typing in required field the error message should disappear

### Actual behaviour

The error message stays

### Steps to reproduce

1. create a Struct with required text fields and submit button
2. click submit button without setting any values in the required fields
3. type in the field where you see the error message

I debugged the code and I see that onChange gets called and render function also repaints (or trying to) the form but the messages stay
![image](https://cloud.githubusercontent.com/assets/3690867/14733014/a0bc0b52-082d-11e6-86df-3dfaca1dcabc.png)

**Comment by alvaromb** [comment]
This is interesting. I'll put it on my queue. Thanks @pgmemk!

**Comment by alvaromb** [comment]
@gcanti are you happy with including this for 0.5?

**Comment by gcanti** [comment]
At first glance it doesn't seem a bug. By default the error state of an input is updated only when `validate` or `getValue` is called. If you want "continuous validation" you may want to put a `validate` call in the `onChange` handler:

```js
...
onChange(value, path) {
  this.refs.form.getComponent(path).validate()
  this.setState({ value })
}
...
```

or call a custom handler:

https://github.com/gcanti/tcomb-form-native/issues/75

**Comment by pgmemk** [comment]
Thank you. 
I'm using custom handler :).
