### ISSUE TITLE
[Request] support style arrays like React does natively?

### ISSUE THREAD

**Issue by braco** [gcanti/tcomb-form-native#149]
Would be nice to be able to pass in style arrays.

RN supports this:

```
<View style={[styles.one, styles.two]}></View>
```

which merges the trees together.

I suppose this is a request to modify the default bootstrap templates.

**Comment by appbeijing** [comment]
var options = {
	stylesheet:theme.defaults,// your style
	fields: {}
}

**Comment by alvaromb** [comment]
Can you elaborate more the issue, @braco ?
