### ISSUE TITLE
Layout question

### ISSUE THREAD

**Issue by sibeliusseraphini** [gcanti/tcomb-form-native#151]
How can I display to text component one beside another?

is this possible?

**Comment by alvaromb** [comment]
Yes @sibeliusseraphini, with a custom template (credit card example):

```js
/* @flow */

import React, { View } from 'react-native'

function creditCard (locals: Object) {
  return (
    <View>
      {locals.inputs.card_number}
      <View style={styles.expirationContainer}>
        <View style={[styles.expirationField, styles.margin]}>
          {locals.inputs.card_expire_year}
        </View>
        <View style={[styles.expirationField, styles.margin]}>
          {locals.inputs.card_expire_month}
        </View>
        <View style={styles.expirationField}>
          {locals.inputs.card_cvv2}
        </View>
      </View>
    </View>
  )
}

const styles = React.StyleSheet.create({
  expirationContainer: {
    flexDirection: 'row',
  },
  expirationField: {
    flex: 1,
  },
  margin: {
    paddingRight: 5,
  },
})

module.exports = creditCard
```

And in your options

```js
options: {
        template: creditCard,
}
```

**Comment by alvaromb** [comment]
Please let me know if you need further info @sibeliusseraphini 👍

**Comment by sibeliusseraphini** [comment]
thanks, I will try that

**Comment by Ajith128** [comment]
May I know how I can read the values from a custom template view added to tcomb-form. I have added a slider to show a range of values,
function sliderTemplate(locals) {
    return (
        <View>
            <Slider
                minimumValue={0}
                locals={locals}
                decimal={locals.config.decimal ? locals.config.decimal : 0}
                maximumValue={locals.config.maxVal}
                step={locals.config.step}
            />
        </View>
    );
}

**Comment by pymd** [comment]
@alvaromb Does the creditcard example posted above really work? I tried making it work, but it throws this error "TypeError: undefined is not a function (evaluating '_reactNative2.default.createElement')".
Does the tcomb-form-native library really supports templating at the form level? Or is it only possible on a per field basis? 
Please help. I can't get it to work at the form level.
