### ISSUE TITLE
Setting `{ height: 0 }` to one field makes hidden all fields

### ISSUE THREAD

**Issue by miqmago** [gcanti/tcomb-form-native#154]
### Version

- tcomb-form-native v0.4.2
- react-native v0.25.0-rc

I would like to have a hidden field in the form, as I need it in the state.

```javascript
import t from 'tcomb-form-native';
import update from 'react-addons-update';

// https://facebook.github.io/react/docs/update.html
const stylesheet = update(t.form.Form.stylesheet, {
    textbox: {
        normal: {
            opacity: { $set: 0 },
            height: { $set: 0 }, // <--- Without this parameter, it works and sets opacity to 0 only to AdditionalContactDetails, as expected
        },
    },
});

export const ContactDetailsOptions = {
    auto: 'placeholders',
    label: 'Dades de contacte (Opcional)',
    fields: {
        Telephone: {
            placeholderTextColor: '#FCB',
            placeholder: 'Telèfon',
            keyboardType: 'phone-pad',
        },
        WebAddress: {
            placeholderTextColor: '#FCB',
            placeholder: 'Web',
            keyboardType: 'url',
        },
        ElectronicMail: {
            placeholderTextColor: '#FCB',
            placeholder: 'E-Mail',
            keyboardType: 'email-address',
        },
        AdditionalContactDetails: {
            stylesheet,
            placeholderTextColor: '#FCB',
            placeholder: 'Altres dades de contacte',
        },
    },
};
```

### Expected behaviour

The field `AdditionalContactDetails` should not be shown, while the state has it's default value.

### Actual behaviour

All fields are being hidden.

**Comment by alvaromb** [comment]
Have you tried to debug the `textbox.js` template? What stylesheet do you get there for all your text fields? The code (https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L60) is pretty straightforward, just sends the stylesheet present in the template, so I think your issue might be other thing.

**Comment by miqmago** [comment]
Ouch! Thanks, I don't know what was happening, suddenly it worked...

**Comment by miqmago** [comment]
Well, in fact what I've discovered is that setting `{ height: { $set: 1 } }` works, setting it to 0 doesn't... Very strange.

**Comment by alvaromb** [comment]
Something is happening somewhere else, I doubt it comes from `tcomb-form-library`. I would like to see how you define your form's stylesheet.

**Comment by miqmago** [comment]
I'm working on a `hidden` option, I will make pull request if it feels good to you :smile:

**Comment by alvaromb** [comment]
Sure. Please ping me if you need help debugging your form rendering.

**Comment by miqmago** [comment]
Just a question: my first approach is to add 
```javascript
  if (locals.hidden) {
    return null;
  }
```

at the beginning of each template (and add the option `hidden` to each `getLocals()`).

Quite simple, I'm not really suer if this will populate the value to the state.
