### ISSUE TITLE
Dispatch in redux is wiping form fields

### ISSUE THREAD

**Issue by ssomnoremac** [gcanti/tcomb-form-native#156]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.23.1

### Expected behaviour

Form values should remain where they are

### Actual behaviour

a global setInterval dispatch is calling a completely unrelated action that is wiping fields of the form. 

### Steps to reproduce

1. using redux in an app dispatch an action while filling out a form

**Comment by alvaromb** [comment]
Hello @ssomnoremac!

Redux must be updating your component and the form losing its state. Try to save it using the `onChange` method to `setState` the form input.

**Comment by ssomnoremac** [comment]
Solid. That did it. Thanks for getting back so quickly!

**Comment by alvaromb** [comment]
👍 cool @ssomnoremac!

Glad to have helped!
