### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by miqmago** [gcanti/tcomb-form-native#157]
I've developed a list component https://github.com/miqmago/tcomb-form-native/commit/b70e9e4d618dd2cbaed37b49c102431641fb3e6a (it's still work in progress but right now it's working on Android, supposedly on iOS too) with the following features:

- Creates the corresponding subcomponent for each of the values of the list
- Adds a button to add new items which can be placed at the beginning or at the end, before help and errors
- For each list item adds a button to remove it which can be placed at bottom or at top of the item
- When a new item is added, implements the following callbacks:
  - onBefore(nativeEvent) --> return true, the new item or a promise with new item
  - onAfter(nativeEvent)
- When an item is removed, implements the following callbacks:
  - onBefore(nativeEvent, listIndex) --> return true, the new item or a promise with new item
  - onAfter(nativeEvent)

Can be called with this options:

```js
const Persons = t.list(
    t.struct({
        name: t.String,
        surname: t.maybe(t.String),
        age: t.Number,
        rememberMe: t.Boolean
    })
});
const options = {
    addItem: {
        label: <Text style={{ alignSelf: 'center', color: 'white' }}>Add person</Text>,
        stylesheet: {
            button: {
                normal: {
                    backgroundColor: '#FCB'
                }
            }
        },
        onBefore: function onBeforeAddItem(e) {
            return new Promise(resolve => resolve({
                name: 'Default name'
            }));
        },
        onAfter: function onAfterAddItem() {
            console.log('New person was added');
        },
        position: 'top', // 'top' (default), 'bottom'
        // All TouchableHighlight options, i.e:
        disabled: true
    },
    removeItem: {
        // label: 'Remove person', // Defaults to humanize('removeItem'): "Remove item"
        onBefore: function onBeforeRemoveItem(e, idx) {
            return new Promise((resolve, reject) => {
                Alert.alert(
                    'Delete person',
                    'Are you sure?',
                    [
                        { text: 'Ask later', onPress: () => reject('Canceled') },
                        { text: 'No', onPress: () => reject('Canceled'), style: 'cancel' },
                        { text: 'Yes', onPress: resolve },
                    ]
                );
            });
        },
        position: 'bottom', // 'top', 'bottom' (default)
        // All TouchableHighlight options
    },
    stylesheet: {
        addItem: {
                button: { normal: {}, disabled: {} },
                label: { normal: {}, disabled: {}  },
        },
        removeItem { // same },
        listGroup: { normal: {}, error: {} },
        listItem: { normal: {}, error: {} }
    },
    fields: {
        name: { ... },
        surname: { ... },
        ....
    },
};
```

It's not complete:
- Missing mockery tests
- Missing testing in iOS
- Missing validation testing (not clear how should be implemented)

I will need help to develop those features.
I've implemented the component in a separate file, just for development cleareness.
(Maybe would be a good idea to separate every component in his own separate file, they would be happier :smile: )

**Comment by gcanti** [comment]
Hi @miqmago,

I'm sorry, somehow I completely missed this issue. There is a pending PR on list support if you want to chime in https://github.com/gcanti/tcomb-form-native/pull/173
