### ISSUE TITLE
Hidden field with default value?

### ISSUE THREAD

**Issue by austinksmith** [gcanti/tcomb-form-native#161]
Perhaps this is something that's just gone over my head but how does one simply hide a field while keeping it present and with a default value? I've figured out how to set a default value but there doesn't seem to be anyway to hide the field in the struct. You also can't simply say struct.my_field = '1234'; on submit like I would hope to eliminate the need for a hidden field at all. Any guidance would be much appreciated thanks.

**Comment by gcanti** [comment]
There's an `hidden` option https://github.com/gcanti/tcomb-form-native#hidden-component

**Comment by austinksmith** [comment]
It doesn't appear to work, 

```t.struct({
  eventId: t.String
});```

```var options = {
	auto: 'placeholders',
	fields: {
    eventId: {
    	hidden: true
    }
  }
};```

My field eventId still appears in the form

**Comment by gcanti** [comment]
The `hidden` option is contained in v0.4.4 (https://github.com/gcanti/tcomb-form-native/releases/tag/v0.4.4). Which version are you using?

**Comment by wellyal** [comment]
Have you found the solution for this. I have a similar problem (the hidden field is still showing). I have 0.6.9 version. 

``` javascript
const type = t.struct({
  country: t.String,
});
...
country: {
  nullOption: 'Selecione um país',
  label: 'País',
  hidden: true
},
```

**Comment by arnoldbird** [comment]
I'm also wondering how to set a default value for a hidden field, or for any text field.

**Comment by arnoldbird** [comment]
In case someone else happens by this way, the value property in state can be used to set a default value:

```
state = {
    value: {
      my_field: 'something'
    }
}
```
