### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by shtefanntz** [gcanti/tcomb-form-native#163]
### Version
- tcomb-form-native v0.4.4
- react-native v0.26.0

### Expected behaviour

To work :D

### Actual behaviour

![screen](https://cloud.githubusercontent.com/assets/3305076/15439252/ba8b1228-1ed8-11e6-9769-2cd688793fa0.png)

I just upgraded to RN 0.26, which made update all other dependancies. But I couldn't figure what's the problem with this library, because the code seems 'ok' (I'm talking about the code in components.js). 

Thanks,
Stefan

**Comment by rogerroelofs** [comment]
it is not yet compatible with RN 0.26.  The implicit dependency on react was removed and the lib has to be updated to take that into account.

**Comment by rogerroelofs** [comment]
It appears to be fixed on the master branch.  You can use the master branch directly by setting you package.json to
    "tcomb-form-native": "gcanti/tcomb-form-native"

I'd suggest waiting until the next release to upgrade RN or making sure you revert your package.json back as soon as the next release comes out.  Working with unreleased code long term is probably not a good idea.

**Comment by gcanti** [comment]
> You can use the master branch

Another option is installing a particular commit (the current last commit on master should be safe):

```sh
npm install gcanti/tcomb-form-native#13e2c68c8832208626253011916a2542fc426168
```

so you don't depend on (possibly breaking) future commits on master

**Comment by alvaromb** [comment]
The RN release cycle is insane. It's hard to keep updated when your app is broken every two weeks. I really love the technology and thank Facebook for it but man, I hope we get to 1.0 soon. 

Enviado desde mi iPhone

**Comment by gcanti** [comment]
@alvaromb going to release a `0.5.0-rc.0`, ok?

**Comment by alvaromb** [comment]
Ok!

Thumbs up. 

Enviado desde mi iPhone

**Comment by gcanti** [comment]
Closing as per https://github.com/gcanti/tcomb-form-native/releases/tag/v0.5.0

**Comment by grantd77** [comment]
hello,

I am using a much more recent version of react-native, 0.55.4, and I am getting the error above for the iOS project I am working on.

Is there anything specific I should be doing to make sure I do not get this error?
Cheers.

**Comment by grantd77** [comment]
Hello out there, I was getting this issue still, but it was because I was getting the older 0.4.4 version, force npm install to fetch the 0.5 version and you should be ok.
