### ISSUE TITLE
[Question] Show date fields as label unless focused on

### ISSUE THREAD

**Issue by amirfl** [gcanti/tcomb-form-native#164]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.4
- react-native v0.26.0

### Expected behaviour

trying to get date field shown as a label until selected. When it gets focus on it should show a date picker.

### Actual behaviour
Date picker is shown no matter if in focus or not.

Is there a way to have a date field appear as text until the user focuses on it and replaces it with a date picker?

**Comment by gcanti** [comment]
Relevant https://github.com/gcanti/tcomb-form-native/issues/61

**Comment by amirfl** [comment]
Implementing the solution from [#61](https://github.com/gcanti/tcomb-form-native/issues/61) gives an error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Component`.`

**Comment by amirfl** [comment]
Implementing the solution from [#61](https://github.com/gcanti/tcomb-form-native/issues/61) gives an error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Component`.`

**Comment by amirfl** [comment]
Implementing the solution from [#61](https://github.com/gcanti/tcomb-form-native/issues/61) gives an error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Component`.`

**Comment by alvaromb** [comment]
You have to create a custom template to do that. Here https://github.com/gcanti/tcomb-form-native/issues/61#issuecomment-157332926 you have an example with a `Picker` instead of a `DatePicker`. Please use it as a reference and ping me if you need further info.

**Comment by amirfl** [comment]
Implementing the solution from [#61](https://github.com/gcanti/tcomb-form-native/issues/61) gives an error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Component`.`
