### ISSUE TITLE
Warning with IOSDatePIcker

### ISSUE THREAD

**Issue by amirfl** [gcanti/tcomb-form-native#165]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.4
- react-native v0.26.0

### Steps to reproduce
Insert t.date object into the model.
```
var Person = t.struct({
  name: t.String,            
  startDate:t.Date,
});
```
```
var options = {
  fields: {
    name: {label:"First Name", placeholder:"Joe"},
    startDate: {mode:"date", label:"Start Date", },
  },
}; 
```
inside the component:
```
getInitialState:function(){
    return {
      value:{
        startDate: (new Date()),
      },
```
### Stack trace and console log
The date picker correctly shows the date set in this.state.value, but a warning is shown:
`Warning: Failed propType: Invalid prop `date` of type `Number` supplied to `RCTDatePicker`, expected instance of `Date`. Check the render method of `DatePickerIOS``

**Comment by alvaromb** [comment]
Hello @amirfl!

This is an upstream issue, here you have more info https://github.com/facebook/react-native/pull/7472.

**Comment by gcanti** [comment]
FYI here's a temporary fix https://github.com/gcanti/tcomb-form-native/pull/175#issuecomment-223616240
