### ISSUE TITLE
Text Input Auto Completion

### ISSUE THREAD

**Issue by Team-23** [gcanti/tcomb-form-native#166]
### Version

Tell us which versions you are using:
- tcomb-form-native v0.4.0
- react-native v0.24.1
### Expected behaviour

When an auto-complete email (in this case) is entered by user, the refinement function should evaluate the auto-completed value.
### Actual behaviour

The value prior to the auto-completion is evaluated not the full string of characters.
### Steps to reproduce
1. Create a refinement property with a function that checks for a valid email.
2. Start typing an email address and let auto-complete populate
3. Validation fails.

Please note: If auto completion is not used, the validation works as expected.

Example Code:
var EmailField = t.refinement(t.String, function (email) {
  return EMAIL_REGEX.test(email);
});

**Comment by gcanti** [comment]
@Team-23 is this an upstream issue of it happens because of `tcomb-form-native`? Perhaps the auto-completion doesn't trigger the `onChange` events in RN.

**Comment by alvaromb** [comment]
@Team-23 can you post your full auto completion source?

**Comment by Team-23** [comment]
Please find below the relevant parts. Thank you for your time.

`const EMAIL_REGEX = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

var EmailField = t.refinement(t.String, function (email) {
  return EMAIL_REGEX.test(email);
});

// here we are: define your domain model
var Business = t.struct({
  businessName: t.String,
  contactName: t.String,
  email: EmailField,
  phone: t.maybe(t.String),
  quoteDescription: t.maybe(t.String)
});
t.form.Form.stylesheet = formStyles;

            <Form
              ref="form"
              type={Business}
              value={this.state.value}
              onChange={this.onChange}
              options={options}
              style={[inlineStyles.form]}
            />

  onChange(value) {
    this.setState({ value: value });
  },
`

**Comment by alvaromb** [comment]
How are you setting the autocompletion?

**Comment by gcanti** [comment]
@Team-23 Could you please verify that enabling the autocompletion with a controlled `TextInput` its `onChangeText` handler triggers? In `tcomb-form-native` we are using `onChangeText` to track changes but if it doesn't trigger it's an upstream issue and there's nothing we can do.

Relevant? https://github.com/facebook/react-native/issues/7496

**Comment by Team-23** [comment]
@alvaromb @gcanti I should have written this correctly. Yes it is the auto-correct (and auto-colpetion of suggested words) of the TextInput that is causing the issue. facebook/react-native#7496 seems to be relevant to this.

**Comment by alvaromb** [comment]
This has been fixed!
