### ISSUE TITLE
Add onChange handler to TextInput

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form-native#168]

**Comment by weixingsun** [comment]
Please let me know if you got this fix ready, I can test it on my phone and simulator

**Comment by gcanti** [comment]
Thanks @weixingsun, there's a branch for this, you can just run `npm install gcanti/tcomb-form-native#168` and try it out

**Comment by weixingsun** [comment]
@gcanti, I cannot see any alert in onChangeNative, could you pls double check the method calling tree? or let me know if I need change my code ?
                   onChangeNative(event){
                      alert(JSON.stringify(event.nativeEvent))
                   }
                  render(){
                    <Form
                        ref="form"
                        type={t.struct(this.state.type)}
                        value={this.state.value}
                        options={this.state.options}
                        onChange={this.onChange.bind(this)}
                        onChangeNative={this.onChangeNative.bind(this)}
                    />
                 }

**Comment by gcanti** [comment]
@weixingsun sorry, I forgot to explain the usage. This is a simple example:

```js
import t from 'tcomb-form-native';

const Form = t.form.Form;

const Type = t.struct({
  name: t.String
})

const options = {
  fields: {
    name: {
      onChange: (event) => console.log(event) // <= the new feature
    }
  }
}

class AwesomeProject extends Component {

  onPress() {
    const value = this.refs.form.getValue();
    if (value) {
      console.log(value)
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <t.form.Form
          ref="form"
          type={Type}
          options={options}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress.bind(this)} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

**Comment by gcanti** [comment]
@weixingsun and this is an example implementing a simple AutoExpandingTextInput:

```js
import t from 'tcomb-form-native'

const Form = t.form.Form

const Type = t.struct({
  name: t.String
})

class AwesomeProject extends Component {

  constructor(props) {
    super(props)
    this.state = { height: 40 }
  }

  onPress() {
    const value = this.refs.form.getValue()
    if (value) {
      console.log(value)
    }
  }

  onChange(value) {
    this.setState({ value })
  }

  render() {

    const options = {
      fields: {
        name: {
          stylesheet: Object.assign({}, Form.stylesheet, {
            textbox: {
              normal: {
                height: this.state.height
              },
              error: {
                height: this.state.height
              }
            }
          }),
          multiline: true,
          onChange: (event) => {
            this.setState({
              height: event.nativeEvent.contentSize.height
            });
          }
        }
      }
    }

    return (
      <View style={styles.container}>
        <t.form.Form
          ref="form"
          type={Type}
          options={options}
          value={this.state.value}
          onChange={this.onChange.bind(this)}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress.bind(this)} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.5.1

**Comment by daveteu** [comment]
@gcanti 

citing your example above, even though I copy codes word for word, onChange of field returns error
undefined is not an object(evaluating 'event.nativeEvent.contentSize.height')

![screen shot 2018-05-10 at 8 24 06 pm](https://user-images.githubusercontent.com/18649392/39869495-4ed4bfe4-5490-11e8-901a-9c809f6fa5e3.png)

First time install today, using **0.6.11**
