### ISSUE TITLE
this.refs.form.getComponent is no longer working?

### ISSUE THREAD

**Issue by aaronksaunders** [gcanti/tcomb-form-native#17]
testing with latest release and sample app and getting red screen
```
this.refs.form.getComponent is not a function
```
is there a new way to get the underlying component, I have retest and rebuilt the latest... what is the latest version of react-native that this component has been tested with?

When I look in the debugger, I dont see the method...

![screenshot 2015-05-05 21 37 48](https://cloud.githubusercontent.com/assets/524953/7486174/256215ce-f36f-11e4-8dca-be098eea7fe9.png)

**Comment by gcanti** [comment]
In tcomb-form-native the API `getComponent` doesn't exist yet, but it should be fairly easy to add:

```js
getComponent(path) {
  path = t.Str.is(path) ? path.split('.') : path;
  return path.reduce((input, name) => input.refs[name], this.refs.input);
}
```

**Comment by aaronksaunders** [comment]
@gcanti I will give it a try and add it to the module, I could have sworn it was working a few days ago though?
