### ISSUE TITLE
Number keypad should show for numeric fields..

### ISSUE THREAD

**Issue by jsphkhan** [gcanti/tcomb-form-native#171]
### Version
- tcomb-form-native v0.5.1
- react-native v0.24.1

### Expected behaviour
When clicking/tapping on numeric fields (eg. Age), the number keypad should show up.

### Actual behaviour
It shows up the alphabet keypad. Screen below,

<img width="150" alt="screen shot 2016-05-29 at 12 59 43 am" src="https://cloud.githubusercontent.com/assets/1991609/15629541/e8ae4c5e-2538-11e6-9967-fe7823e00beb.png">

**Comment by gcanti** [comment]
You can set the `keyboardType` option (https://facebook.github.io/react-native/docs/textinput.html#keyboardtype).

Do you mean that `tcomb-form-native` should apply `keyboardType: numeric` as a default if detects that there's no `keyboardType` option defined by the developer and the type is numeric?

**Comment by appbeijing** [comment]
keyboardType should disappear

**Comment by gcanti** [comment]
@appbeijing the `keyboardType` option can't simply "disappear", as a developer you may want to set one of following legal values:

```
'default', 'email-address', 'numeric', 'phone-pad', 'ascii-capable', 'numbers-and-punctuation', 'url', 'number-pad', 'name-phone-pad', 'decimal-pad', 'twitter', 'web-search'
```

**Comment by alvaromb** [comment]
`keyboardType` shouldn't disappear. We could set the `numeric` value as default if it represents a `t.Number` value. I'll add this into my list.

**Comment by thibault12** [comment]
How can you implement the 'done' or 'return' button in the numeric keypad to enable the users to close the keypad?

**Comment by ltankey** [comment]
> How can you implement the 'done' or 'return' button in the numeric keypad to enable the users to close the keypad?

`returnKeyType = 'done'`

**Comment by AarshOza** [comment]
> > How can you implement the 'done' or 'return' button in the numeric keypad to enable the users to close the keypad?
> 
> `returnKeyType = 'done'`

Thank you it saved my day

**Comment by shashwatvarshney** [comment]
how to set keyboard in react native to show only numbers, no extra punctuation marks or special characters should be there like . , etc.
i tried keyboardType={"numeric"}

![upload on net](https://user-images.githubusercontent.com/44412994/79718304-569fc400-82f9-11ea-9045-5e7027093cf8.png)

i need to have only numbers in above image it contains punctuation also how to remove that
