### ISSUE TITLE
Cannot find module './datepicker' when testing

### ISSUE THREAD

**Issue by bennythomps** [gcanti/tcomb-form-native#174]
### Version

- tcomb-form-native v0.5
- react-native v0.26.1

### Expected behaviour

I should be able to run my tests without import issues.

### Actual behaviour

When I run my tests, I receive the error `Cannot find module './datepicker'` when transpiling

### Steps to reproduce

1. Author a test that involves a tcomb form
2. Run test via Mocha using Babel compiler

### Stack trace and console log

`Cannot find module './datepicker'`

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form-native/issues/134#issuecomment-216618765

**Comment by bennythomps** [comment]
Thank you @gcanti
