### ISSUE TITLE
Persist focus in form when switching between it's fields

### ISSUE THREAD

**Issue by sharq1** [gcanti/tcomb-form-native#177]
### Version

- tcomb-form-native v0.5.1
- react-native v0.26.1

### Expected behaviour

When I tap on another field in a form I want the focus to switch from current field to the tapped one

### Actual behaviour

Current field loses input. Have to tap second time on that another input

I'm allowing to switch between the fields with the return key (code below), but that's not enough. People expect to switch to field they tap on.
```
returnKeyType: 'next',
onSubmitEditing: () => this.refs.form.getComponent('passwordAgain').refs.input.focus(),
```

**Comment by gcanti** [comment]
@sharq1 @alvaromb is this a `tcomb-form-native` issue or an upstream issue of RN?

**Comment by alvaromb** [comment]
The `Done` button isn't handled automatically. Use `onSubmitEditing` from `TextInput` to handle the press @sharq1.

**Comment by sharq1** [comment]
@alvaromb I'm not talking about the keyboard `done` or `next` button, which I handle just fine. I'm talking about the behavior when tapping directly on another text input.

**Comment by alvaromb** [comment]
Sorry @sharq1, this is due to the container `ScrollView` and it's the expected behaviour. Set `keyboardShouldPersistTaps` (please double check the prop name, I'm writing it from memory) to `false`.

**Comment by sharq1** [comment]
Thank you @alvaromb!
I tried setting `keyboardShouldPersistTaps` before by adding new `ScrollView` but since it didn't work I assumed it's `tcomb`'s issue, but I failed to notice that there was another `ScrollView` above. 

`keyboardShouldPersistTaps` works when set to `true`

**Comment by ansmonjol** [comment]
Hi, I tried `keyboardShouldPersistTaps` but it's not working for me.

I have the focus animation when clicking to an other input field (mean for exemple on android the underline border change color and I see the cursor inside the input I just clicked), but immediately after that, the input lost his focus and the keyboard close.

Any idea ? 

I'm using react-native v0.35.0 and tcomb v0.6.1

**Comment by jcrjaci** [comment]
@sharq1 @alvaromb but with that solutions, the keyboard appears always visible, even if the click is outside the form field.
Any workaround?

**Comment by cbilgili** [comment]
@sharq1 @ansmonjol I had same problem. But for me tcomb form was inside of <KeyboardAwareScrollView>. When it is removed behaves as expected.
