### ISSUE TITLE
problem with i18n

### ISSUE THREAD

**Issue by appbeijing** [gcanti/tcomb-form-native#178]
t.form.Form.i18n = {
  optional: '',
  required: ' (required)'
};

it is not work when you use label

**Comment by gcanti** [comment]
It's by design, `optional` and `required` are supposed to be applied only when you don't override labels (`label` option)

**Comment by appbeijing** [comment]
你让不用英语的人怎么玩，莫非要我泱泱大中华的表单全都显示英文吗？
Have you considered the problem of internationalization ?

**Comment by gcanti** [comment]
Which problem?

**Comment by appbeijing** [comment]
when I mask a form ,I need to tell user which is required,  if I take English as a label text, our user will be puzzled, in china  people who can understand English is small, but everyone can read chinese.

**Comment by gcanti** [comment]
You can set your own labels right? Choose the language you want

**Comment by appbeijing** [comment]
like this ?
var Person = t.struct({
	姓名: t.String,
	曾用名: t.maybe(t.String),
	年纪: t.String,
	国籍:t.String,
	爱好:t.String,
	生日:t.Date,
        记住密码: t.Boolean,
});

if it was ok, I think you can remove label.

**Comment by gcanti** [comment]
I mean the labels in the options :)

**Comment by appbeijing** [comment]
hi,  how can I set a red color to  text of i18n ? @gcanti 
t.form.Form.i18n = {
optional: '',
required: ' <Text style={styles.red}>(required)</Text>'
};

**Comment by appbeijing** [comment]
hi, how can I set a color to the text of i18n ? @gcanti 
`t.form.Form.i18n = {
optional: '',
required: '<Text style={styles.red}>*</Text>'
};
`
It dosen't work.

**Comment by alvaromb** [comment]
The `I18n` option is attached to the label, so I think you would need to drop a custom factory to do that and modify how this line behaves https://github.com/gcanti/tcomb-form-native/blob/master/lib/components.js#L137

**Comment by gcanti** [comment]
This is what I would do with `tcomb-form` (replace `span`s with `Text` I guess)

```js
class MyFactory extends t.form.Textbox {

  getDefaultLabel() {
    const ctx = this.props.ctx
    if (ctx.label) {
      return (
        <span>
          <span>{ctx.label}</span>
          <span style={{color: 'red'}}> {(this.typeInfo.isMaybe ? this.getI18n().optional : this.getI18n().required)}</span>
        </span>
      )
    }
  }

}

const Type = t.struct({
  name: t.String
})

const options = {
  fields: {
    name: {
      factory: MyFactory
    }
  }
}
```

**Comment by appbeijing** [comment]
@alvaromb thank you，I modify the code #L137 and textbox.js , I think if getLabel() return  json  not  string ,it will be better to work。
