### ISSUE TITLE
Double tapping on textinput.

### ISSUE THREAD

**Issue by susylPearl** [gcanti/tcomb-form-native#181]
i should double tap to input text after first input finished, this means when i write text in first textfield then again for writing in second textfield i should do double tap first tap will dissapear keyboard and second tap will  provide us for inputting text. Cannot we do keyboard always appear untill all textfield have been filled up, or unless we should tap done button on keyboard. Sorry for my inconvinent english. Any suggestion would be appriciated.

**Comment by appbeijing** [comment]
+1

**Comment by alvaromb** [comment]
Please, look at this issue: https://github.com/gcanti/tcomb-form-native/issues/177#issuecomment-226101903
