### ISSUE TITLE
[Android] Password field's last typed char disappears too quickly

### ISSUE THREAD

**Issue by imalbert** [gcanti/tcomb-form-native#182]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.0
- react-native v0.24.0

### Expected behaviour

Typing in a TextInput with option `{ password: true, secureTextEntry: true }` should consistently show the last typed character until the next character input.

### Actual behaviour

After the first typed character, the last typed character is shown but disappears almost instantly.

Only seen in Android. iOS is OK

**Comment by gcanti** [comment]
Hi @imalbert, 

Have you already tried with vanilla react-native (perhaps it's an upstream issue)?

**Comment by imalbert** [comment]
Hey! I tried using the `TextInput` and it works as expected in the same project

**Comment by imalbert** [comment]
Hello again, I'm still having this problem. I have a repro [here](https://github.com/imalbert/rntest-01) which i should have done earlier.

the versions in this repo:
```
tcomb-form-native@0.4.4
react-native@0.24.0
react@0.14.8
```

I also tested earlier with these versions with similar results
```
tcomb-form-native@0.5.1
react-native@0.28.0
react@15.1.0
```

It would be really weird if only I have this problem. Please help!

**Comment by alvaromb** [comment]
I think this is due to the controlled component nature of the `TextInput`. Can you show us an image of the actual issue?

**Comment by imalbert** [comment]
Here's what happens
![rntest-01](https://cloud.githubusercontent.com/assets/12537973/16378479/b707d968-3c9e-11e6-98f7-eaefccedbc5a.gif)

**Comment by alvaromb** [comment]
Yeah, probably this is because it is a controlled component. @gcanti probably this also affects iOS too, I have some weird `TextInput` effects with passwords.

I'll try to jump into this.

**Comment by imalbert** [comment]
Thank you very much :smile:

**Comment by gcanti** [comment]
@imalbert @alvaromb making the vanilla TextInput a controlled component shows the same behavior of the tcomb TextInput. Also https://github.com/facebook/react-native/issues?utf8=✓&q=secureTextEntry. Going to tag this as an upstream issue.
