### ISSUE TITLE
Form doesn't Scrolldown

### ISSUE THREAD

**Issue by jaimecorrea** [gcanti/tcomb-form-native#183]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.4.4
- react-native v0.24.1

### Expected behaviour

I have a form of more than 7 fields but I'm not able to scrolldown to see them all...

### Actual behaviour

I can't scroll down inside the form (it's inside a ScrollView):

```
<View style={styles.container}>
        <ScrollView style={styles.scrollContainer}>
          <Form
            ref="form"
            type={this.state.type}
            value={this.state.value}
            onChange={this.onChange}
            options={options}
          />
          <TouchableHighlight style={styles.button} onPress={this.onPress.bind(this)} underlayColor='#99d9f4'>
            <Text style={styles.buttonText}>Guardar</Text>
          </TouchableHighlight>
        </ScrollView>
      </View>
```

### Steps to reproduce

1. Run a form with more than 4 fields

### Stack trace and console log

There is no error in log...

**Comment by sankalp0o** [comment]
@jaimecorrea were you able to resolve this? I'm facing the same problem.

**Comment by alvaromb** [comment]
You have to manually handle the keyboard... or use our component to do that!

https://github.com/APSL/react-native-keyboard-aware-scroll-view

😉
