### ISSUE TITLE
Placeholder color is not changing

### ISSUE THREAD

**Issue by sudharsan1988** [gcanti/tcomb-form-native#185]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.5.1
- react-native v0.27.2?

I'm testing on a Android device.

### Expected behaviour

I would like to have the placeholders color to be white

### Actual behaviour

I tried to overwrite the style with

stylesheet.controlLabel.normal.color = '#FFFFFF';
stylesheet.controlLabel.error.color = '#FFFFFF';

But it's not reflecting. But I am able to add Text Color when the user enter input.

Here is my Type,

const CreditCard = t.struct({
  number: t.Number,              
  exp_month: t.Number,  
  exp_year: t.Number, 
  cvc: t.Number        
});

Even though I am using "Number", keyboard doesn't change at all.

Thank you for your help.

**Comment by sudharsan1988** [comment]
I fixed it by adding "placeholderTextColor" in the options.

var options = { 
  auto: 'none',
  
  fields: {
    number: {
      placeholder: 'Card numbers',
      placeholderTextColor:'#FFFFFF',
      stylesheet: stylesheet, // overriding the style of the textbox
    },
    exp_month: {
      placeholder: 'MM',
      placeholderTextColor:'#FFFFFF',
      stylesheet: stylesheet, // overriding the style of the textbox
    },
     exp_year: {
      placeholder: 'YYYY',
      placeholderTextColor:'#FFFFFF',
      stylesheet: stylesheet, // overriding the style of the textbox
    },
     cvc: {
      placeholder: 'CVC',
      placeholderTextColor:'#FFFFFF',
      stylesheet: stylesheet, // overriding the style of the textbox
    }

  }
};

**Comment by bsiddiqui** [comment]
Is it possible to do this globally?

**Comment by alvaromb** [comment]
Sorry, this is a `TextInput` prop, so it doesn't come from the global stylesheet http://facebook.github.io/react-native/releases/next/docs/textinput.html#placeholdertextcolor.
