### ISSUE TITLE
Android datepicker always open the current date

### ISSUE THREAD

**Issue by karir-workstation** [gcanti/tcomb-form-native#187]
### Version
- tcomb-form-native v0.5.1
- react-native v0.28.0

### Expected behaviour

When edit data, android date picker must show the date based on the date of the data

### Actual behaviour

Android date picker always show the current date, like this code below :
```    
    DatePickerAndroid.open({date: new Date()})
      .then(function (date) {
        if (date.action !== DatePickerAndroid.dismissedAction) {
          var newDate = new Date(date.year, date.month, date.day);
            locals.onChange(newDate);
        }
    });
```

Why android date picker not show the value based on the data, like this code below ?
```
   DatePickerAndroid.open({date: new Date(locals.value)})
      .then(function (date) {
        if (date.action !== DatePickerAndroid.dismissedAction) {
          var newDate = new Date(date.year, date.month, date.day);
            locals.onChange(newDate);
        }
    });
```

**Comment by alvaromb** [comment]
Hi @karir-workstation!

Would you like to send a PR? ☺️

**Comment by karir-workstation** [comment]
I don't know how to write the test for this bug. So it's fix only. I hope it's enough.

**Comment by appbeijing** [comment]
hi @alvaromb 
 you don't set time , so it always show current time.
the code:
 `TimePickerAndroid.open({is24Hour: true})`
I think it should be TimePickerAndroid.open({is24Hour: true, date:new Date(you select time || current time)})

I want to konw how to set year month day hour minute second together in android environment.

**Comment by appbeijing** [comment]
by the way, what's  "PR"? My English is not good

**Comment by gcanti** [comment]
@appbeijing **P**ull **R**equest

**Comment by francescjimenez** [comment]
In datepicker it's solved, but it isn't on timePickerAndroid
