### ISSUE TITLE
how can I set Date format

### ISSUE THREAD

**Issue by appbeijing** [gcanti/tcomb-form-native#189]
I have already read source

 `if (locals.config.format) {
      formattedValue = locals.config.format(locals.value);
    }`

 but my function need pass two arguments, 
for example：formatDate("yyyy-mm-d h:f:s","Tue Jul 5 2016 10:04:52 GMT+0800 (中国标准时间)"),
because my form is dynamically generated, every date format is different。
how can I do it?

**Comment by gcanti** [comment]
Currying?

```js
const myFormatFunction = format => date => formatDate(format, date)
const myFormat1 = 'yyyy-mm-d h:f:s'
const myFormat2 = 'yyyy-mm-d'
// etc...

...

const formOptions = {
  fields: {
    myDate: {
      config: {
        format: myFormatFunction(myFormat1)
      }
    }
  }
}
```

**Comment by dianacgp1280** [comment]
import moment from 'moment';
const myFormatFunction = format => date => moment().format('YYYY-MM-DD')
const formOptions = {
  fields: {
    myDate: {
      config: {
        format:myFormatFunction()
      }
    }
  }
}

**Comment by jariwalabhavesh** [comment]
@gcanti Is there any example, because it is not formatting date in my case.
```
var effectiveDate = {
            label: 'Effective Date',
            mode:'date',
            config:{
                format:()=>{
                    // i am not getting callback here for formatting date
                }
            },
        };  
```
```
let options = {
            fields: {
               "effectiveDate":effectiveDate
            }
        };
```

**Comment by alvaromb** [comment]
How are you setting the options in your `Form`, @jariwalabhavesh ?

**Comment by jariwalabhavesh** [comment]
@alvaromb 
```
 var Person = t.struct({
            effectiveDate: t.Date // a date field
        });
```
`<Form ref="documentDate" type={Person} value={this.state.dateValue} options={options} />`

**Comment by alvaromb** [comment]
Mmm, it seems ok. Can you post your full source code?

**Comment by jariwalabhavesh** [comment]
@alvaromb 
Thanks for reply, after you reply i again tested code and it start working, i didn't know what was actual reason. But now it is working and **HERE IS WORKING EXAMPLE**

```
class DateComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {
        }
    }

    render() {
        var Person = t.struct({
            effectiveDate: t.Date // a date field
        });
        let myFormatFunction = (format,date) =>{
            return moment(date).format(format);
        }
        var effectiveDate = {
            label: 'Effective Date',
            mode:'date',
            config:{
                format:(date) => myFormatFunction("DD MMM YYYY",date)
            }
        };
        let options = {
            fields: {
               "effectiveDate":effectiveDate
            }
        };
        return (
            <View style={styles.container}>
                <View>
                    <Form ref="documentDate" type={Person} value={this.state.dateValue} options={options} />
                </View>
            </View>
        );
    }
}
```

Thanks very much @alvaromb

**Comment by Mogust** [comment]
@jariwalabhavesh hello, i try yout code but getting error said "typeerror: cannot call a class as a function"

**Comment by jariwalabhavesh** [comment]
@Mogust 
I think it was working, May be issue with in your code. Component is not returning render component
