### ISSUE TITLE
Question: How to find a component from Form or Struct?

### ISSUE THREAD

**Issue by bigparksh** [gcanti/tcomb-form-native#19]
Hi, I'm so sorry about my english.
I use tcomb-form-native and think that it's a good library.
Sometime, I want to find a component from Form or Struct.
What is the easiest solution?

This is my stupid solution.
```
class Struct extends Component {
 ... 
  findComponentByName(name) {
    return this.refs[name];
  }
}

class Form {
  ...
  findComponentByName(name) {
    return this.refs.input.findComponentByName(name);
  }
}
```

**Comment by gcanti** [comment]
Hi, 
in tcomb-form there's the following API:

https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L707

I'll add it to tcomb-form-native asap.

**Comment by bigparksh** [comment]
Hi,
Thank you for your help.
