### ISSUE TITLE
secureTextInput broken

### ISSUE THREAD

**Issue by CarbonC** [gcanti/tcomb-form-native#190]
### Version

Tell us which versions you are using:
IOS
- tcomb-form-native v0.5.1
- react-native v0.27.2

### Expected behaviour

Bullets appear on option secureTextInput: true and last letter staying one second

### Actual behaviour

The bullet points to hide text appear smaller than default ones, and so there is a flickering when a new letter is written from all the line which shows one second big points and then little ones. Moreover, the new letter is only displayed few milliseconds.

### Steps to reproduce

1.
2.
3.

```
```

**Comment by gcanti** [comment]
Relevant https://github.com/gcanti/tcomb-form-native/issues/182
