### ISSUE TITLE
Formatting the form

### ISSUE THREAD

**Issue by michael-ar** [gcanti/tcomb-form-native#194]
### Version

- tcomb-form-native v0.5.1
- react-native v0.28.0

Was wondering if it is possible to create components other than the input fields generated by the form. For example, to create the form in the screenshot below, I would need to have a container wrappered around the DOB and email fields, which was set to `flexDirection: 'row'`

Any ideas on how to go about this would be much appreciated.

<img width="372" alt="screen shot 2016-07-11 at 10 52 01" src="https://cloud.githubusercontent.com/assets/18557997/16726964/ab35d5a0-4756-11e6-9e8c-bbb89b11b82c.png">

**Comment by gcanti** [comment]
Relevant https://github.com/gcanti/tcomb-form-native/issues/151

**Comment by michael-ar** [comment]
@gcanti exactly what I need, thank you for getting back so quickly 👍
