### ISSUE TITLE
Not working on new version of react-native?

### ISSUE THREAD

**Issue by chuckyouliu** [gcanti/tcomb-form-native#195]
Just started experimenting with react-native, these are the versions I'm using:
"react": "15.2.1",
"react-native": "0.29.0"

Right now I have tcomb-form-native version set to the github branch because I thought maybe the npm release wasn't compatible with the up to date versions, but I get the same following error:

"undefined is not an object (evaluating 'this._reactInternalInstance._nativeContainerInfo._idCounter')"

All I do is create a model like the one in the readme example and call '< Form type={Person} / >' nothing else.

**Comment by gcanti** [comment]
The problem is with react ^15.2.x, I'll fix that asap

**Comment by gcanti** [comment]
Could you please try this branch? https://github.com/gcanti/tcomb-form-native/tree/195

**Comment by chuckyouliu** [comment]
See the form now, appreciate the fast response!

**Comment by gcanti** [comment]
Ok, thanks. Going to merge and release the fix

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.5.3
