### ISSUE TITLE
Question: How can I implement a (password) textinput with a button inside, to show/reveal the password when tapped?

### ISSUE THREAD

**Issue by SudoPlz** [gcanti/tcomb-form-native#197]
I was just wondering what path to take to implement what the title says using your beautiful library.!

**Comment by gcanti** [comment]
The simplest way would be to write a custom template:

(pseudo code)

```js
class MyPasswordComponent extends React.Component {
  
  state = {
    passwordDisplayed: false
  }

  toggleDisplay() {
    this.setState({ passwordDisplayed: !this.state.passwordDisplayed })
  }

  render() {
    return <div onClick={this.toggleDisplay.bind(this)}>...your input here..</div>
  }

}

// override the default template https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L4
function myPasswordTemplate(locals) {
  return ...
}

...

const Type = t.struct({
  password: t.String
})

const options = {
  fields: {
    password: {
      template: myPasswordTemplate
    }
  }
}
```

**Comment by SudoPlz** [comment]
Thank you!

**Comment by SudoPlz** [comment]
Ok for people looking for this in the future, I have created it:

**Comment by SudoPlz** [comment]
@gcanti if you find time you could perhaps add it to your library, because a password with such a show/hide label button I think is necessary to lots of people.

**Comment by gcanti** [comment]
@SudoPlz I want to keep this library lean, a useful component as yours may be published as a standalone component though

**Comment by abuammar** [comment]
@SudoPlz - how do i use it in my signing page?

**Comment by SudoPlz** [comment]
@abuammar I believe you're not passing the right template.

```
var options = {
    stylesheet: mergeFormCss({
        textbox: {
            normal: {
                textAlign: t.t('dir') == 'rtl' && Platform.OS == 'android' ? 'right' : 'left',
                height: 30, // have to do it on iOS
                color: 'white',
            },
        }
    }, 'flat'),
    fields: {
        email: {
            placeholder: t.t('Email'),
            auto: 'placeholders',
            error: t.t('Email is empty'),
            template: (locals) => textbox(locals, ),
        },
        password: {
            placeholder: t.t('Password'),
            auto: 'placeholders',
            error: t.t('Password is empty'),
            password: true,
            secureTextEntry: true,
            template: (locals) => textbox(locals, ), // <--- Here you have to pass the PasswordTemplate
        }
    }
};
```

**Comment by Otik133040040** [comment]
already in lib for hide and show password? @gcanti

**Comment by otikindriyana** [comment]
bro @SudoPlz  how to change value passwordHidden and secureTextEntry when click show/hide?

**Comment by SudoPlz** [comment]
@otikindriyana it's been 4 years, I don't even remember TBH, and we no longer use this library :/

**Comment by otikindriyana** [comment]
already solved
add:
`
onPasswordShowClicked(){    
        
    if(this.state.options.fields.confirmPassword.secureTextEntry == true){
      var options = t.update(this.state.options, {
        fields: {
          confirmPassword: {
            secureTextEntry: {'$set': false},
            config:{
              passwordHidden: {'$set': false},
            }
          }
        }
      });
      this.setState({options: options});
    }else if(this.state.options.fields.confirmPassword.secureTextEntry == false){
      var options = t.update(this.state.options, {
        fields: {
          confirmPassword: {
            secureTextEntry: {'$set': true},
            config:{
              passwordHidden: {'$set': true},
            }
          }
        }
      });
      this.setState({options: options});
    }
  }
`
