### ISSUE TITLE
Text inputs are weird on android

### ISSUE THREAD

**Issue by austinksmith** [gcanti/tcomb-form-native#198]
Using the latest version but on my forms the text inputs don't have the full borders around them only on android. The exact same form and styles on IOS show a full border around the input boxes..any idea what I can do to fix this on android? 
<img width="1099" alt="screenshot 2016-07-14 11 42 56" src="https://cloud.githubusercontent.com/assets/2227747/16845847/52fcc452-49b8-11e6-9c47-90ef911ddc28.png">

**Comment by gcanti** [comment]
Dupe of https://github.com/gcanti/tcomb-form-native/issues/129
