### ISSUE TITLE
Question - bring up a lowercase keyboard

### ISSUE THREAD

**Issue by newbreedofgeek** [gcanti/tcomb-form-native#199]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.5.3
- react-native v0.23.1

### Expected behaviour

This is more of a question, how do I bring up the lowercase keyboard on iOS when I have a simple form. e.g.- 
username: t.String
password: t.String

When I select the textbox on iOS the keyboard comes up and it defaults to normal keyboard. So the first key is an Uppercase letter. In React (i.e  HTML) you can disable this behaviour and bring up the lower case keyboard.

In the case of a username / password field, the keyboard defaulting to Uppercase is annoying.

### Actual behaviour

As you type, the first character is Upper Case.

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

```
```
Thanks very much.

**Comment by gcanti** [comment]
If there is an `react-native` API for that (e.g. `keyboardType`), then you should be able to do that with `tcomb-form-native` as well

> In React (i.e HTML) you can disable this behaviour and bring up the lower case keyboard

how?

**Comment by alvaromb** [comment]
`autoCapitalize` is your friend: http://facebook.github.io/react-native/releases/0.30/docs/textinput.html#autocapitalize

Take a look at the `TextInput` API docs 😊

**Comment by newbreedofgeek** [comment]
@alvaromb thanks. that worked.

@gcanti actually its the same in react (web) too. i.e. autoCapitalize="none"

**Comment by Dhrupal** [comment]
@alvaromb: Worked dost! Thank you :)

**Comment by kallayyash** [comment]
yes exactly we have to use :    autoCapitalize="none" 
 its working for me ):

if you are using component in that also u have to mention autoCapitalize={autoCapitalize}

Thanks hope u saved ur time 

Kallayya Hiremath

**Comment by lekeCoder** [comment]
> `autoCapitalize` is your friend: http://facebook.github.io/react-native/releases/0.30/docs/textinput.html#autocapitalize
> 
> Take a look at the `TextInput` API docs 😊

link no longer valid
