### ISSUE TITLE
Question: How to pass in standard options for t.dat?

### ISSUE THREAD

**Issue by jterskine** [gcanti/tcomb-form-native#20]
I would like to change the mode and minuteInterval.

Model:
```javascript
var form = t.struct({
	name: t.Str,
	birthdate: t.Dat
});
```
Options:
```javascript
var options = {
  fields: {
    birthdate: {
      mode: 'time',
      minuteInterval: 10,
    }
  }
};
```
Form component
```javascript
 <Form
    ref="form"
    type={form}
    onChange={this._onChange}
    options={options}
/>
```
`name` and `birthdate` render, but I am unable to modify the datePicker. Anything that I'm overlooking? Thanks!

**Comment by gcanti** [comment]
Just checked your code and works fine for me. I'm using tcomb-form-native v0.1.8 and react-native v0.4.3.

p.s.
Note. If you see the "red screen of death" is because you must pass a default value for the birthDate field (datePickerIOS requires a value, `null` is not allowed)

**Comment by jterskine** [comment]
Thanks! I had an another `options` lying around.. 

Great library.
