### ISSUE TITLE
Auto-Capitalisation of Field Names

### ISSUE THREAD

**Issue by michael-ar** [gcanti/tcomb-form-native#202]
### Version

- comb-form-native v0.5.3
- react-native v0.28.0

### Issue

Would be very useful to allow custom capitalisation of the field names. For example I have a card form with a `CVV` field, but I can't override the libraries default behaviour of displaying `Cvv`.

Is this currently possible?

**Comment by alvaromb** [comment]
Set a custom label for these fields

https://github.com/gcanti/tcomb-form-native#labels-and-placeholders

**Comment by michael-ar** [comment]
@alvaromb thank you for such  quick response, not sure how i missed that...

**Comment by alvaromb** [comment]
Glad to have helped ;) @michael-ar
