### ISSUE TITLE
Applying stylesheet doesn't seem to work

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#21]
I'm loading and applying the bootstrap stylesheet, or at least, I think I am. Nothing seems to be happening:

    var React = require('react-native');
    var t = require('tcomb-form-native');
    var styles = require('../Styles');
    var formStyles = require('tcomb-form-native/lib/stylesheets/bootstrap');

    var Form = t.form.Form;
    Form.stylesheet = formStyles;
    [....]
    <Form
	ref="form"
	 type={Login}
	options={options}
	/>

Any suggestions?

**Comment by gcanti** [comment]
Hi,
weird...anyway bootstrap is the default stylesheet so you can remove these lines:

```js
var React = require('react-native');
var t = require('tcomb-form-native');
var styles = require('../Styles');
// var formStyles = require('tcomb-form-native/lib/stylesheets/bootstrap');

var Form = t.form.Form;
// Form.stylesheet = formStyles;
[....]
<Form
ref="form"
 type={Login}
options={options}
/>
```

Let me know if it's everything ok

Giulio

**Comment by mschipperheyn** [comment]
This is on me. Sorry. I did get it to work.
