### ISSUE TITLE
Could it show Picker/DatePicker on Floating Bottom?not below the item.

### ISSUE THREAD

**Issue by dyguests** [gcanti/tcomb-form-native#211]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6
- react-native v0.28

### Expected behaviour

show Picker/DatePicker on Floating Bottom.

### Actual behaviour

show Picker/DatePicker below the item.

### Steps to reproduce

1.Tap a item use t.enums.
2.The Picker will show below the item.

### Stack trace and console log

None.

**Comment by alvaromb** [comment]
This is the default behaviour right now, the `Picker`s are collapsed in order to improve usability. If you don't want this behaviour, you have to drop your own custom factory or template.
