### ISSUE TITLE
textinput can't input chinese...just blink

### ISSUE THREAD

**Issue by shapenlone** [gcanti/tcomb-form-native#212]
### 0.6.0

Tell us which versions you are using:

- tcomb-form-native v0.6.0
- react-native v0.27.2

### Expected behaviour
just can input chinese.....

### Actual behaviour

can not input chinese.the inputText component just blink,and still input english...

thanks.

**Comment by gcanti** [comment]
It doesn't seem an issue with this library. Not sure how to handle chinese with RN, maybe you can tweak the `keyboardType` option

**Comment by shapenlone** [comment]
thx,but i solve this problem..
 Modify this textbox.js file...comment value={locals.value} add defaultValue={locals.value}
