### ISSUE TITLE
[Andoid datePicker] - minDate and maxDate support?

### ISSUE THREAD

**Issue by adamTrz** [gcanti/tcomb-form-native#214]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.0
- react-native v0.31.0
- checked on Nexus 6 emulator (API 23, Android6) and  same real device

### Expected behaviour

Passing maximumDate and minimumDate should update Android DatePicker options.

### Actual behaviour

At this point, Datepicker allow me to choose whatever date i wish, both as far in past or future as i want.

### Steps to reproduce

Here are some of options of Form:

```
const options = {
  auto: 'none',
  fields: {
    from: {
      label: 'Od:',
      placeholder: 'Od',
      minimumDate: new Date(),
      mode: 'date',
      config: {
        format: (date) => String(moment(date).format("dddd, MMMM Do YYYY")),
      }
    },
    to: {
      label: 'Do:',
      placeholder: 'Do',
      minimumDate: new Date(),
      mode: 'date',
      config: {
        format: (date) => String(moment(date).format("dddd, MMMM Do YYYY")),
      }
    },
...
```

**Comment by gcanti** [comment]
@alvaromb `minDate` and `maxDate` options seem missing here https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/datepicker.android.js#L70 is it correct?

**Comment by adamTrz** [comment]
Hi, I've made some changes in datebicker.android.js to render way i need it to: :)
`
      <TouchableNativeFeedback
        accessible={true}
        ref="input"
        background={background}
        onPress={function () {
          if (datePickerMode === 'time') {
            TimePickerAndroid.open({is24Hour: true})
              .then(function (time) {
                if (time.action !== TimePickerAndroid.dismissedAction) {
                  var newTime = new Date();
                  newTime.setHours(time.hour);
                  newTime.setMinutes(time.minute);
                  locals.onChange(newTime);
                }
              });
          } else {
            let config = {
              date: locals.value || new Date(),
            }
            if (locals.minimumDate) {
              config['minDate'] = locals.minimumDate
            }
            if (locals.maximumDate) {
              config['minDate'] = locals.maximumDate
            }
              // maxDate: locals.maximumDate || null,
              // minDate: locals.minimumDate || null
            DatePickerAndroid.open({...config})
              .then(function (date) {
                if (date.action !== DatePickerAndroid.dismissedAction) {
                  var newDate = new Date(date.year, date.month, date.day);
                  locals.onChange(newDate);
                }
              });
          }
        }}>
`

**Comment by alvaromb** [comment]
Yes, @gcanti, those configs are missing. Adding them right now!

**Comment by alvaromb** [comment]
There you go https://github.com/gcanti/tcomb-form-native/pull/219/files
