### ISSUE TITLE
t.update() is not working, 

### ISSUE THREAD

**Issue by derekmerrill** [gcanti/tcomb-form-native#216]
import React, { Component, PropTypes } from 'react';
import {connect} from 'react-redux';
import {form} from 'tcomb-form';
import {t} from 'tcomb-react';
import LaddaButton from 'react-ladda';
import R from 'ramda';
import {VerifyUser, User} from 'database/tcomb/user';
import {getUserDetails} from 'scripts/hotline_app/app_service';
import Toaster from 'scripts/components/toaster';
import {HotlineSettings} from 'database/tcomb/settings';
import {Link} from 'react-router';
import {ReactRoutes} from 'routes/enumerated_routes';

class HotlineSettingsPage extends Component {
    static displayName = 'HotlineSettingsPage';
    static propTypes = {
        user: PropTypes.object.isRequired,
        onSubmitForm: PropTypes.func.isRequired
    };
    constructor(props) {
        super(props);
        const {user,line_configuration} = this.props;
        
        this.state = {
            formValue: {
                first_name: user.first_name,
                last_name: user.last_name,
                phone: user.phone,
                call_rate: line_configuration && line_configuration.call_rate,
                start_time:12,
                end_time:5
            },
            formOptions:{
                template:(locals) => {
                    return (
                        <div className="customSettings">
                            <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                {locals.inputs.first_name}
                                {locals.inputs.last_name}
                            </div>
                        </div>
                    );
                },
                fields: {
                    first_name:{
                        attrs:{
                            placeholder : 'First Name',
                        },
                        disabled: true,
                        template: (local) => {
                            return (
                                <div className="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <label htmlFor={local.attrs.id}>First Name</label>
                                    <div  className="">
                                        <input disabled={local.disabled} type={local.type} value={local.value} name={local.attrs.name} onChange={this.updateStateValue} id={local.attrs.id}/>
                                        <span><img src="http://localhost:8081/app/styles/edit.png" alt={local.attrs.name} onClick={this.enableField}/></span>
                                    </div>
                                </div>
                            );
                        }
                    },
                    last_name:{
                        attrs:{
                            placeholder : 'Last Name'
                        },
                        disabled: true,
                        template: (local) => {
                            return (
                                <div className="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <label htmlFor={local.attrs.id}>Last Name</label>
                                    <div  className="" >
                                        <input disabled={local.disabled} type={local.type} value={local.value} name={local.attrs.name} onChange={this.updateStateValue} id={local.attrs.id}/>
                                        <span><img src="http://localhost:8081/app/styles/edit.png" alt={local.attrs.name} onClick={this.enableField}/></span>
                                    </div>
                                </div>
                            );
                        }
                    }
                }
            }
        };
    }
    handleClick = (e) => {
        const row = this.refs.form.getValue();
        console.log(row);
        console.log(this.state);
        if (row){
            this.props.onSubmitForm(row);
        }else{
            console.log('form invalid');
        }
    };

    onChange = (event) => {
        console.log(event);
    };

    updateStateValue = (event) => {
        
        let {formValue,formOptions} = this.state;
        formValue[event.target.name] = event.target.value;
        this.setState({formValue:formValue,formOptions:formOptions});
    };

    enableField = (event) => {
        
        let {formValue,formOptions} = this.state;
        let temp = {};
        temp[event.target.alt] = { disabled: {'$set': false}};
        let options = t.update(formOptions, {
            fields: temp
        });
        this.setState({formValue:formValue,formOptions:options});
        console.log(this);
    };
    
    render() {
        const {formValue} = this.state;
        const {formOptions} = this.state;
        return (
            <div className="content">
                <span className="logoSec">
                <img src="http://localhost:8081/app/styles/hotlineLogo.png"></img>
                </span>
                <div className="detailsSec settings">
                    <h3>Settings</h3>
                    <div className="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <form.Form ref="form"
                               type={HotlineSettings}
                               value={formValue}
                               options={formOptions} onChange={this.onChange}/>
                     </div>
                    
                    <p className="resetPwd">
                        <Link to={ReactRoutes.RESET_PASSWORD}>
                        Reset Password</Link>
                    </p>
                    <p className="deactivateLink"><a href="#">Deactivate my Hotline</a></p>
                    <span className="col-lg-6 col-md-6 col-sm-12 col-xs-12 buttonSec "> 
                        <a href="#" onClick={this.handleClick.bind(this)}>Save</a>
                    </span>
                    <span className="col-lg-6 col-md-6 col-sm-12 col-xs-12 buttonSec "> <a href="active.html">Cancel</a></span>
                </div>
                <Toaster {...this.props} />
            </div>
        )
    }
}

export default connect(
    state => (state.defaultReducer),
    dispatch => ({
        onSubmitForm: (form) => {
            getUserDetails(dispatch, form);
        },
    })
)(HotlineSettingsPage)

Normally every field is in disabled mode  when i click on edit icon field will become editable, here t.update is not working properly, form is not taking the new formoptions

**Comment by alvaromb** [comment]
Hello @derekmerrill!

Please open the issue in the right repo, this is for React Native.
