### ISSUE TITLE
form refs not available in modal

### ISSUE THREAD

**Issue by damianlajara** [gcanti/tcomb-form-native#218]
The following are the versions of react-native and tcomb from my `package.json` file:
"tcomb-form-native": "^0.6.0",
"react-native": "0.31.0"

In my handler `this.validateForm` that I am using on form submit, I am simply trying to access the ref from the form I have created like this: `this.refs.createCollectionForm.getValue();` but I keep getting this error:
> undefined is not an object (evaluating '_this.refs.createCollectionForm.getValue')

I have tried moving the `Form` around and found that it works in any view EXCEPT when inside the modal.
Following is a code snippet: 
```javascript
<View style={styles.container}>
        <Modal
          animationType={"slide"}
          transparent={false}
          visible={this.state.modalVisible}
          onRequestClose={this.toggleVisible}
          >
          <View style={styles.formContainer}>
            <Form
              ref="createCollectionForm"
              type={CollectionSchema}
              options={formOptions}
            />
            <TouchableHighlight style={styles.button} onPress={this.validateForm} underlayColor='#99d9f4'>
              <Text style={styles.buttonText}>Create</Text>
            </TouchableHighlight>
          </View>
        </Modal>
</View>
```

**Comment by gcanti** [comment]
@damianlajara it seems an upstream issue not specifically related to this library
