### ISSUE TITLE
Left Icon Support

### ISSUE THREAD

**Issue by idan-ratzabi** [gcanti/tcomb-form-native#221]
What do I need to do to add a left icon to each type of component (textBox,datePicker and so..). Do I have to customize each component by myself by subclassing the original one (e.g t.TextBox) ? Any easier way ? 
If I subclass the original component I'd still get the normal validation and so, correct ?

**Comment by alvaromb** [comment]
You have to build your own custom templates https://github.com/gcanti/tcomb-form-native#templates

**Comment by idan-ratzabi** [comment]
Would I have to implement the popping of the the native calendar myself (for datepicker component) ?  Anyway to use the tcomb implementation ?

**Comment by alvaromb** [comment]
Yes, you can take the existing templates as an example. Copy 'em and modify to bring your needs. Then, you can import and use them as templates or factories.

**Comment by alvaromb** [comment]
Just to clarify, we have provided the existing templates not only to have a bunch of working examples, but also to serve as an starting point to build your own.

**Comment by idan-ratzabi** [comment]
I understand. I'll have a look. Thanks

**Comment by alvaromb** [comment]
Cool! Let me know if you need anything else.

**Comment by Ivykp** [comment]
@alvaromb thank you for the answer. Currently i have [this template](https://gist.github.com/Ivykp/f1db5dd357e789b03134d5f47fe47475). However i would need to pass the **icon name** through the locals. How could i do it?

**Comment by flunder** [comment]
@Ivykp I've just got this to work with icons, made a gist, maybe it can help you https://gist.github.com/flunder/276ea1b3b373e905a7448614df261d6b
