### ISSUE TITLE
Horizontal separator?

### ISSUE THREAD

**Issue by ramsestom** [gcanti/tcomb-form-native#222]
Is there a simple way to add an horizontal separator between two fields of a form?

**Comment by razor1895** [comment]
hi, you could render a template to your form option

**Comment by alvaromb** [comment]
You could try to customize the stylesheets (see https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md) or drop a custom template. The first option is easier, but it may not fit your needs completely.
