### ISSUE TITLE
add property border bottom color and width to a textbox

### ISSUE THREAD

**Issue by danielCrespo01** [gcanti/tcomb-form-native#223]
it is possible to BorderBottom color and width to a textbox
try to use this but does not work:

```js
let Form = t.form.Form;
Form.stylesheet styleTCombForm = const;
styleTCombForm.textbox.normal={color:'red',height:40,marginBottom:10,padding:7,borderBottomWidth:4,borderBottomColor:'#47315a'};
```

**Comment by alvaromb** [comment]
It is possible. Simple steps to do that:

 - Copy & paste the bundled stylesheet.
 - Change the properties under the `textbox` key to fit your needs. 
 - Assign the newly created stylesheet in the options of the form

```js
const options = {
  stylesheet: newFormStylesheet
}

...

<Form options={options} />
```

I don't really get what are you really doing in the code you just posted, but there is an excellent stylesheets tutorial here https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md

**Comment by danielCrespo01** [comment]
with documentation succeed in making this code but the borderbottom property does not work
const stylesheet = load.cloneDeep(t.form.Form.stylesheet);

stylesheet.textbox= {
		normal:{
			color: 'red',
			fontSize: 12,
			height: 36,
			padding: 7,
    	                flexDirection: 'row',
    	                borderBottomColor: '#ddd',
    	                borderBottomWidth: .5,
			marginBottom: 5
		}
	};

**Comment by alvaromb** [comment]
This looks like a React Native problem, not an issue with this library. Try to use another width for the border and check `TextInput`' style props.

**Comment by danielCrespo01** [comment]
var Person = t.struct({
  name: t.String
});

function myCustomTemplate(locals) {

  var containerStyle = {...};
  var labelStyle = {...};
  var textboxStyle = {...};

  return (
    <View style={containerStyle}>
      <Text style={labelStyle}>{locals.label}</Text>
      <TextInput style={textboxStyle} />
    </View>
  );
}

var options = {
  fields: {
    name: {
      template: myCustomTemplate
    }
  }
};

Could you help me with an example that I can no longer access the myCustomTemplate method of example I am calling this way but it does not work:
template: {this.myCustomTemplate}
