### ISSUE TITLE
Big issue with react-native 0.33 

### ISSUE THREAD

**Issue by egghead27** [gcanti/tcomb-form-native#228]
### Version

Tell us which versions you are using:
- tcomb-form-native v0.6.1
- react-native v0.33
### Expected behaviour

Fill normally the input text field.
### Actual behaviour

When a letter is typed on the keyboard, it appears then it desappears...
Finally, the field is always empty.
### Steps to reproduce

Here is a piece of my code

`var Form = t.form.Form;

var Email = t.refinement(t.String, function (m) {
  var re = /^(([^<>()[]\.,;:\s@"]+(.[^<>()[]\.,;:\s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/;
  return re.test(m);
});

// here we are: define your domain model
var Person = t.struct({
  name: t.String,              // a required string
  email: Email,
});

var options = {
     i18n: {
    optional: ' (optionnel)',
    surname : 'Prénom',
    required: '',
    add: 'Add',   // add button
    remove: '✘',  // remove button
    up: '↑',      // move up button
    down: '↓'     // move down button
  },
  fields: {
    name: {
      label: 'Nom'
    },
    email:{
        keyboardType: 'email-address',
        error: 'Votre email n\'est correct'
    }
  }
}; // optional rendering options (see documentation)` 

And for the rendering 

`  render() {
    return (
      <View style={styles.container2}>
        {/\* display */}
        <Form
          ref="form"
          type={Person}
          options={options}

```
    />
   <TouchableHighlight style={styles.button} onPress={this.onPress.bind(this)} underlayColor='#99d9f4'>
      <Text style={styles.buttonText}>Save</Text>
    </TouchableHighlight>
  </View>
);
```

  }`
### Stack trace and console log

console.log stay empty and there is no error log, so no stacktrace....

**Comment by ansmonjol** [comment]
Maybe you forgot to add `onChange={this._onChange.bind(this)}` In your `<Form />` and create the onChange Function like this 
```
_onChange(value) {
  // Update the value of the fields
  this.setState({ value });
}
```

**Comment by egghead27** [comment]
Hello, unfortunately, the onchange method is already in the tcomb native lib. I looked at it, and placed a log, the value is treated with success. It's after the onchange call that the field is erased.

I think you should know that i dev an app for android 5.1.

PS: i met another issue with the navheader bar from NavigationExperimental. It don't display.

**Comment by kendrickkesley** [comment]
Hi! I experienced the same problem yesterday
I used the form like this

> <Form
>           ref="form"
>           type={Person}
>           value={this.state.value}
>           onChange={this.onChange}
>         />

but i forgot to change the state onChange..
this.setState({value: value});

hope this helps!

**Comment by alvaromb** [comment]
Which RN version?

**Comment by apoorv-1310** [comment]
0.55.4
