### ISSUE TITLE
Styling doesn't work

### ISSUE THREAD

**Issue by BogdanHossu** [gcanti/tcomb-form-native#229]
### Version
- tcomb-form-native v0.6.1
- react-native v0.32.0

I have set borderRadius to my field but doesn't wants to change, also added a background color but that one works. Do somebody knows what can be the issue?

```
textbox: {
    normal: {
      color: INPUT_COLOR,
      fontSize: FONT_SIZE,
      height: 36,
      padding: 7,
      borderRadius: 4,
      borderColor: BORDER_COLOR,
      borderWidth: 1,
      marginBottom: 5,
      backgroundColor: 'white'
    }
```

**Comment by wasa4587** [comment]
Documentation is bad, you need to pass all stylesheets

This worked for me
```
import bootstrap from 'tcomb-form-native/lib/stylesheets/bootstrap.js';
var options = {
  stylesheet : bootstrap
}
override the specific stylesheet
options.stylesheet.textbox.normal = {
  color: '#fff',
  height: 36,
  padding: 7,
  borderRadius: 4,
  borderWidth: 0,
  marginBottom: 5
};
```

**Comment by vanng822** [comment]
@wasa4587 This still not solve the problem I am facing. My problem is that I have many input fields which I want different height for each. Look like no way to do this? Isn't it better to also pass style per field name.

**Comment by alvaromb** [comment]
@vanng822 you can pass the `stylesheet` option per field:

```js
options: {
  fields: {
    myField: {
      stylesheet: myStylesheet,
    }
  }
}
```

**Comment by alvaromb** [comment]
@BogdanHossu I don't exactly get what's your issue, can you elaborate?

**Comment by alvaromb** [comment]
Closing, please ping me @BogdanHossu if you're still experiencing problems when styling your forms.
