### ISSUE TITLE
integration with webpack

### ISSUE THREAD

**Issue by abhishiv** [gcanti/tcomb-form-native#23]
From this file: https://github.com/gcanti/tcomb-form-native/blob/master/lib/util/React.js

```
var React;
try {
  React = require.call(this, 'react');
} catch(e) {
  React = require('react-native');
}
module.exports = React;
```

This results in the following error while using webpack (via mjohnston/react-native-webpack-server), 

```
WARNING in ./~/tcomb-form-native/lib/util/React.js
Critical dependencies:
12:10-17 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/tcomb-form-native/lib/util/React.js 12:10-17
```

I'm not really aware of another solution, but maybe once facebook/react-native#1331 is implemented?

**Comment by gcanti** [comment]
I need that util in order to execute the tests in node. If we can find a way to run the tests with react-native instead of react I can remove it

**Comment by ppiekarczyk** [comment]
:+1: just ran into this same issue. 

Is this only run for the test? Could it be possible to solve in something similar located here? https://github.com/webpack/webpack/issues/424
