### ISSUE TITLE
Can i do this styling? with tcomb form

### ISSUE THREAD

**Issue by jariwalabhavesh** [gcanti/tcomb-form-native#230]
![screen shot 2016-09-19 at 6 49 57 pm](https://cloud.githubusercontent.com/assets/10993666/18633431/e60ac01c-7e99-11e6-96b5-fba8646fd1d1.png)

i want to create design like show in screenshot. How can i achieve this kind of design in single form.

I had already created this design by using separate form :
1st form contents firstName and lastname and
2nd form contents role and company.

if i put all four together all four field are arranged in same row. 
i got reference from https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md regarding this kind of design.

can any one suggest or is there any way that i can create this design using single form component.

**Comment by alvaromb** [comment]
You can do it with custom stylesheets, [docs here](https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md) and custom templates, [docs here](https://github.com/gcanti/tcomb-form-native#templates).

Also, check out this issue that contains relevant information for creating custom templates (credit card form example) https://github.com/gcanti/tcomb-form-native/issues/151.

**Comment by jariwalabhavesh** [comment]
Thank You @alvaromb
