### ISSUE TITLE
you can add keyboard control?

### ISSUE THREAD

**Issue by danielCrespo01** [gcanti/tcomb-form-native#232]
You could use another library or perform methods to better control the keyboard and hide when the view is touched or generate a scroll so that the keyboard comes a little below the input in which enrolling.

**Comment by Nicolas-Menettrier** [comment]
Hello, just wrap you're view in https://github.com/APSL/react-native-keyboard-aware-scroll-view

**Comment by alvaromb** [comment]
Answered, thanks @Nicolas-Menettrier !
