### ISSUE TITLE
How do I specify enum Picker default Item label other than -

### ISSUE THREAD

**Issue by ptah23** [gcanti/tcomb-form-native#237]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1
- react-native v0.34

### Expected behaviour

How do specify my own label for the first item in the Picker

### Actual behaviour
First Item label is always -

Is there a way to configure it to be something else like "Tap to Choose"?

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form-native#nulloption-option
