### ISSUE TITLE
Remove unnecessary bottom border Android from default style

### ISSUE THREAD

**Issue by sibelius** [gcanti/tcomb-form-native#239]
### Version

Tell us which versions you are using:
- tcomb-form-native v0.6.1
- react-native v0.34.0

Every TextInput has unnecessary bottom border after RN34

https://github.com/facebook/react-native/issues/10108

![input](https://cloud.githubusercontent.com/assets/4318513/18829564/850dddde-83e5-11e6-82c0-07556ad51cf4.png)

we should set `underlineColorAndroid='transparent'` as the default

**Comment by alvaromb** [comment]
Hi @sibelius!

Thanks for reporting this. Can you send a PR? 😄 

Many thanks!

**Comment by sibelius** [comment]
should I change just this style: https://github.com/gcanti/tcomb-form-native/blob/master/lib/stylesheets/bootstrap.js#L62?

**Comment by sibelius** [comment]
I've added there, but I'm receiving an error

invalid props.style key `underlineColorAndroid` supplied to `TextInput`

**Comment by compojoom** [comment]
I'm working on the same thing.
underlineColorAndroid is not a style property, but a property of TextInput. You'll have to pass it in your options for the field...

@alvaromb - maybe we should make a global property for the options underlineColorAndroid that would be automatically applied to all fields?

**Comment by alvaromb** [comment]
I'm in for maintaining the actual behaviour, add it to the `options` of the text field.

**Comment by sibelius** [comment]
how can I solve this problem right now?

I've tried this

```js
const options = {
      auto: 'placeholders',
      fields: {
        email: {
          maxLength: 250,
          autoCorrect: false,
          keyboardType: 'email-address',
          autoCapitalize: 'none',
         underlineColorAndroid: 'transparent',
          onSubmitEditing: () => this.refs.form.getComponent('password').refs.input.focus()
        },
        password: {
          maxLength: 70,
          secureTextEntry: true,
         underlineColorAndroid: 'transparent',
          error: 'Must have 6-12 characters with at least 1 number and 1 special character'
        }
      }
    };
```

but it did not worked

**Comment by compojoom** [comment]
But it should. This is what I have in my options as well:
```
{
		stylesheet: stylesheet,
		auto: 'none',
		fields: {
			name: {
				placeholder: 'Name',
				underlineColorAndroid: 'transparent',
			},
```

and it works...

**Comment by sibelius** [comment]
I did a clean install, and worked well, tks

@alvaromb I just feel that `underlineColorAndroid: 'transparent',` should be the default, but style is just a matter of taste

feel free to close this issue if u wanna keep the current defaults

**Comment by compojoom** [comment]
The problem with this not being the default is that the style on android looks bad. 

But it's hard to make it default as it is not a style property. So maybe updating the docs would solve the issue. I'm sure that there a lot of users out there, that have no clue why the form looks bad on android out of the box :(

**Comment by gcanti** [comment]
You are talking about adding a default, so is not a breaking change, right?
What are the possibile issues of adding a default to `underlineColorAndroid`?

**Comment by sibelius** [comment]
it is not a breaking change

the only issue is that it will not show the underlineColor on android as it was the behavior before RN34

**Comment by gcanti** [comment]
Let me understand, if we add `underlineColorAndroid = 'transparent'` as a default, will users of < RN34 be affected in some way? If the answer is yes, it *is* a breaking change and we should stick with the current behaviour

**Comment by sibelius** [comment]
the answer is no

check this out - https://github.com/facebook/react-native/issues/10108

**Comment by cmrichards** [comment]
:+1:  for being a default

**Comment by cmrichards** [comment]
Is there a way to set it as a global default without needing to add  "underlineColorAndroid: 'transparent'' to the config for every field I create with tbomb-form-native? That would be really useful.  

Great library btw!

**Comment by adamrainsby** [comment]
I agree it shouldn't show the line by default.

**Comment by adamrainsby** [comment]
Pull request here: https://github.com/gcanti/tcomb-form-native/pull/254

**Comment by adamrainsby** [comment]
I don't think this is a breaking change because it was transparent by default before 0.34.

**Comment by javiercr** [comment]
+1 for setting `underlineColorAndroid=' transparent` as default, i.e. merging #254 . Also I agree with @cmrichards it would be nice to be able to change this prop globally.

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form-native/releases/tag/v0.6.2

**Comment by Bmkaradia** [comment]
<TextInput underlineColorAndroid={'transparent'}   placeholder="Username"/>

**Comment by guillaume250** [comment]
you can set the underlineColorAndroid property to RGBA(0,0,0,0) like this  `<TextInput underlineColorAndroid="rgba(0,0,0,0)"`

**Comment by Darkiring** [comment]
underlineColorAndroid="transparent"

**Comment by ghost** [comment]
In dark mode underlineColorAndroid="transparent" not working .
