### ISSUE TITLE
this.refs.form.getValue() is undefined ( Cannot read property 'form' of undefined)

### ISSUE THREAD

**Issue by trungbbvitalify** [gcanti/tcomb-form-native#241]
### Version
Latest version
Tell us which versions you are using:
Latest version

### Expected behaviour

this.refs.form.getValue()
need get value that inputed from form 

### Actual behaviour

can not get value that inputed from form , fatal error happen 

### Steps to reproduce

If i put on press function 
onPress: function () {
    // call getValue() to get the values of the form
    var value = this.refs.form.getValue();
    if (value) { // if validation fails, value will be null
      console.log(value); // value here is an instance of Person
    }
  }
in class testabc extends React.Component {
...
}
error happen , but if follow example put it in 
var AwesomeProject = React.createClass({
}
it works fine .

**Comment by alvaromb** [comment]
Sorry @trungbbvitalify but the error report is very opaque. Are you sure you have correctly used the `ref` prop in your form? It seems that this is a programming error, not related with the library.

**Comment by gcanti** [comment]
Can't repro without a code example, please file a complete issue
