### ISSUE TITLE
Globalization - Support comma as decimal mark, and dot as thousand seperator

### ISSUE THREAD

**Issue by tom-zeit** [gcanti/tcomb-form-native#243]
Hello, first of all thanks for all the contributors for a great library! :)

I'm building an app for the german market and I would really like to have a support for german number formatting, which is : 100.132,25.
The desired behaviour will show the user the mentioned number formatting when typing, but in the code, the returned value will be a normal javascript Number. 

I couldn't find a way to do it in the library, the closet thing was:
https://github.com/gcanti/tcomb-form-native/issues/57

But this solution doesn't support the thousand separator, and it doesn't support initial populated values.

Thanks!

**Comment by gcanti** [comment]
Hi, 

Did you define a custom transformer as suggested in that issue?

**Comment by alvaromb** [comment]
Hello @tom-zeit!

It seems that you need a custom transformer for adding support of comma decimal. For the dot separator, maybe you could do that only in the displayed value, modifying the number to display in the `render` lifecycle event. You could eliminate the dot separator in your transformer but add it when displaying the value.

**Comment by tom-zeit** [comment]
@gcanti - yea I did.
@alvaromb  - What do you mean by changing the render? How can I control the rendering of the field inside the form?

**Comment by alvaromb** [comment]
Well, I was a bit confused with transformer/refinements for validation. In the end I think you could do that using a custom transformer. Use `t.String` as the type of the field and build a custom refinement for validating the entered input (i.e., `12.000,76` should be a valid number, `1a.000,76` should not).

**Comment by tom-zeit** [comment]
My solution in the end was to use the transformer proposed in #57 , but also with replacing dots with empty string. Full code:
```

var germanNumberFormatter = {
  format: value => Nil.is(value) ? null : String(value),
  parse: value =>{
    if(value) {
      value = value.replace('.','')
      value = value.replace(/,/g, '.')
    }
    var n = parseFloat(value);
    var isNumeric = (value - n + 1) >= 0;
    return isNumeric ? n : toNull(value);
  }
};
// Globally set number transformer
t.form.Textbox.numberTransformer = germanNumberFormatter;

```

For the initial value problem, I just formatted the value with the right format before providing it to the form.


Thanks for the help!
