### ISSUE TITLE
UISwitch moving slowly

### ISSUE THREAD

**Issue by neilyoung** [gcanti/tcomb-form-native#246]
Wrong behavior shown in video. 

http://maps.alphadex.de/tcomb-native.mov

Any idea why?

**Comment by alvaromb** [comment]
You have the `Enable slow animations` option in your iOS simulator turned on:

https://www.natashatherobot.com/ios-simulator-slow-animations/

**Comment by neilyoung** [comment]
Cool. Wasn't aware of this. But noticed already, that the Switch component did also behave like so. Was already about to remove the issue. You've been faster. ;)

Thanks.
