### ISSUE TITLE
Add Version Support Table

### ISSUE THREAD

**Issue by dangnelson** [gcanti/tcomb-form-native#248]
I'm working on a standard for displaying version support on React-Native module README files. I would love your feedback: [react-native-version-support-table](https://github.com/dangnelson/react-native-version-support-table)

**Comment by alvaromb** [comment]
This is great, @dangnelson!

Honestly it will take some time to find all the past versions and their RN matching version... @gcanti how do you feel about adding this *from the current version and onwards?

**Comment by gcanti** [comment]
👍 now in the README we display

- tcomb-form-native ^0.5: react-native >= 0.25.0
- tcomb-form-native ^0.4: react-native >= 0.20.0
- tcomb-form-native ^0.3: react-native < 0.13.0

**Comment by dangnelson** [comment]
Thanks. I wrote it up thinking it would be optional to provide that level of detail, in hopes people would at least use it for the most recent version they've released. Then expand it as needed based on their circumstance.

**Comment by alvaromb** [comment]
PR: https://github.com/gcanti/tcomb-form-native/pull/255

Let me know if I missed something.

**Comment by dangnelson** [comment]
Looks great, thanks!
