### ISSUE TITLE
It would be nice if the <Text> component for the data value were wrapped in a <View> so we could add a border

### ISSUE THREAD

**Issue by cmrichards** [gcanti/tcomb-form-native#250]
`var value = locals.value ? <Text style={dateValueStyle}>{formattedValue}</Text> : null;`

It would be good to be able to put a border around the date displayed in the datepicker for android (I'm guessing the issue exists in iOS too?).    At the moment it just looks like a piece of unclickable text rather than some kind of input field. 

It's not possible to add a border on a <Text> component and wrapping  in a View would allow this.  Something like : 

`var value = locals.value ? <View style={...}><Text style={dateValueStyle}>{formattedValue}</Text></View> : null;`

https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/datepicker.android.js#L50

I appreciate that the boostrap templates are only a guide and we can create our own, but I think this is a sensible addition as this template is useful.

**Comment by compojoom** [comment]
Can't you use this? https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/datepicker.android.js#L53

**Comment by alvaromb** [comment]
This should be supported with the latest version: https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/textbox.js#L37
