### ISSUE TITLE
Optional field ask need input data 

### ISSUE THREAD

**Issue by trungbbvitalify** [gcanti/tcomb-form-native#252]
Hi,

I'm trying to use select component  (as example )  with custom options not use default value like this 

var Gender = t.enums({
  M: 'Male',
  F: 'Female'
});

var Person = t.struct({
  name: t.String,
  surname: t.String,
  email: t.maybe(t.String),
  age: t.Number,
  rememberMe: t.Boolean,
  gender: t.maybe(Gender) // enum
});
 and options like this 
var options = {
  fields: {
  gender: {
      nullOption: {value: '1', text: 'Choose it'},
      options :[{ value: '2', text: 'abc'},{ value: '3', text: 'xyz'}]
  }
 }
};
It can be render form like a charm and input data for all fields event optional field 
, But when i summit form ( var value = this.refs.form.getValue();) validator will  alert ask need input value for gender field ??.
May be i got somethings wrong ?
Many Thanks

Version

tcomb-form-native v0.6.0
react-native v0.32.1

**Comment by alvaromb** [comment]
Can you format a bit your code? It's really hard to read it this way 😝

**Comment by ansmonjol** [comment]
Did you tried to log your state.value when submitting ?

Maybe you forgot the `onChange` function in your form then the state value is not updated ?

---------------------------
@alvaromb 
```javascript
var Gender = t.enums({
   M: 'Male',
   F: 'Female'
});

var Person = t.struct({
   name: t.String,
   surname: t.String,
   email: t.maybe(t.String),
   age: t.Number,
   rememberMe: t.Boolean, 
   gender: t.maybe(Gender) // enum
});
```
and options like this 
```javascript
var options = {
   fields: {
      gender: {
         nullOption: {value: '1', text: 'Choose it'},
         options :[{ value: '2', text: 'abc'},{ value: '3', text: 'xyz'}]
      }
   }
};
```

**Comment by alvaromb** [comment]
The supported `Gender` values are `M` and `F`, you're passing another values. Change it to match what you define in your `enum`.
