### ISSUE TITLE
how to add text between 2 input text box

### ISSUE THREAD

**Issue by atilaqi** [gcanti/tcomb-form-native#253]
I am wondering if I can insert some text which can navigate to new page when clicking between 2 input text box. like the text in red circle .

Thanks in advance.  
 
![qq 20161014161239](https://cloud.githubusercontent.com/assets/2506571/19380311/5490b616-9229-11e6-8a1d-e4cffe93491b.png)

**Comment by alvaromb** [comment]
You can write a custom template for that field or... separate the form into two forms. I bet the first option will be better for your needs. https://github.com/gcanti/tcomb-form-native#templates
