### ISSUE TITLE
add image before every Textbox in form

### ISSUE THREAD

**Issue by abuammar** [gcanti/tcomb-form-native#258]
### Version

Tell us which versions you are using:

"tcomb-form-native": "^0.5.3"
"react-native": "^0.34.0",

### Expected behaviour

a login form with two textbox username and password, i want to dispaly image before username and pasword textbox.

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by c4d3r** [comment]
You can also make a new template, copy the existing bootstrap template perhaps and then just edit out the textbox form. in the options of your form add: `templates: yourCustomTemplate` where you define `yourCustomTemplate` as `yourCustomTemplate=require('tcomb-form-native/lib/templates/bootstrap` and next you set `yourCustomTemplate.textbox=require('yourCustomTextboxComponent`)` hope this helps! :) next time please try making a post on stackoverflow :)

**Comment by alvaromb** [comment]
@c4d3r is right, creating a custom template is one option, docs here: https://github.com/gcanti/tcomb-form-native#templates
