### ISSUE TITLE
Missed keystrokes

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#26]
I'm seeing a lot missed keystrokes on my forms (iPhone 6 simulator). Seems to me that the rendering cycle is to blame and I'm not sure if the same problem would occur on the live phone but it shouldn't happen in the first place.. Perhaps an input box should use onBlur to update state or use some kind of buffer.

**Comment by gcanti** [comment]
> Seems to me that the rendering cycle is to blame 

Yes thanks for pointing out. After some tweaks I think that the main problem is having "controlled inputs". 
Removing `this.setState({value})` in the `onChange` handler speeds up the things.

https://github.com/gcanti/tcomb-form-native/blob/master/lib/core.js#L87

**Comment by gcanti** [comment]
should be fixed in v0.2
