### ISSUE TITLE
Remove Android input borderWidth

### ISSUE THREAD

**Issue by ansmonjol** [gcanti/tcomb-form-native#260]
### Version

- tcomb-form-native v0.6.1
- react-native v0.35.0

### Expected behaviour

On android, I only want my inputs to have the `underlineColorAndroid` and no `borderWidth`
On IOS, I only want a `borderWith: 1`

### Actual behaviour

On Android, I have both `underlineColorAndroid` and `borderWidth` when I create an input with the tcomb lib.
If I create an input by importing `TextInput` from react-native lib , I have an input with the native platform style rules.

### Steps to reproduce

1. Create input with tcomb lib
2. See what happen

### Screenshots

Here is the style of the inputs I create on Android
**Note that the third one is one created by importing `TextInput` from react-native lib.**

<img width="316" alt="screen shot 2016-10-24 at 11 13 07" src="https://cloud.githubusercontent.com/assets/5517077/19642041/44cf5f84-99db-11e6-8329-869a994860a7.png">

--------------------------
https://material.google.com/components/text-fields.html#

**Comment by wasa4587** [comment]
You can override the stylesheets

This worked for me
```
import bootstrap from 'tcomb-form-native/lib/stylesheets/bootstrap.js';
var options = {
  stylesheet : bootstrap
}
override the specific stylesheet
options.stylesheet.textbox.normal = {
  color: '#fff',
  borderWidth: 0
};
```

**Comment by ansmonjol** [comment]
Great, thanks !

I think I should be implemented natively in tcomb, since it's a native style requirement for material design.
