### ISSUE TITLE
TextInput android style not normal

### ISSUE THREAD

**Issue by zleast** [gcanti/tcomb-form-native#261]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1
- react-native v0.35

**Comment by gcanti** [comment]
Please, fill in the relevant sections:

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by zleast** [comment]
@gcanti  sorry. I think underlineColorAndroid default value should be "transparent". I found can set it at options
