### ISSUE TITLE
Is there any way to add matrial-design icons in form ??? 

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [gcanti/tcomb-form-native#262]
### Version

Tell us which versions you are using:
- tcomb-form-native v0.?.?
  latest
- react-native v0.?.?
  react-native-cli: 1.0.0
  react-native: 0.35.0

**Comment by alvaromb** [comment]
Yes, custom templates: https://github.com/gcanti/tcomb-form-native#templates
