### ISSUE TITLE
crash when focusing a textbox

### ISSUE THREAD

**Issue by ducduong** [gcanti/tcomb-form-native#267]
I'm fighting a crash whenever I focus to a textbox, not sure if it is the library or dependencies so I post it here.

```
const Form = t.form.Form

const User = t.struct({
  name: t.String,
  phone: t.String,
  email: t.String,
  pin: t.String,
})

export default class TabSignup extends React.Component {
  render () {
    return (
      <View style={styles.tabContent}>
        <Form
          ref="form"
          type={User}
          options={options}
        />
        <Button block onPress={this.continue.bind(this)}> Continue </Button>
      </View>
    )
  }
}
```

![image](https://cloud.githubusercontent.com/assets/13758/20019712/fa093160-a2a3-11e6-9b51-20b8c1169c22.png)

**Comment by ducduong** [comment]
never mind, it's not related to tcomb, I tried a simple Textbox and it crashed too.

**Comment by alvaromb** [comment]
I'm the author of that library, react-native-keyboard-aware-scroll-view. Please check the compatibility of your RN version with the library version installed. 

If you need further help, open an issue into the other library. 

Enviado desde mi iPhone

**Comment by ducduong** [comment]
@alvaromb thank you, I upgraded RN and React to the latest versions and all are fine now.
