### ISSUE TITLE
Schema validation using Joi

### ISSUE THREAD

**Issue by joelmarquez90** [gcanti/tcomb-form-native#268]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1
- react-native v0.36.1

### Enhance

I have an API that uses [Joi](https://github.com/hapijs/joi) for validating request body and query params. It would be great if I could use those same schemas in order to validate the form.

**Comment by alvaromb** [comment]
`tcomb` already validates your forms, I don't get exactly how that library would fit inside `tcomb-form-native`. Any thoughts @gcanti ?

**Comment by gcanti** [comment]
In order to reutilize the same schemas, you'd need a conversion joi -> tcomb
