### ISSUE TITLE
override behavior of pickers

### ISSUE THREAD

**Issue by flizzer** [gcanti/tcomb-form-native#271]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1
- react-native v0.37.0

Just curious if there is a way to override the default behavior of pickers.  For example, when using a .Date field, a DatePickerIOS component gets rendered.  However, a date is displayed with a time and a timezone at the top, even if I set the mode as "date":

<img width="588" alt="screen shot 2016-11-14 at 9 43 54 pm" src="https://cloud.githubusercontent.com/assets/596833/20291352/87845f6c-aab3-11e6-8ddb-31f6753dafd7.png">

Can I customize how the date gets displayed or remove it altogether?  I've looked at the react-native docs and can't see a good way for how to do this so not sure if it's possible.  The same goes for enums.  Can I remove the label that gets displayed:

<img width="659" alt="screen shot 2016-11-14 at 9 47 01 pm" src="https://cloud.githubusercontent.com/assets/596833/20291412/03a21a76-aab4-11e6-9b75-beca09675bf7.png">

Thanks in advance for any help.

```
```

**Comment by alvaromb** [comment]
You can pass a `config` object in your form options that can contain a `format` function that will format the date value: https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/datepicker.ios.js#L34

For the enums, it will always render the selected value so you should create a custom template if you prefer to have a different behaviour.

**Comment by flizzer** [comment]
Thanks for the help!  The docs mention looking at the dateTouchable and dateValue stylesheet keys for customizing the collapsing.  I'd like to make the default behavior "uncollapsed".  How would I do that please?  Thanks.

**Comment by alvaromb** [comment]
You need to bring a custom template to do that. The current template doesn't have a prop to disable the collapsible behaviour (but it would be cool, wanna send a PR? 😉).

**Comment by flizzer** [comment]
Possibly.  It looks like the current template has a "collapsed" property but it's not publicly available.  So I thought about modding that one so that consumers could specify collapsible or not.  Or should I create a new template for a "NonCollapsibleDatePickerIOS"?

**Comment by alvaromb** [comment]
Sounds good @flizzer!

Do you want to send a PR? Feel free to ping me if you need help with something!

**Comment by flizzer** [comment]
@alvaromb in thinking this through some more, I like the idea of a new NonCollapsibleDatePickerIOS and specifying via an options.config prop which one to use, but how would that get wired up so that a Date field gets rendered as either a CollapsibleDatePickerIOS or a NonCollapsibleDatePickerIOS?  I'm not sure I see how these objects get composed.  And yes, I'll be happy to send a PR once I get out of my own way :)  Thanks.
