### ISSUE TITLE
DatePickerAndroid with placeholder and textbox styling

### ISSUE THREAD

**Issue by jesouhaite08** [gcanti/tcomb-form-native#277]
I am using the DatePickerAndroid on my form. I want it to be empty by default, have a placeholder and have the same styling of a textbox.

I don't see a way to implement this, aside from using a custom template, but wanted to verify.

Thanks.

**Comment by alvaromb** [comment]
Custom template is the way to go @jesouhaite08. Please let me know if you need further assistance.
