### ISSUE TITLE
Problem with value and nullOption set to false

### ISSUE THREAD

**Issue by damathryx** [gcanti/tcomb-form-native#278]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1
- react-native v0.38.0

### Expected behaviour

Trying to set defaultValue for picker
nullOption is set to false,

`const locationsForm = {
    auto: 'none',
   fields: {
      locations: {
        nullOption: false
      }
   }
}`
`const locationsValue = {
  locations: 0
}`
`<Form ref="location" type={t.struct({ locations: t.enums.of([_.map(locations, 'address')]) })} value={value} options={locationsForm} />`
### Actual behaviour

ComponentWillMount keeps on triggering
getting error
![screen shot 2016-12-13 at 3 34 13 pm](https://cloud.githubusercontent.com/assets/14576761/21131663/f32e4892-c14a-11e6-95eb-2f38c0e77042.png)
![screen shot 2016-12-13 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/14576761/21131664/f385afba-c14a-11e6-8644-e475ab6b1292.png)

### Stack trace and console log
![screen shot 2016-12-13 at 3 49 16 pm](https://cloud.githubusercontent.com/assets/14576761/21131818/c2da0536-c14b-11e6-8737-de57ed91d159.png)

**Comment by alvaromb** [comment]
Hi @damathryx!

It is possible that the default value you're passing is not available in the enum options?

**Comment by damathryx** [comment]
I set the defaultValue to the first result of the array
`const locationsValue = { locations: 0 }`
I'm only passing array inside t.enums.of.

**Comment by alvaromb** [comment]
Sorry, I don't get what's exactly going on, can you post the form type you're using?

**Comment by damathryx** [comment]
`<Form ref="location" type={t.struct({ locations: t.enums.of([_.map(locations, 'address')]) })} value={value} options={locationsForm} />`

**Comment by alvaromb** [comment]
I think the problem is that your `defaultValue` is not present in the locations, thus resulting in the `selectedOption` undefined.

**Comment by damathryx** [comment]
Fixed it by transforming the array to object using lodash.
`_.zipObject(_.range(locations.length), _.map(locations, 'address'))`
supplied to
`t.enums`
