### ISSUE TITLE
[Question] Is there a way to have multiple-page forms?

### ISSUE THREAD

**Issue by mikaoelitiana** [gcanti/tcomb-form-native#279]
I wanted to know if there is a way to create a multiple-page form. Say in a registration form I want to have user general data on first page. The user will click a "next" button and the a pages for education, interests,... will be loaded one after another. 

Thanks

**Comment by alvaromb** [comment]
Hi @mikaoelitiana!

It's possible, but `tcomb-form-native` will not autogenerate the navigation, the pages, etc.

You will need to build  a navigation and use this library in each page you need a form.

**Comment by alvaromb** [comment]
Please, take a look at this thread https://github.com/gcanti/tcomb-form-native/issues/25

**Comment by mikaoelitiana** [comment]
OK thanks
