### ISSUE TITLE
Styling items in Select

### ISSUE THREAD

**Issue by arajigah** [gcanti/tcomb-form-native#280]
I'm trying to change the text color inside Select from black to white on ios. I don't see a way to override this; I tried `t.form.Form.stylesheet.select.normal.color` but it throws an error about using `color` in a `View`.

Is there an easier way to change the text color inside Select?

**Comment by brookehurford** [comment]
I am also having trouble styling the select box. I can changed styles for the select options, but not the default box before clicking it open.

Any tips?

**Comment by alvaromb** [comment]
You need to use the `itemStyle` prop on iOS. http://facebook.github.io/react-native/releases/0.42/docs/picker.html#itemstyle

Pass it as a local, not in the stylesheet: https://github.com/gcanti/tcomb-form-native/blob/master/lib/templates/bootstrap/select.ios.js#L72
