### ISSUE TITLE
options props is not passed to Form class

### ISSUE THREAD

**Issue by waterstar** [gcanti/tcomb-form-native#281]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.1 and v0.5.3
- react-native v0.37.0

### Expected behaviour

Tell us what should happen
options props should work as documented

### Actual behaviour

Tell us what happens instead
options props has no effect. Try to debug by putting a break point around getComponentOptions function and notice this.props.options (so does this.props.value) has no value.

### Steps to reproduce

1. create a simple Form as documented
2. change a field by passing options variable to Form's options props
3. notice there is no change in any field

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by gcanti** [comment]
This is too generic, please provide a minimal example reproducing the issue

**Comment by waterstar** [comment]
Here is the code I tested. Not sure is relevant, I am running the code on Exponent platform. 

```
import React from 'react';
import { StyleSheet, Text, View, TouchableHighlight } from 'react-native';

var t = require('tcomb-form-native');
var Form = t.form.Form;
// here we are: define your domain model
var product = t.struct({
              QRcode: t.String,
              name: t.String,
              phoneNumber: t.Number,
            });

var basicopts = {
      label: 'testing...'
      fields:{
        QRcode: {
          label: 'QR Code',
        },
        name: {
          label: 'Name ...',
        },
        phoneNumber: {
          label: 'Phone Number',
        }
      }
    };

let get_options = (v) => { return basicopts; }

export default class NewBasicForm extends React.Component
{
  render() {
    return (
      <View style={styles.container}>
        <Form
          ref="basicform"
          options={basicopts} value={{name:'testing...'}} type={product}
        />
      </View>
    );
  }
}

```

**Comment by waterstar** [comment]
Sorry for this false alarm... is my mistake that I have edited a buffer instead of actual file.
