### ISSUE TITLE
TimePickerAndroid not showing on mode datetime only DatePicker.

### ISSUE THREAD

**Issue by damathryx** [gcanti/tcomb-form-native#283]
- tcomb-form-native v0.6.1
- react-native v0.38.0

```
const dateForm = {
      auto: 'none',
      fields: {
        date_time: {
          minimumDate: new Date(new Date().getTime() + (24 * 60 * 60 * 1000)),
          minuteInterval: 10,
          mode: 'datetime',
          config: {
            format: date => String(moment(date).format('D MMM YYYY HH:MM A')),
          },
        },
      },
    };
```
only datepicker shows not timepicker in android.

**Comment by luisguilhermemsalmeida** [comment]
Anything on this? Having the same issue here, I think a workaround would be to show first datepicker and then timepicker on android

**Comment by pk2004** [comment]
We are also having the same issue here. Agree with @luisguilhermemsalmeida datepicker then timepicker seems like a reasonable approach.

**Comment by kingctan** [comment]
no datetime mode. I also need this features.

**Comment by alvaromb** [comment]
There are two components in `react-native`, `TimePickerAndroid` and `DatePickerAndroid`. This library exposes both, but AFAIK there is no `DateTimePickerAndroid` or similar stuff in RN.

Feel free to ping me if I'm wrong :)

**Comment by JWDobken** [comment]
What is the status of this issue?
Has anyone implemented a solution already?

**Comment by alvaromb** [comment]
Hi all!

I'm currently working on this, please feel free to test the initial implementation: https://github.com/gcanti/tcomb-form-native/pull/410

**Comment by alvaromb** [comment]
Merged in master.
