### ISSUE TITLE
[IOS datePicker] - minDate and maxDate support?

### ISSUE THREAD

**Issue by semirturgay** [gcanti/tcomb-form-native#284]
### Version

Hi i am using latest versions of both react-native and tcomb-form-native. 

`minDate` and `maxDate` options does not works for ios datepicker.

**Comment by semirturgay** [comment]
it seems this options are set as `maximumDate` and `minimumDate` as prop.They are not set in config object like android. 

```
{
          stylesheet: styles.datePickerStyles,
          config: {
              format: (value) => moment(value).format("MM/DD/YYYY"),
          },
          mode: "date",
          maximumDate:moment(new Date())
}

**Comment by ngnclht1102** [comment]
@semirturgay I have the same problem, could you tell me how can you solve that?

**Comment by yasemincidem** [comment]
@ngnclht1102 reason of problem is `moment(new Date())`.When you use moment(new Date()),it returns Moment object.But maximumDate accept `Date` as value of type.As a result of you should convert `moment()` object to `Date` with `toDate()` method.Here is right:
```
{
     stylesheet: styles.datePickerStyles,
     config: {
         format: (value) => moment(value).format("MM/DD/YYYY"),
     },
     mode: "date",
     maximumDate:moment(new Date()).toDate()
}
```

**Comment by ngnclht1102** [comment]
@yasemincidem Thanks, I got it. It worked!!
