### ISSUE TITLE
Adding new types/controls to the form?

### ISSUE THREAD

**Issue by aksonov** [gcanti/tcomb-form-native#29]
I want to add 'slider' and 'range' slider to the form for 'age' selection. How to add new custom types into the form?

**Comment by gcanti** [comment]
I'd go for a custom template https://github.com/gcanti/tcomb-form-native#templates

**Comment by aksonov** [comment]
Yes, thanks, got it - pass it via 'options' for specific fields ('age' in my case), right?

**Comment by gcanti** [comment]
Right
