### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by vsrinivas150283** [gcanti/tcomb-form-native#293]
Most of the time, forms do have file upload feature.
Can we implement file upload option using templates? Does anyone worked on this?

**Comment by alvaromb** [comment]
I worked on this, but outside of the scope of this library. A file upload would require an external library to handle the access of the filesystem. If you have an idea, please feel free to send a PR.

Thanks.

**Comment by piranna** [comment]
Can you point us where you were working on this topic?
