### ISSUE TITLE
TextInput Focus Error

### ISSUE THREAD

**Issue by Richard-Cao** [gcanti/tcomb-form-native#294]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.3
- react-native v0.39.2

```
this.form.getComponent('email')
```

is this:
![da6793e6-fa71-4515-a65f-3f0d52f8a5eb](https://cloud.githubusercontent.com/assets/5953992/22066768/7753a1ea-ddc9-11e6-98d5-a95965d8eeb9.png)

```
this.form.getComponent('email').refs
```

is only an object, and

```
this.form.getComponent('email').refs.input
```
is undefined, not have `focus()` function and so on.

**Comment by Richard-Cao** [comment]
@gcanti

**Comment by skoob13** [comment]
Have the same issue with custom components. Is there any solution?

**Comment by Geczy** [comment]
@skoob13 can you post your solution code
