### ISSUE TITLE
Is there a way to compare value with value of another field within refinement?

### ISSUE THREAD

**Issue by ilyadoroshin** [gcanti/tcomb-form-native#297]
Hi, guys! 

Is there a way to keep this logic in refinement and not to do that via component state? would be great though.. like:

`F.struct({`
`  email:           F.String,`
`  newEmail:        F.refinement(F.String, function(email) {`
`    return email !== this.email.value`
`  }),`
`})`

Thanks!

**Comment by javiercr** [comment]
I was wondering exactly the same. I have a simple sign up form with two fields `password` and `passwordConfirmation` and I'd like the second one to be marked in red on submit, (after calling `this.refs.form.getValue()`), if the passwords don't match.

**Comment by fogg4444** [comment]
Very interested if anyone has solved this yet.

**Comment by alvaromb** [comment]
I have done this. Take this code as an example:

```js
    const PasswordMinLength = t.refinement(t.String, value => {
      return value.length > 6
    })
    const ConfirmPasswordEquality = t.refinement(t.String, value => {
      return value === this.state.value.password
    })
    this.SignupFormStruct = t.struct({
      name: t.String,
      middle_name: t.maybe(t.String),
      surname: t.String,
      birth_date: t.Dat,
      address: t.String,
      country_pid: t.enums(props.countries, 'Countries'),
      province_pid: t.maybe(t.String),
      city_pid: t.maybe(t.String),
      postcode: t.String,
      phone: t.String,
      email: t.String,
      password: PasswordMinLength,
      confirm_password: ConfirmPasswordEquality,
    })
```

The trick is to save the state of the form and use it in your refinements.

**Comment by chirag04** [comment]
@gcanti thoughts on this?
