### ISSUE TITLE
date field issue

### ISSUE THREAD

**Issue by mayanksahai** [gcanti/tcomb-form-native#298]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.5
react-native-cli: 2.0.1
react-native: 0.40.0

i am using method to initialise model object

function getType(value) {
  var props = { // fixed fields
    description: t.String,              // a required string
    ownedTo: t.maybe(t.String),  // an optional string
    amount: t.Number,
    expenseCategory: ExpenseCategory,
    incurredDate: t.Date,// a required number
    shared: t.Boolean,       // a boolean
  };
  if (value.shared) {
    props.email = t.String; // required and visible
  }
  return t.struct(props);
}

it shows select date in Mon Jan 23 2017 23:34:48 GMT +0800 (SGT)

is there a way to format it and to take just date only. no time and time zone info ?

so it picks Mon Jan 23 2017 only.

**Comment by alvaromb** [comment]
Look at the `format` key: https://github.com/gcanti/tcomb-form-native#ios-date-config-option

**Comment by hussamkurd** [comment]
@alvaromb any example

**Comment by Renegade1821** [comment]
@hussamkurd insert something like this to the options of your date ( moment is moments.js )
```
  config: {
        format: (date) => {
          const formatedDate = moment(date).format('DD.MM.YYYY');
          return formatedDate;
        },
      },
```
