### ISSUE TITLE
Correct way to update domain model programmatically?

### ISSUE THREAD

**Issue by chadobado** [gcanti/tcomb-form-native#3]
Loving this library, thanks for porting it to React-Native!

As per the readme:
```
3. No need to update forms when domain model changes
```
How do you update the domain model programmatically?  

..or at least return the current state of all inputs (not just ones that pass validation via getValue)?

*Edit: Just noticed that onChange will pass current state of all inputs*

I might be going about this the wrong way but it doesn't appear that the domain model object is updatable or elements of the domain model (or generated inputs) are being mounted as writable props on this.refs.form.props. 

Use cases: 

1. Radio inputs (multiple inputs, only one can be selected at once)
2. Updating one input based on the value of another (country -> state -> city selectors)
3. Progressive/expanding forms (user enters email -> secondary email confirmation input appears)
4. Field to field validation (secondary email input validates against primary email input)

Most React-ish way I found was to assign the forms default values (as per [this](https://github.com/gcanti/tcomb-form-native#default-values)) to the parent's state and update as needed with setState.  Unfortunately this expectedly will reset any other user-modified inputs to their initial default values.

Also tried extending this.state.values with this.refs.form.getValue()'s response (along with any changes I want to inject), but this will expectedly reset any inputs that do not pass validation (since they are not returned by getValue) which effectively clears the users progress and any error message.

*Edit:  didn't realize that getValue only returns if all inputs validate.  Thought it returned data for individual fields that validated successfully.*

**Radio input example:**

```javascript
var ChildInfo = t.struct({            
  birthDate: t.Dat,
  male: t.maybe(t.Bool),
  female: t.maybe(t.Bool),
});

var SignupChildView = React.createClass({
  getInitialState: function(){
    return {
      values: {}
    }
  },
  _onChange: function() {
    var value = this.refs.form.getValue();
    if (value.male === true) { // if male checkbox is selected, deselect the female checkbox
      
      var _values = this.state.values
      _values['female'] = false
      this.setState({values: _values})
      
    }
    if (value.female === true) { // if female checkbox is selected, deselect the male checkbox
      
      var _values = this.state.values
      _values['male'] = false
      this.setState({values: _values})
      
    }

  },
  render: function() {
    return (
      <View style={styles.container}>
        {/* display */}
        
        <Form
          ref="form"
          type={ChildInfo}
          value={this.state.values}
          options={options}
          onChange={this._onChange}
        />
        <TouchableHighlight style={styles.button} onPress={this._onSubmit} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Next</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```
Maybe there's a way to do this?  If not, would be awesome to have the option of defining the domain model itself as a part of component state to more easily leverage React's reconciliation.

Thanks in advance for your feedback, and again for this awesome library!

**Comment by gcanti** [comment]
Hi,
I'd implement male/female choice with a select:

```js
var Gender = t.enums({
    M: 'Male',
    F: 'Female'
});

var ChildInfo = t.struct({            
  birthDate: t.Dat,
  gender: Gender
});
```

If you really want to use two switches, I'd make them required:

```js
var ChildInfo = t.struct({
  birthDate: t.Dat,
  male: t.Bool, // required
  female: t.Bool // required
});

var options = {};

var AwesomeProject = React.createClass({

  onPress: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  getInitialState: function(){
    return {
      values: {male: true, female: false} // provide a default value (e.g. male)
    }
  },

  _onChange: function(values) { // <-- onChange receives the current state of all inputs
    if (values.male !== this.state.values.male) {
      values.female = !this.state.values.female;
    } else if (values.female !== this.state.values.female) {
      values.male = !this.state.values.male;
    }
    this.setState({values: values});
  },

  render: function() {
    return (
      <View style={styles.container}>
        <Form
          ref="form"
          type={ChildInfo}
          value={this.state.values}
          options={options}
          onChange={this._onChange}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```

> Updating one input based on the value of another (country -> state -> city selectors)

Yes it's possible, you can change the type on the fly:

```js
var Country = t.enums({
  IT: 'Italy',
  US: 'United States'
});

var states = {
  IT: {
    L: 'Lombardia',
    V: 'Veneto',
    P: 'Piemonte'
  },
  US: {
    CA: 'California',
    NY: 'New York'
  }
};

var options = {};

var AwesomeProject = React.createClass({

  onPress: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  getInitialState: function(){
    return {
      type: t.struct({country: Country}),
      values: {}
    }
  },

  _onChange: function(values) {
    var props = {country: Country}; // <- change this type on the fly...
    var country = values.country; // <- ...based on this value
    if (!country) {
      values = {};
    } else {
      if (country !== this.state.values.country) {
        values.state = null;
      }
      props[country] = t.enums(states[country]);
    }
    this.setState({
      type: t.struct(props),
      values: values
    });
  },

  render: function() {
    return (
      <View style={styles.container}>
        <Form
          ref="form"
          type={this.state.type}
          value={this.state.values}
          options={options}
          onChange={this._onChange}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```

**Comment by gcanti** [comment]
> Thought it returned data for individual fields that validated successfully

If you need it, you can get the raw validation result calling `getValue(true)`. getValue will return a `ValidationResult` object with a `value` field containing the individual fields that validated successfully.

**Comment by chadobado** [comment]
Great thank you for the suggestions - all are helpful!

I also found your other repo with the original library and other answers which are all helpful.

One last question, is ```hasError``` been implemented as a valid field option for this library?  I've been trying to implement something similar to your great example here:

https://github.com/gcanti/tcomb-form/issues/79

Snippet:

```javascript
this.setState({
            options: {
              fields: {
                email: {
                  hasError: true,
                  error: 'Invalid email'
                }
              }
            }
          });
```

But adding ```hasError: true``` on the fly has no effect.  Similarly, if I define  ```hasError: true``` into the initial options, it does not render the form with the error as I would expect... 

In the following simple example:

```javascript
var options = {
  order: ['email','email2','password','rememberMe'],
  auto: 'placeholders',
  fields: {
    email: {
      hasError: true,
      placeholder: 'Enter your email',
      error:'Testing error',
    },
    email2: {
      placeholder: 'Please retype your email',
    },
    password: {
      password: true
    },
    rememberMe: {
      onTintColor: '#48BBEC',
      
    }
  }
};

```

**Comment by gcanti** [comment]
Ops, I'm afraid I missed the `hasError` option. I just made a commit with the relevant change
