### ISSUE TITLE
View was rendered with explicitly set width/height but with a 0 flexBasis

### ISSUE THREAD

**Issue by radiegtya** [gcanti/tcomb-form-native#300]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.4
- react-native v0.40.0

### Expected behaviour

the form should be rendered 

### Actual behaviour

it produce error: View was rendered with explicitly set width/height but with a 0 flexBasis

### Steps to reproduce

1. change flex to flexGrow (http://stackoverflow.com/questions/41004883/react-native-view-was-rendered-with-explicitly-set-width-height-but-with-a-0-fle)

### Stack trace and console log

<img width="320" alt="tcomb" src="https://cloud.githubusercontent.com/assets/2161622/22411133/fe1cc24e-e6d2-11e6-8cee-55bfecdbe957.png">
<img width="1276" alt="tcomb2" src="https://cloud.githubusercontent.com/assets/2161622/22411134/fe206bb0-e6d2-11e6-8d6b-62852766c2f2.png">

```
```

**Comment by alvaromb** [comment]
I don't think this error belongs to `tcomb-form-native`.

**Comment by futurechallenger** [comment]
@radiegtya it may be caused by this break changes in RN 0.36, check this out, https://github.com/facebook/react-native/wiki/Breaking-Changes#fix-unconstraint-sizing-in-main-axis-0a9b6b---emilsjolander
