### ISSUE TITLE
Problem with ScrollView and TextInputs on Android

### ISSUE THREAD

**Issue by miguelmsanchezm** [gcanti/tcomb-form-native#301]
### Version
- tcomb-form-native v0.6.4
- react-native v0.38.0

### Expected behaviour

Be able to scroll even when touching the TextInput.

### Actual behaviour

There is a padding of 7 set in the `stylesheets/bootstrap.js`
 ` stylesheet: {
      ...
         textbox: {
            normal: {
               ...
               padding: 7,`

Which creates a scroll inside the TextInput that takes the focus from the parent ScrollView. If we set that padding to 0, the problem is solved.
On iOS works even with the padding set to 7.

Someone has experience the same issue ?

**Comment by alvaromb** [comment]
Hi @miguelmsanchezm!

Yes, I'm experiencing the same issue. Working on a fit ATM.
