### ISSUE TITLE
Example using JSON Data

### ISSUE THREAD

**Issue by indivisable** [gcanti/tcomb-form-native#302]
Is there an example using JSON data?

> JSON Schema support
> 
> JSON Schemas are also supported via the (tiny) tcomb-json-schema library.
> 
> Note. Please use tcomb-json-schema ^0.2.5.

**Comment by alvaromb** [comment]
There is no example available, just the docs in the lib https://github.com/gcanti/tcomb-json-schema

Please feel free to send a PR with an example :)
