### ISSUE TITLE
Datepicker launch crashes on React Native v0.41.2

### ISSUE THREAD

**Issue by casoetan** [gcanti/tcomb-form-native#306]
### Version

- tcomb-form-native v0.6.0
- react-native v0.41.2

### Expected behaviour
When I click a date / datetime field, a Datepicker should pop up

### Actual behaviour

App crashes

### Steps to reproduce

1. Add a date field as usual t.Date
2. Launch app and try to click on the field for the Datepicker popup
3. CRASH...

### Stack trace and console log

```sh
TypeError: expected dynamic type `double', but had type `string'
getDouble
    ReadableNativeMap.java:-2
createFragmentArguments
    DatePickerDialogModule.java:172
open
    DatePickerDialogModule.java:159
invoke
    Method.java:-2
invoke
    BaseJavaModule.java:319
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:818
```

![screenshot_1486430611](https://cloud.githubusercontent.com/assets/1047316/22673778/77b61c54-ecdc-11e6-9613-b34386e5a768.png)

**Comment by wuxudong** [comment]
+1

Version
tcomb-form-native 0.6.4
react-native 0.42.0-rc.1

**Comment by alvaromb** [comment]
Hi!

@casoetan is this issue still present?

**Comment by casoetan** [comment]
Fixed.

**Comment by sdstolworthy** [comment]
What did you do to resolve? I'm having this same problem

**Comment by NickAlvesX** [comment]
@sdstolworthy Same.

**Comment by jerome-smith** [comment]
having the same issue:  @casoetan  please let me know how you resolved this issue
