### ISSUE TITLE
temporary save feature

### ISSUE THREAD

**Issue by litingjun2015** [gcanti/tcomb-form-native#309]
### Version

Tell us which versions you are using:

- tcomb-form-native v3.10.8
- react-native v0.39.2

### Expected behaviour

my form have many fields which are required, customer might not fill in all fields at one time, could you provide a temporary save feature for them to fill in information next time.

###
Thanks

**Comment by ZohraS** [comment]
Why not use Async to store the values?

**Comment by alvaromb** [comment]
Use the `onChange` event of the `Form` to save your form state before submitting.
