### ISSUE TITLE
TextInput does not scroll as you type more

### ISSUE THREAD

**Issue by pgmemk** [gcanti/tcomb-form-native#31]
Thank you for the great library :-). I am extensively using it for our open source app.

One problem:

When you use react-native's **TextInput** component and type more than is visible, the text in the **TextInput** gets scrolled to the left while you are typing. Your's does not scroll. It allows to type as much as you want and will submit the whole value but you don’t see the rightmost part of the text which you typed.

**Comment by gcanti** [comment]
Hi!

Seems related to padding (10 im my case). If I set a padding with a value greater than 7 it doesn't scroll to the right.
I filed a issue https://github.com/facebook/react-native/issues/1718. As a workaround I could replace 10 with 7 in the default stylesheet.

**Comment by pgmemk** [comment]
Thank you
