### ISSUE TITLE
Template options accept function only, should accept text

### ISSUE THREAD

**Issue by mikaoelitiana** [gcanti/tcomb-form-native#311]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.4
- react-native v0.37.0

### Expected behaviour

Template options should accept text as template value, not fonction only: 

```

var options = {
  fields: {
    name: {
      template: myCustomTemplate
    }
  }
};

````

We need that when storing options in database instead of writing it in the code. We will get something like: 

```
var options = {
  fields: {
    name: {
      template: 'myCustomTemplate'
    }
  }
};
```

### Actual behaviour

We using options stored in database, we get an error saying myCustomTemplate is not a function.

### Steps to reproduce

1. Create a template function and put it in code
2. Store and retrieve options from database
3. Use retrieved options in code

**Comment by gcanti** [comment]
How tcomb-form-native can know what to do with the string `'myCustomTemplate'`?

**Comment by mikaoelitiana** [comment]
From step 1: "Create a template function and put it in code". So `myCustomTemplate` is present in code but not called directly.

**Comment by gcanti** [comment]
It's not clear how it would work in practice, how you get a reference to the function `myCustomTemplate` using the string `'myCustomTemplate'`? Please provide an example of a sensible implementation.

**Comment by mikaoelitiana** [comment]
I am not sure yet but maybe something like this: 

```
hello = function(name){console.log("hello", name)};
// ...
str = "hello"
fn = new Function(str + "('world')")
fn() // "hello world"
```

**Comment by gcanti** [comment]
An acceptable solution should not use globals, `eval` or `new Function`. Closing for now

**Comment by mikaoelitiana** [comment]
ok thanks
