### ISSUE TITLE
Provide callback parameter to form.getValue(), so it can be handled asynchronously

### ISSUE THREAD

**Issue by andrewhl** [gcanti/tcomb-form-native#313]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.4
- react-native v0.40.0

### Expected behaviour

I have a situation where I am triggering a React Native Alert if a user has modified a form and attempted to leave the view without saving. I am using `this.form.getValue()` as a representation of the state of the form. If it is null, I fire the `popRoute`, otherwise I alert the user.

```javascript
    handleClose = () => {
        const formValue = this.form.getValue();

        if (!formValue) {
            this.props.popRoute(this.props.navigation.key);
            return;
        }

        Alert.alert('You have unsaved changes.', 'Are you sure you want to leave?', [
            {text: 'Cancel'},
            {text: 'Ok', onPress: () => this.props.popRoute(this.props.navigation.key)}
        ]);
    };
```

I expect that for complex forms, with multiple values, that I will be able to handle this asynchronous behaviour synchronously. That I can, at minimum, call a callback function after `this.form.getValue()` has returned.

I would like to be able to pass a callback function to `this.form.getValue()`:

```javascript
    handleClose = () => {
        this.form.getValue(this.onComplete);    
    };

    onComplete = (value) => {
        if (!value) {
            this.props.popRoute(this.props.navigation.key);
            return;
        }

        Alert.alert('You have unsaved changes.', 'Are you sure you want to leave?', [
            {text: 'Cancel'},
            {text: 'Ok', onPress: () => this.props.popRoute(this.props.navigation.key)}
        ]);
    }
```

### Actual behaviour

For simple forms I have no issue, but for forms with multiple fields, the `popRoute` is executed before `this.form.getValue()` completes, and the component unmounts. This causes a "No View to update" error.

### Steps to reproduce

1. Create a form with multiple fields (> 5)
2. Implement the above close behaviour with an Alert
3. In other words, create a situation where getValue() will resolve after the component has unmounted

### Stack trace and console log
![img_3001](https://cloud.githubusercontent.com/assets/1120082/22953220/4193211e-f2de-11e6-9972-6028af42041f.PNG)

**Comment by alvaromb** [comment]
Hi @andrewhl!

AFAIK, your issue it's not related with `tcomb-form-native`, but more with how you're navigating between your scenes. I think that what you are experiencing is your navigator unmounting the current scene.

`getValue` runs synchronously and doesn't accept a callback or any other parameter. Even if it was async, you would suffer the same issue I think. What you need to do is to prevent the scene unmounting, can you tell me which navigation system are you using?

**Comment by andrewhl** [comment]
Hello @alvaromb! Thanks for your response. We are using NavigationExperimental from react-native. We'll be soon switching to [react-navigation](https://reactnavigation.org/). Unfortunately, we had some urgency with this feature and wound up resolving it by switching to Redux Form. I think we can close this issue as it stands as I won't be able to confirm whether a different navigation system resolves it.

**Comment by alvaromb** [comment]
I think your issue was related with how NavigationExperimental handle your `handleClose` function, but I can't be sure without looking at the actual code.

Thanks for your report, I've been unable to jump in until today.

**Comment by andrewhl** [comment]
@alvaromb No problem! Cheers.
