### ISSUE TITLE
Q: Is it possible to respond to changes to individual fields?

### ISSUE THREAD

**Issue by flyingace** [gcanti/tcomb-form-native#318]
- tcomb-form-native v0.6.4
- react-native v0.41.2

Is it possible to respond to changes to individual fields rather than just to changes to the entire form? If so, how is this done?

**Comment by muthuraman007** [comment]
In form tag , you need to use form **options** for adding event handler to individual field,
var Form=t.form.Form;
```
<Form
type={}
options={}  // <= 
/>
```
you need to define options like this
```
var options={
fields:{
txtBox1:{
label:"Name"
onTextChange: () => { }  // <= event handling function 
}
}
}
```

**Comment by alvaromb** [comment]
Closing, feel free to ping me @flyingace if you need further help!

**Comment by newfylox** [comment]
Hi!

I have the same issue. Even with what @muthuraman007 suggested it doesn't work. There's no functions or codes that I see in this library (when I browse the code) that handle "onChangeText" anywhere.

Am I wrong? Thanks!
