### ISSUE TITLE
How do I change the color of the switch / checkbox / boolean ? Currently it won't change from green

### ISSUE THREAD

**Issue by brookehurford** [gcanti/tcomb-form-native#323]
### Version

Tell us which versions you are using:

- tcomb-form-native: 0.6.4
- react-native v0.41.2

### Expected behaviour

To be able to change the color when a boolean is switched to on

### Actual behaviour

Haven't been able to target this with any of the stylesheet documentation tips, I also looked at switchiOS and haven't been able to get any of that to work either.

**Comment by alvaromb** [comment]
Please use the `onTintColor` local config option: https://github.com/gcanti/tcomb-form-native/blob/8287ccaf70fa757c98c6f895c4572875d0c9c4ff/README.md#other-standard-options-1
