### ISSUE TITLE
Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by pocesar** [gcanti/tcomb-form-native#324]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.5
- react-native v0.41.0

### Expected behaviour

t.Boolean works

### Actual behaviour

```
Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

<init>
StaticLayout.java:423

MakeLayout
SwitchCompat.java:606

onMeasure
SwitchCompat.java:526

measure
View.java:20214

measure 
ReactSiwtchManager.java:62
```

### Steps to reproduce

1. Create a form with t.struct({ empty: t.Boolean })
2. Navigate to the form 

### Stack trace and console log

There's no console.log, and since it's happening on Java, it has no debug break

**Comment by marcosschroh** [comment]
@pocesar I have the same problem. Did you find a solution?

**Comment by pocesar** [comment]
nope, had to resort to a t.list with Yes / No

**Comment by alvaromb** [comment]
Hi @pocesar!

Can you show us the source code in order to reproduce the issue?
