### ISSUE TITLE
0.6.6 no padding on TextInput on Android

### ISSUE THREAD

**Issue by pocesar** [gcanti/tcomb-form-native#327]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.6
- react-native v0.42.0

### Expected behaviour

Correct horizontal padding on inputs

### Actual behaviour

The text inside TextInput has no padding, it's glued to the side border

### Steps to reproduce

1. Upgrade to react-native 0.42
2. Use any form with t.String

Actually I think it was caused by aa6aa7ec328add489bcc9c24f30e7a185cb262c1 on Android it should have at least a paddingHorizontal of 7

**Comment by alvaromb** [comment]
Hi @pocesar!

I'm open to review a PR for this issue :)

**Comment by alvaromb** [comment]
Update to 0.6.7.
