### ISSUE TITLE
Label and field options doesn't work for t.list(t.struct())

### ISSUE THREAD

**Issue by pocesar** [gcanti/tcomb-form-native#328]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.6
- react-native v0.42.0

### Expected behaviour

This code should have proper labels:

```jsx
const Model = t.struct({
  list: t.list(
    t.struct({
      name: t.String,
      type: t.String
    })
  )
})

<Form type={Model} options={{  
  fields: {
     list: {
       label: '',
       fields: {
         name: {
           label: 'Nome'
         }, 
         type: {
            label: 'Tipo'
         }
       }
     }
  }
}} />
```

### Actual behaviour

The labels are not applied to the list items, the inputs created when adding new items to the list are 'Name' and 'Type' respectively. it seems that the nested t.struct options inside fields are all ignored

**Comment by pocesar** [comment]
All options under the nested `fields` are ignored

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb-form-native#items-configuration

**Comment by pocesar** [comment]
doesn't work

**Comment by pocesar** [comment]
the only documented example is the "Nested structures" but doesn't the combination of t.list and t.struct

**Comment by gcanti** [comment]
I meant that you missed the item option in the code above, try

```js
<Form type={Model} options={{  
  fields: {
     list: {
       label: '',
       item: {
         fields: {
           name: {
             label: 'Nome'
           }, 
           type: {
              label: 'Tipo'
           }
         }
       }
     }
  }
}} />
```

**Comment by pocesar** [comment]
thanks, works now. I guess the examples could be updated to reflect using list of nested structs (constructive feedback)

**Comment by alvaromb** [comment]
Hi @pocesar!

How do you feel about sending a PR? :)

**Comment by pocesar** [comment]
sure :)
