### ISSUE TITLE
Manually setting state on validation exception with password field generates error

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#33]
So, I process server side exceptions by setting state against a tcomb form

    var options = Object.freeze({
	  fields:{
		j_username:{
		  label:i8n.getMessage('ui.email'),
			placeholder:i8n.getMessage('ui.email'),
			error: i8n.getMessage('errors.email'),
			keyboardType:'email-address',
			autoCorrect:false
		},
		j_password:{
		  label:i8n.getMessage('ui.password'),
			placeholder:i8n.getMessage('ui.password'),
		  error: i8n.getMessage('errors.password'),
			password:true
		}
	  }
	});

[...]

    	LoginActions.login(value.j_username,value.j_password)
        .then(status)
        .catch(function(err){
             this.setState({
                options:utils.processServerExceptions(options,err)
             });

So, processServerException just loops over the errors and if the fieldname matches, it will return a copy of the object with the relevante field getting a new error message and hasError:true

So, if the password field is the one generating the exception, I get this error, presumably because iOS doesn't allow you to set the password field

Error setting property 'secureTextEntry' of RCTTextField with tag #228:RCTTextField does not have setter for secureTextEntry' property.

**Comment by gcanti** [comment]
I can't reproduce your error. 

My setup:

- tcomb-form-native v0.2.2
- react-native v0.5.0

This snippet works fine if can be helpful:

```js
var Form = t.form.Form;

var Credentials = t.struct({
  username: t.Str,
  password: t.Str
});

var AwesomeProject = React.createClass({

  getInitialState() {

    // initial options
    return {
      options: {
        fields: {
          username: {},
          password: {
            password: true
          }
        }
      }
    };
  },

  onPress() {
    var value = this.refs.form.getValue();
    if (value) {

      // disable al fields while submitting
      this.setState({
        options: t.update(this.state.options, {
          fields: {
            username: {
              editable: {'$set': false}
            },
            password: {
              editable: {'$set': false}
            }
          }
        })
      });

      // fake server call
      setTimeout(() => {
        this.setState({
          options: t.update(this.state.options, {
            fields: {
              username: {
                editable: {'$set': true}
              },
              password: {
                editable: {'$set': true},
                hasError: {'$set': true},
                error: {'$set': 'Server error!'}
              }
            }
          })
        });
      }, 2000);
    }
  },

  render() {
    return (
      <View style={styles.container}>
        <Form
          ref="form"
          type={Credentials}
          options={this.state.options}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 50,
    padding: 20,
    //backgroundColor: '#333333'
    backgroundColor: '#ffffff'
  },
  title: {
    fontSize: 30,
    alignSelf: 'center',
    marginBottom: 30
  },
  buttonText: {
    fontSize: 18,
    color: 'white',
    alignSelf: 'center'
  },
  button: {
    height: 36,
    backgroundColor: '#48BBEC',
    borderColor: '#48BBEC',
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 10,
    alignSelf: 'stretch',
    justifyContent: 'center'
  }
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```
