### ISSUE TITLE
Placeholder font size

### ISSUE THREAD

**Issue by brascene** [gcanti/tcomb-form-native#332]
Hi, how can we change placeholder text font size?

**Comment by javiercr** [comment]
You can follow the guide here:
https://github.com/gcanti/tcomb-form-native/blob/master/docs/STYLESHEETS.md#overriding-the-style-locally

However note that in React Native the `fontSize` for the placeholder of a [`<TextInput>`](https://facebook.github.io/react-native/docs/textinput.html) is always the same than the `fontSize` of the input itself. If you really need to have a different font size for the placeholder you'll probably have to create a custom TextInput component and the corresponding factory / template for tcomb-form-native.

**Comment by alvaromb** [comment]
Thanks for jumping into the issue @javiercr!

**Comment by brascene** [comment]
@javiercr Thank you very much, it's good enough that input fontsize is equal to placeholder fontsize :)
