### ISSUE TITLE
Custom factory with react-native-autocomplete-input

### ISSUE THREAD

**Issue by sun2rise** [gcanti/tcomb-form-native#335]
It would be very useful to have a way to use autocomplete in a simple say in the form fields.
I am using it taking advantage of the wonderful [react-native-autocomplete-input](https://github.com/l-urence/react-native-autocomplete-input).

I think this could just become another type of input like Textbox or Select.. this would be a good enhancement.

Some adding i have to use (see in `this.state`):
- `elements` is to store the array of objects that i need to have for the autocomplete;
- `propForQuery` is a string containing the name of the property of the elements to search by (not really used yet, it's just there);
- `didMount` is useful when i use initial values for the form, so the first time the component is mounted it use the init value and then stops using that value, or you won't be able to make further changes

But I have some warning that I cannot disarm...
## it's working but can anybody help me make it better?

here is the code so far (working for me):
#### When i build the form I use this option object
```js
const options = {
  fields: {
    name: {
      factory: AutoInput,
      config: {
        elements: this.props.objectsForAutocomplete,
        propForQuery: 'name',
      },
      label: 'Name',
    },
  },
};
```

#### Here is the AutoInput factory
```js
import React from 'react';
import { StyleSheet, View, Text, TouchableOpacity } from 'react-native';
import t from 'tcomb-form-native';
import Autocomplete from 'react-native-autocomplete-input';

const Component = t.form.Component;

class AutoInput extends Component {
  constructor(props) {
    super(props);
    this.state = {
      elements: [],
      propForQuery: '',
      query: '',
      didMount: false,
    };

    this.getTemplate = this.getTemplate.bind(this);
  }

  getLocals() {
    const locals = super.getLocals();
    const { config: { elements, propForQuery } } = locals;
    this.setState({ elements, propForQuery });
    return locals;
  }

  getTemplate() {
    return (function(locals) {
      const { query, propForQuery } = this.state;
      const elements = this.findElement(query);
      const comp = (a, b) => a.toLowerCase().trim() === b.toLowerCase().trim();

      if (!this.state.didMount) {
        const name = this.props.value;
        this.setState({ query: name, didMount: true });
        locals.onChange(name);
      }

      return (
        <View style={styles.container}>
          <Autocomplete
            autoCorrect={false}
            style={{
              backgroundColor: '#ffffff',
              borderRadius: 5,
              height: 36,
              fontSize: 17,
              padding: 7,
            }}
            inputContainerStyle={styles.inputContainerStyle}
            data={
              elements.length === 1 && comp(query, elements[0].name)
                ? []
                : elements
            }
            defaultValue={query}
            onChangeText={text => {
              this.setState({ query: text });
              locals.onChange(text);
            }}
            placeholder={locals.label}
            renderItem={({ name }) => (
              <TouchableOpacity
                onPress={() => {
                  this.setState({ query: name });
                  locals.onChange(name);
                }}
              >
                <Text style={styles.itemText}>{name}</Text>
              </TouchableOpacity>
            )}
          />
        </View>
      );
    }).bind(this);
  }

  findElement(query) {
    if (query === '' || !query) {
      return [];
    }

    const { elements } = this.state;
    const regex = new RegExp(`${query.trim()}`, 'i');
    return elements.filter(element => element.name.search(regex) >= 0);
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: '#F5FCFF',
  },
  autocompleteContainer: {
    backgroundColor: '#ffffff',
    color: '#000000',
    fontSize: 17,
    height: 36,
    padding: 12,
    borderRadius: 5,
  },
  inputContainerStyle: {
    borderRadius: 4,
    borderColor: '#cccccc',
    borderWidth: 1,
    marginBottom: 18,
  },
  itemText: {
    fontSize: 15,
    margin: 2,
  },
});

AutoInput.transformer = {
  format: value => {
    return value;
  },
  parse: value => {
    return value;
  },
};

export default AutoInput;
```

**Comment by sun2rise** [comment]
No more warning with this code

```js
import React from 'react';
import { View, Text, TouchableOpacity, InteractionManager } from 'react-native';
import t from 'tcomb-form-native';
import Autocomplete from 'react-native-autocomplete-input';

const Component = t.form.Component;

class AutoInput extends Component {
  constructor(props) {
    super(props);
    this.state = {
      elements: [],
      propForQuery: '',
      query: '',
    };
    this.localsOnChange = null;
    this.getTemplate = this.getTemplate.bind(this);

    InteractionManager.runAfterInteractions(() => {
      const locals = super.getLocals();
      const { config: { elements, propForQuery } } = locals;
      const query = this.props.value;
      this.setState({ elements, propForQuery, query });
      locals.onChange(query);
    });
  }

  getLocals() {
    return super.getLocals();
  }

  getTemplate() {
    return function(locals) {
      const { query } = this.state;
      const elements = this.findElement(query);
      const comp = (a, b) => a.toLowerCase().trim() === b.toLowerCase().trim();

      return (
        <View style={styles.container}>
          <Autocomplete
            autoCorrect={false}
            style={{
              backgroundColor: '#ffffff',
              borderRadius: 5,
              height: 36,
              fontSize: 17,
              padding: 7,
            }}
            inputContainerStyle={styles.inputContainerStyle}
            data={
              elements.length === 1 && comp(query, elements[0].name)
                ? []
                : elements
            }
            defaultValue={query}
            onChangeText={text => {
              this.setState({ query: text });
              locals.onChange(text);
            }}
            placeholder={locals.label}
            renderItem={({ name }) => (
              <TouchableOpacity
                onPress={() => {
                  this.setState({ query: name });
                  locals.onChange(name);
                }}
              >
                <Text style={styles.itemText}>{name}</Text>
              </TouchableOpacity>
            )}
          />
        </View>
      );
    }.bind(this);
  }

  findElement(query) {
    if (query === '' || !query) {
      return [];
    }

    const { elements } = this.state;
    const regex = new RegExp(`${query.trim()}`, 'i');
    return elements.filter(element => element.name.search(regex) >= 0);
  }
}

const styles = {
  container: {
    flex: 1,
    // backgroundColor: '#F5FCFF',
  },
  autocompleteContainer: {
    backgroundColor: '#ffffff',
    color: '#000000',
    fontSize: 17,
    height: 36,
    padding: 12,
    borderRadius: 5,
  },
  inputContainerStyle: {
    borderRadius: 4,
    borderColor: '#cccccc',
    borderWidth: 1,
    marginBottom: 18,
  },
  itemText: {
    fontSize: 15,
    margin: 2,
  },
};

AutoInput.transformer = {
  format: value => {
    return value;
  },
  parse: value => {
    return value;
  },
};

export default AutoInput;
```

**Comment by 6624465** [comment]
Hi, I got error on  "return elements.filter(element => element.name.search(regex) >= 0);"

TypeError: elements.filter is not a function

This error is located at:
    in Component (created by Component)
    in RCTView (at View.js:113)
    in View (at struct.js:32)
    in Component (created by Form)
    in Form (at ChickenProfileDetail.js:565)
    in RCTView (at View.js:113)
    in View (at ChickenProfileDetail.js:564)
    in RCTView (at View.js:113)
    in View (at ScrollView.js:744)
    in RCTScrollView (at ScrollView.js:852)
    in ScrollView (at KeyboardAwareHOC.js:329)
    in _class (at Content.js:10)
    in Content (at connectStyle.js:384)
    in Styled(Content) (at ChickenProfileDetail.js:563)
    in RCTView (at View.js:113)
    in View (at Container.js:15)
    in Container (at connectStyle.js:384)
    in Styled(Container) (at ChickenProfileDetail.js:540)
    in ChickenProfileDetail (at SceneView.js:17)
    in SceneView (at DrawerScreen.js:21)
    in DrawerScreen (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(DrawerScreen) (at DrawerNavigator.js:71)
    in Unknown (at createNavigator.js:13)
    in Navigator (at DrawerView.js:178)
    in RCTView (at View.js:113)
    in View (at DrawerLayoutAndroid.android.js:186)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)
    in DrawerLayoutAndroid (at DrawerView.js:158)
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at Navigation.js:423)
    in Navigation (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:113)
    in View (at CardStack.js:454)
    in RCTView (at View.js:113)
    in View (at CardStack.js:453)
    in RCTView (at View.js:113)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:113)
    in View (at CardStack.js:414)
    in RCTView (at View.js:113)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at App.js:29)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:126)
    in AppContainer (at renderApplication.js:34)
