### ISSUE TITLE
Set State with modified options resets values

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#34]
I remember asking on tcomb-validation some time ago how to deal w server side exceptions and create "manual validation exceptions".

The answer was to call setState with an options object, containing the field, hasError:true and the modified validation exception message.

However, this leads to:
1. the state of the form being reset to null
2. the values of the form still being visible in the UI

I tried two things:
1. just calling setState, with the affected field. But this leads the other fields to be removed
2. calling setState with a "full" modified options object containing the affected fields, hasError:true and modified validation messages.

**Comment by gcanti** [comment]
Just added two relevant sections to the docs.

Adding a default value and listen to changes:

https://github.com/gcanti/tcomb-form-native#adding-a-default-value-and-listen-to-changes

Disable a field based on another field's value:

https://github.com/gcanti/tcomb-form-native#disable-a-field-based-on-another-fields-value
