### ISSUE TITLE
t.form.File error (Android)

### ISSUE THREAD

**Issue by LukeSolomonS** [gcanti/tcomb-form-native#346]
- tcomb-form-native v0.6.7
- react-native v0.42.3

### Expected behaviour

I'm trying to create a form with a "Upload File" field. I've seen this issue: [https://github.com/gcanti/tcomb-form/issues/112](url), and copied the _struct_ and _options_ of the form, but I get an error:

_[tcomb] Invalid argument props {
    "caption": "?String",
    "copyright": "?String",
    "reference": "?String",
    "is_video": "Boolean"
} supplied to struct(props, [options]) combinator (expected a dictionary String -> Type)_

### Steps to reproduce
I'm using an Android Virtual Device running Android 7.0, and my code is as follows (sorry, couldn't figure how to use Github's 'code' tag and mantain the readability) :

`import React, { Component } from 'react';`
`import {`
`  AppRegistry,`
`  StyleSheet,`
`  Text,`
`  View,`
`  TouchableHighlight,`
`  Platform,`
`  Alert`
`} from 'react-native';`
`import axios from 'axios';`
`const t = require('tcomb-form-native');`
`var Form = t.form.Form;`
`var Type = t.struct({`
`  caption: t.maybe(t.Str),`
 ` copyright: t.maybe(t.Str),`
`  reference: t.maybe(t.Str),`
`  file: t.form.File, // <-- your irreducible`
`  is_video: t.Bool`
`});`
`var options = {`
`  fields: {`
`    file: {`
`      type: 'file'`
`    }`
`  }`
`};`
`export default class AppVereador extends Component {       `
`    onPress = () => {`
`      var value = this.refs.form.getValue();`
`      console.log(value);`
`    }`
`    render() {`
`      return (`
`        <View style={styles.container}>          `
`          <Form`
`              ref="form"`
`              type={Type}`
`              options={options}`
`          />`
`          <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>`
`            <Text style={styles.buttonText}>Save</Text>`
`          </TouchableHighlight>`
`        </View>`
`      );`
`    }`
`}`
`const styles = StyleSheet.create({`
`  container: {`
`    flex: 1,`
`    padding: 20,`
`    backgroundColor: '#333333',    `
`  },`
`  button: {`
`    height: 36,`
`    backgroundColor: '#48BBEC',`
`    borderColor: '#48BBEC',`
`    borderWidth: 1,`
`    borderRadius: 8,`
`    marginBottom: 10,`
`    alignSelf: 'stretch',`
`    justifyContent: 'center'`
`  },`
`  buttonText: {`
`    fontSize: 18,`
`    color: 'white',`
`    alignSelf: 'center'`
`  },`
`});`
`AppRegistry.registerComponent('AppVereador', () => AppVereador);`

### Stack trace and console log

As said earlier, my console throws this error:
_[tcomb] Invalid argument props {
  "caption": "?String",
  "copyright": "?String",
  "reference": "?String",
  "is_video": "Boolean"
} supplied to struct(props, [options]) combinator (expected a dictionary String -> Type)_

Any help would be great, I really need to figure this out :/

**Comment by gcanti** [comment]
`t.form.File` doesn't exist in `tcomb-form-native`

**Comment by LukeSolomonS** [comment]
> `t.form.File` doesn't exist in `tcomb-form-native`

What?! But...but...what about the answer on the issue I mentioned? It _does_ mention `t.form.File`. Am I missing something? If that is the case, could someone point me the way?

**Comment by gcanti** [comment]
@LukeSolomonS the issue you mentioned is in the `tcomb-form` repo (the web version of this library)

**Comment by alvaromb** [comment]
Hi @LukeSolomonS!

As @gcanti said, File belongs to other repo. If you want to upload an image, I suggest to get the URI of the image file with a library with access to the camera or camera roll and then perform a multipart request with a `FormData` entity.
