### ISSUE TITLE
Using tcomb-template for TextBox as a React Component

### ISSUE THREAD

**Issue by dhavrosh** [gcanti/tcomb-form-native#359]
Hey guys,

I'm trying to use an own template for textbox.
I'd like to use React Component for it, cause i need a state for animations and when I try to export an react component from template file I got errors that this doesn't have props

Can I solve it or we just can return a simple function? Does anybody know?

**Comment by alvaromb** [comment]
Your templates can return React components. For a more advanced example, check https://github.com/APSL/react-native-floating-label
