### ISSUE TITLE
this.refs.form is undefined

### ISSUE THREAD

**Issue by varmab** [gcanti/tcomb-form-native#36]
Do you see anything wrong here?

refs is undefined.

'use strict';

var React = require('react-native');
var t = require('tcomb-form-native');
var { AppRegistry, StyleSheet, Text, View, TouchableHighlight, Component } = React;

var Form = t.form.Form;

var PaymentType = t.enums({
    M: 'Cash',
    F: 'Check'
});

var VendorNote = t.struct({
    VendorName: t.Num,
    PaymentType: PaymentType,
    PaymentAmount: t.Num,
    Notes:t.Str
});

var options = {};

class VendorNoteEntry extends Component {
    render() {
        return (
            <View style={styles.container}>

                <Form
                    ref="form"
                    type={VendorNote}
                    options={options}
                    />
                <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
                    <Text style={styles.buttonText}>Save</Text>
                </TouchableHighlight>
            </View>
        );
    }

    onPress() {
        // Getting error here
        console.log(this.refs.form.getValue());
    }
}

var styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        marginTop: 50,
        padding: 20,
        backgroundColor: '#ffffff',
    },
    title: {
        fontSize: 30,
        alignSelf: 'center',
        marginBottom: 30
    },
    buttonText: {
        fontSize: 18,
        color: 'white',
        alignSelf: 'center'
    },
    button: {
        height: 36,
        backgroundColor: '#48BBEC',
        borderColor: '#48BBEC',
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 10,
        alignSelf: 'stretch',
        justifyContent: 'center'
    }
});

module.exports = VendorNoteEntry;

**Comment by gcanti** [comment]
Same as #32

**Comment by theappgeek** [comment]
If you want to preserve Google Closure Compiler Crushing resilience, make sure to never access as a property what was specified as a string. This means you must access using this.refs['myRefString'] if your ref was defined as ref="myRefString".

**Comment by alvaromb** [comment]
How does the compiler works in a RN environment, @theappgeek? Do you have to run it first and then bundle the resulting code?
