### ISSUE TITLE
Change border color when focused?

### ISSUE THREAD

**Issue by Turkules** [gcanti/tcomb-form-native#365]
How exactly can I change the border color of a certain text input when that input is selected?

`var Form = t.form.Form;`
`var NewUser = t.struct({`
 ` name: t.String,`
`});`

    var options = {
       fields: {
          name: {
             onFocus: () => changeBorderColor()
          }
       }
    }

How can I achieve something like this ?

**Comment by Waffun** [comment]
This exists?
