### ISSUE TITLE
PropTypes / createReactClass deprecation warning

### ISSUE THREAD

**Issue by pocesar** [gcanti/tcomb-form-native#368]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.9
- react-native v0.45.1

### Expected behaviour

No warnings about deprecation

### Actual behaviour

Giving deprecation warnings

### Steps to reproduce

1. Install this module
2. Use a remote debugger

### Stack trace and console log

![image](https://user-images.githubusercontent.com/461084/27762703-5d96cf48-5e4d-11e7-8090-d6187111894c.png)

It's an easy fix though, just use `prop-types` module instead

**Comment by gcanti** [comment]
propTypes are used in the following files

- datepicker.ios.js
- select.ios.js

/cc @alvaromb

**Comment by StevePotter** [comment]
Hi, this is now broken in react 16.0.0-beta-1 released July 26.  I would be happy to submit the PR to use the separate proptypes package and not use createClass.  Would you be open to that?

**Comment by alvaromb** [comment]
Sure!

**Comment by alvaromb** [comment]
This should be fixed.
