### ISSUE TITLE
undefined is not a function (evaluating 'this._lazyCallableModules[names]()')

### ISSUE THREAD

**Issue by abdelghafourzguindou** [gcanti/tcomb-form-native#370]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.9
- react-native v0.46.1

this error was appeared in my first run with tcomb-form-native

**Comment by humblo** [comment]
Hi,

I have the same problem. Someone can help me please :)
![capture du 2017-07-11 23 25 23](https://user-images.githubusercontent.com/20171463/28089020-43f77ef2-6690-11e7-8b9b-3b66af4b5b44.png)

**Comment by zGuindouGit** [comment]
It's solved for me by changing the react-native version react-native": "0.45.0", change it in package.json and reinstall package. ;)

**Comment by pihyper** [comment]
Changing the module "babel-preset-react-native" from 2.1.0 to 2.0.0 might fix the issue

**Comment by mchandleraz** [comment]
I ran into this when converting a functional stateless component to a Class because I was referencing `props` rather than `this.props` in a couple places.
