### ISSUE TITLE
Android DatePicker shows yesterday date

### ISSUE THREAD

**Issue by xipgroc** [gcanti/tcomb-form-native#371]
### Version

- tcomb-form-native v0.6.9
- react-native v0.45.1

### Expected behaviour

When using a t.Date field in a form, the Android DatePicker should display the same day as the date in the model (regardless of the locale/timezone we are in).
When selecting a date in the picker, then the date passes though the format function and gets displayed as text, then the user clicks again in the datepicker, the date should be the same as before.

### Actual behaviour

Clicking the date opens the Android DatePicker, showing the day. Clicking on the intended date puts the selected day in the form field, then clicking again shows the day before, and if one keeps clicking and opening the datepicker again it goes always to the day before, etc.

I suppose because of the timezone UTC/GMT +2, and the date is constructed without hour/minute/seconds, the date has 00:00:00 as time and +2 as timezone, it calculates the day as being 22h of the day before.

Note this is a problem with Datepicker, not with Date Spinner. If using an Android version with Date Spinner only, it shows the correct day always.

### Steps to reproduce

```javascript
constructor(props) {
    super(props);
    this.state = {
      user: { name: "Name", birthday: new Date("1953-10-15") }
    };
  }

  render() {
    const Form = t.form.Form;
    const User = t.struct({
      name: t.String,
      birthday: t.Date
    });
    const options = {
      fields: {
        birthday: {
          config: {
            format: date => format(date, "DD-MM-YYYY")
          }
        }
      }
    };
    return <Form 
      value={this.state.user}
      onChange={user => this.setState({ user })}
      ref={component => (this.form = component)}
      type={User}
      options={options} />;
  }
```

Then click on the date, select any day or keep the selected day on the calendar, click on the date again, the day selected is the day before. To reproduce the phone might have to be on a Timezone with GTM +1 or +n days .

This is corrected if using this on datepicker.android.js:

```javascript
const localDate = locals.value || new Date();
            let config = {
              date: new Date(Date.UTC(localDate.getFullYear(), localDate.getMonth(), localDate.getDate()))
            };
```

So maybe there is something I'm missing on this, or this is a problem with the actual react android date picker, or maybe there is another way to define the date type in the form, can anyone tell me please?

Thanks!

**Comment by buraky84** [comment]
Having the same issue with React Native 0.47 & tcomb-form-native v0.6.9

**Comment by shibbyy** [comment]
+1

**Comment by ariantofedri** [comment]
if you are using simulator, please check your time zone (Setting - Date&Time). Then disable "Automatic Time Zone" and Select your actual timezone. Datepicker will show same as your day.

**Comment by xipgroc** [comment]
> if you are using simulator, please check your time zone (Setting - Date&Time). Then disable "Automatic Time Zone" and Select your actual timezone. Datepicker will show same as your day.

It does not. Even when manually selecting the time zone, it's still showing the day before each time the date picker is reopened. Note that this is only a problem using this library, when using DatePickerAndroid directly in another part of my app, the date shows correctly.

**Comment by alvaromb** [comment]
Relevant: https://github.com/gcanti/tcomb-form-native/pull/484

This is an issue with your format function, please check that you're taking into account timezones.
