### ISSUE TITLE
Create large text field to enter 300 chars or more.

### ISSUE THREAD

**Issue by Herxheimer** [gcanti/tcomb-form-native#372]
I'm trying to create a customer support form that lets a user describe the issues they are having. I'm not sure how to create a large text field in tcomb - form native similar to the image below. 
![27996618-2b25af8a-64b4-11e7-9a2a-f76ce31fc93d](https://user-images.githubusercontent.com/25973054/28021345-89db1f8c-6555-11e7-9108-8203da2419e6.png)

 I tried the code below, but it is not working....

     const tcombForm = t.struct({
      test: t.String
        })

     const options = {
       fields: {
         test: {
           type: 'textarea',
             attrs: {
               rows: 20
            }
         }
       }
     }

**Comment by vendramini** [comment]
There's a multiline options plus number of rows. Read the docs, bro =)

**Comment by tommymcdonald** [comment]
```
const t = require('tcomb-form-native');
const Form = t.form.Form;

const options = {
    fields: {
        multiline: true,
        stylesheet: {
            ...Form.stylesheet,
            textbox: {
                ...Form.stylesheet.textbox,
                normal: {
                    ...Form.stylesheet.textbox.normal,
                    height: 150
                },
                error: {
                    ...Form.stylesheet.textbox.error,
                    height: 150
                }
            }
        }
    }
}
```

Adjust height as necessary, but like vendramini said, this is a real RTFM thing.

**Comment by ArneMis** [comment]
there is a multiline option indeed, but the default height on the textbox breaks the multiline option. 

If you put multiline and numberOfLines=4, it will still render one line because of the fixed height of 36 in de default styles. 

So you need to overwrite the height like the example above. But can you point out where this height thing is mentioned in the docs? 

Kind regards
