### ISSUE TITLE
Not returning value from form for custom template

### ISSUE THREAD

**Issue by anoopmm** [gcanti/tcomb-form-native#373]
`
import React, { Component } from 'react';
import { Image, StyleSheet, Dimensions, Platform, Button,TextInput } from 'react-native';
import { connect } from 'react-redux';
import { Container, Text, View, Content, Icon } from 'native-base';
import t from 'tcomb-form-native';

import { pushNewRoute } from '../../actions/route';
import { changeTab } from '../../actions/tab';

const bckImg = require('../../../images/bck.jpg');

const Form = t.form.Form;
const deviceHeight = Dimensions.get('window').height;
const devicewidth = Dimensions.get('window').width;
const styles = StyleSheet.create({
  backGround: {
    width: devicewidth + 2,
    height: Platform.OS === 'ios' ? deviceHeight : deviceHeight - 24,
    backgroundColor: '#fff',
  },
  container: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  shadow: {
    width: devicewidth + 2,
    height: Platform.OS === 'ios' ? deviceHeight : deviceHeight - 24,
    backgroundColor: '#fff',
  },
  bg: {
    flex: 1,
    // bottom: 16,
  },
  bg2: {
    flex: 2,
    // bottom: 16,
  },
  forgotPassword: {
    color: 'black',
    fontSize: 12,
    fontWeight: '100',
  },
  loginText: {
    color: 'black',
    fontSize: 26,
    lineHeight: 26,
    fontWeight: '600',
    alignSelf: 'center',
    marginBottom: 16,
  },
  formView: {
    flex: 1,
    justifyContent: 'center',
    paddingLeft: 32,
    paddingRight: 32,
    paddingTop: 8,
    paddingBottom: 8,
    marginTop: -56,
  },
  firstscreen: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#f0f0f0',
  },
  topImg: {
    height: 80,
    padding: 10,
    margin: 20,
    marginLeft: 10,
    alignSelf: 'center',
  },
  linkView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },

});

const LoginForm = t.struct({
  email: t.String,
});

class Login extends Component {

  static propTypes = {
    pushNewRoute: React.PropTypes.func,
    isFetching: React.PropTypes.bool,
    doLogin: React.PropTypes.func,
  }
  myCustomTemplate( locals ) {
    const FormTemplatetyles = {
      section: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        margin: 10,
      },
      searchIcon: {
        padding: 10,
      },
      input: {
        flex: 1,
        paddingTop: 10,
        paddingRight: 10,
        paddingBottom: 10,
        paddingLeft: 0,
        backgroundColor: '#fff',
        color: '#424242',
      },
    };

    return (
      <View>
        <Text>{locals.label}</Text>
        <TextInput />
      </View>
      // <View style={FormTemplatetyles.section}>
      //   <Icon style={FormTemplatetyles.searchIcon} name="ios-search" size={20} color="#000" />
      //   <TextInput
      //     style={FormTemplatetyles.input}
      //     placeholder="User Nickname"
      //     underlineColorAndroid="transparent"
      //   />
      // </View>
    );
  }
  state = {
    value: {
    },
    options: {
      fields: {
        email: {
          template: this.myCustomTemplate,
        },
      },
    },
  };

  onChange(value) {
    this.setState({
      value,
    });
  }
  pushNewRoute(route) {
    this.props.pushNewRoute(route);
  }
  submitLogin() {
    const value = this.formRef.getValue();
    console.log(value);
    if (value) {
      this.props.doLogin(value);
      // this.props.doAdminLogin();
    } else {
      const errorObj = this.formRef.validate();
      console.log('erroe',errorObj);
    }
  }

  renderForm() {
    return (
      <View style={styles.formView}>
        <Text
          style={styles.loginText}
        >
          Login
        </Text>
        <Form
          ref={(ref) => {
            this.formRef = ref;
          }}
          type={LoginForm}
          options={this.state.options}
          value={this.state.value}
          onChange={value => this.onChange(value)}
        />
        {/* Wrapper for signup/reset password Link */}
        <View style={styles.linkView}>
          <Text style={styles.forgotPassword} onPress={() => this.pushNewRoute('forgotPassword')} >
              forget
          </Text>
          <Text
            style={styles.forgotPassword}
            onPress={() => this.pushNewRoute('register')}
          >
            register
          </Text>
        </View>
        {/* Redwine Login Button */}
        <Button
          title='test'
          loading={this.props.isFetching}
          onPress={() => this.submitLogin()}
        />
      </View>
    );
  }
  renterAPPName(){
    return(
      <View style={styles.firstscreen}>
        <Text
          style={{ fontSize: 30, color: '#4c4c4c', alignSelf: 'center' }}
        >
          TESZT
        </Text>
      </View>
    );
  }
  render() {
    return (
      <Image source={bckImg} style={styles.backGround}>
      <Container >
        <Content style={styles.container}>
          <View style={styles.shadow}>
            <View style={styles.bg}>
              {this.renterAPPName()}
            </View>
            <View style={styles.bg2}>
              {this.renderForm()}
            </View>
          </View>
        </Content>
      </Container>
    </Image>
    );
  }
}

const bindActions = dispatch => ({
  pushNewRoute: route => dispatch(pushNewRoute(route)),
  changeTab: tab => dispatch(changeTab(tab)),
});

const mapStateToProps = state => ({
  auth: state.auth,
  isFetching: state.auth.isFetching,
});

export default connect(mapStateToProps, bindActions)(Login);
 ##`

**Comment by iiitmahesh** [comment]
@anoopmm Please put your code in `Insert code `tags...! difficult to follow long code with any description.
