### ISSUE TITLE
QUESTION: Format for TextField

### ISSUE THREAD

**Issue by imalik8088** [gcanti/tcomb-form-native#381]
Hi there, 
I have a general question. I want to submit a time formatted like `HH:SS` in a TextField and didn't find any documentation about that. 

<img width="220" alt="bildschirmfoto 2017-08-02 um 13 07 49" src="https://user-images.githubusercontent.com/566286/28871153-9c49dd76-7783-11e7-91df-7381cedb5e58.png">

This my web application for that I want to build a App tcomb-form-native.

How can I achieve this behavior?

**Comment by vendramini** [comment]
https://gist.github.com/sibelius/c564ded5bfd39534cf035e0460f2ee9a

Do you want this? A mask?
