### ISSUE TITLE
Checkbox and Radio Buttons Support

### ISSUE THREAD

**Issue by eliehamouche** [gcanti/tcomb-form-native#385]
Has anyone been able to implement a classic checkbox and radio type input fields with tcomb?
I find the ios Switch and pickers to be a bit ugly.

If not can someone give me some guidelines on how to implement them as custom components? The documentation is a bit convoluted.

Thanks

**Comment by alvaromb** [comment]
You could provide custom factory for that: https://github.com/APSL/react-native-floating-label

Radio buttons and checkbox are not present by default in the React Native API, so they will not be included in this lib.
