### ISSUE TITLE
Hiding a nested t.struct

### ISSUE THREAD

**Issue by gmelnick** [gcanti/tcomb-form-native#386]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.8
- react-native v0.44.0

### Expected behaviour

I'm making a complex form with nested sections, each of which is a t.struct full of other fields. For example, my overall structure looks something like this:

```javascript
const Page = t.struct({
    date: t.Date,
    section1: t.struct({
        name: t.String,
        favoriteThing: t.String,
        otherFavoriteThing: t.String
    })
    hideSection1: t.Boolean
})
```

The section struct is rendered simply as a title, all the questions within it, and then a horizontal line.

I want the entire section (title, questions, and line) to be hidden when the hideSection1 boolean is true.

### Actual behaviour

 I can successfully give "section1" the option {hidden: true}, but nothing happens. If I directly give a different field the same option, it is hidden.

Is there a way to accomplish this, or are t.struct's un-hidable right now?

**Comment by vendramini** [comment]
Use templates then you can achieve this easily. Maybe this feature is not implemented.
