### ISSUE TITLE
textinput onKeyPress/onChange key code?

### ISSUE THREAD

**Issue by Monsta1000** [gcanti/tcomb-form-native#390]
### Version

Tell us which versions you are using:

- tcomb-form-native Latest
- react-native Latest

### Expected behaviour

Hello, 

I'm trying to get the key code pressed on textinput.
Any suggestion on how to to do that?

Thanks

**Comment by alvaromb** [comment]
Use text input `option`s https://github.com/gcanti/tcomb-form-native#other-standard-options
