### ISSUE TITLE
disable some days in datepicker

### ISSUE THREAD

**Issue by AITSco** [gcanti/tcomb-form-native#391]
### Version

Tell us which versions you are using:
latest version
- tcomb-form-native v0.?.?
- react-native v0.?.?

### Expected behaviour
i want to disable weekends in datepicker for both android & IOS

Tell us what should happen
send array of days to be disabled
### Actual behaviour
i couldn't find this property
Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by alvaromb** [comment]
Upstream issue.
