### ISSUE TITLE
placeholder color is wrong when set TextInput to mutliline= true

### ISSUE THREAD

**Issue by RyanWan** [gcanti/tcomb-form-native#392]
![aug 23 2017 01-28-25](https://user-images.githubusercontent.com/16396162/29600207-29c8b4e0-8807-11e7-8382-f9e06552e17d.png)
 As illustrated in the picture, the above TextInput has multiline set to true, and the below one is false

**Comment by jsina** [comment]
how could we change the textbox as a multiline?

**Comment by RyanWan** [comment]
you can add `multiline = true` in field options

**Comment by RyanWan** [comment]
I think it's a trivial bug, you can set placeholderTextColor to fix the problem. So I close this issue.
