### ISSUE TITLE
How to set default value to date

### ISSUE THREAD

**Issue by abdelghafourzguindou** [gcanti/tcomb-form-native#394]
I stock my date to data base like this `'MM-DD-YYYY hh:mm:ss'` but when I'm trying to select this date and set It into a date field form this error was appear `'Invalid date'`

```
const dateField= t.struct({
    date1: t.maybe(t.Date),
    date2: t.maybe(t.Date)
});
```
```
const defaultValue = {
 date1: select_from_table_date1,
 date2: select_fromtable_date2
}
```

the select work without problem and I show It by console.log, the result like this `'MM-DD-YYYY hh:mm:ss'`

**Comment by vendramini** [comment]
Try https://momentjs.com/
There's no relation with this lib.

**Comment by ishigamii** [comment]
Had the same problem and solved it by setting a default value to the date 
Considering I have : 
````
var CreateAccount = t.struct({
  birthDate: t.Date,
});

var maxDate = new Date();
maxDate.setFullYear(maxDate.getFullYear()-18);

var createOptions = {
  auto: 'placeholders',
  fields: {
    birthDate: {
      config: {
        format: (date) => moment(date).format('DD/MM/YYYY'), 
      },
      maximumDate: maxDate,
      mode: 'date',
      blurOnSubmit: true
    }
  }
}
````

`this.createValue = {'birthDate': myDate};`

And setting it as default value 
````
<Form
            ref="formCreate"
            type={CreateAccount}
            options={createOptions}
            value={this.createValue}
            onChange={(value) =>  this.createValue = value}/>
````

Hope it helps

**Comment by nhmasum** [comment]
@ishigamii, why this is showing error "moment is not defined"?

**Comment by ishigamii** [comment]
@nhmasum cause you need to install moment via npm and then import it 
`import moment from 'moment';`

**Comment by kkrishnan90** [comment]
@ishigamii  Thanks for your input. Could you please tell me what's the date format you chose to set ```myDate``` variable ? I tried everything from ISOString(), to UTC, etc. Nothing works. 
I am set default values for inputs but not the dates. 
I have my dates coming from server in the ```DD/MM/YYYY``` format. I am using ```moment``` but not able to set the date when I set the value when the component loads. 
Awaiting your response. Thanks in advance !

**Comment by ishigamii** [comment]
@kkrishnan90 sorry bad copy paste, `myDate` is `maxDate`

**Comment by kkrishnan90** [comment]
Yeah okie. Got it. Thanks @ishigamii

**Comment by Mogust** [comment]
thanks @ishigamii  it solve my problem, thank youuu arigatou

**Comment by bhavana-jain** [comment]
Hi, am trying to use datetime picker. however i need only a single placeholder together. however it shows two placeholders.. tap to select date and tap to select time
pls help
