### ISSUE TITLE
User needs to press twice for login submission when keyboard is open

### ISSUE THREAD

**Issue by AlmogRnD** [gcanti/tcomb-form-native#398]
### Version

"react-native": "0.47.2",
"tcomb-form": "^0.9.17",

I have a login form that has username input, log in input and submit button when a user press on the submit the keyboard closed and then they have to press the button again, it should just sumbit the form i.e run the onpress event  

Can this be fixed?

**Comment by alvaromb** [comment]
This is an upstream issue, probably related to the configuration of your container scroll view.
