### ISSUE TITLE
Password field type?

### ISSUE THREAD

**Issue by timdoes** [gcanti/tcomb-form-native#4]
Awesome plugin!

Is there a way to set a field type as password so the characters become dotted out and not viewable while typing?

Thanks,
-Tim

**Comment by gcanti** [comment]
It will lend soon: `secureTextEntry` https://github.com/facebook/react-native/pull/265

**Comment by timdoes** [comment]
Is my structure or syntax incorrect for this?

var options = {
  fields: {
    password: {
      password: true,
      secureTextEntry: true,
    }
  }
};

**Comment by gcanti** [comment]
It seems ok. This is my test case and it works (tcomb-form-native v0.1.6, **react-native v0.3.4**):

```js
var Type = t.struct({
  password: t.Str
});

var options = {
  fields: {
    password: {
      password: true,
      secureTextEntry: true
    }
  }
};

var AwesomeProject = React.createClass({

  onPress: function () {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render: function() {
    return (
      <View style={styles.container}>
        <Form
          ref="form"
          type={Type}
          options={options}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```

**Comment by fedecaccia** [comment]
which is the 'password' option used for? is not enough with secureTextEntry?
