### ISSUE TITLE
Model first field is not listed in the form data

### ISSUE THREAD

**Issue by jhon312020** [gcanti/tcomb-form-native#401]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.?.? - 0.6.9
- react-native v0.?.? - 0.47.0

### Expected behaviour

Model Structure
t.struct({
  name: t.String,              // a required string
  surname: t.maybe(t.String),  // an optional string
  age: t.Number,               // a required number
  rememberMe: t.Boolean        // a boolean
});
![appeared](https://user-images.githubusercontent.com/533369/30752395-caee4f94-9fd9-11e7-832c-adca1b7ec341.png)

### Actual behaviour

As per the actual screen there must be a name field on the form.  But it doesn't appear.

**Comment by alvaromb** [comment]
Check that it's not behind the navigation bar.
