### ISSUE TITLE
No style applied to Date

### ISSUE THREAD

**Issue by YasirPanjsheri** [gcanti/tcomb-form-native#402]
I am using tcomb in react native app
### Expected behaviour

Date supposed to have style applied to it

### Actual behaviour
There is no style shown.. I also tried to override stylesheet , but it seems that styles do not apply

![date](https://user-images.githubusercontent.com/12644122/30845330-21a0ace4-a2a8-11e7-86a6-f52f1ed18c0d.png)

Code snippet
```
const Form = t.form.Form;

Form.stylesheet.datepicker.normal.marginBottom = 20; // Not working , no changes applied
Form.stylesheet.datepicker.normal.borderColor = '#000';  // Not working as well
 
const formRegistration = t.struct({
    // other fields
    birthDate: t.maybe(t.Date)
});
const options = {
    fields: {
        birthDate : {
              label: 'Birth Date',
              mode: 'date',
              config: {
                   format: (date) => myDateFormat('LL', date)
             }
         }
     }
 };
```

**Comment by jlsuarezs** [comment]
I have the same issue, any help?

Thanks in advance.

**Comment by YasirPanjsheri** [comment]
@jlsuarezs Yes I found the solution... Looking at this: https://github.com/gcanti/tcomb-form-native/blob/master/lib/stylesheets/bootstrap.js 
The style for the date is in `dateValue` at line 196

so this is what I did to style it
```
const Form = t.form.Form;

Form.stylesheet.dateValue.normal.borderColor = '#d0d2d3';
Form.stylesheet.dateValue.normal.backgroundColor = '#f0f1f1';
Form.stylesheet.dateValue.normal.borderWidth = 1;
```
you follow the same way to style other components in tcomb (e.g: labels: `Form.stylesheet.controlLabel.normal.fontSize = 14;`)
