### ISSUE TITLE
ref is always undefined

### ISSUE THREAD

**Issue by jonatasdaniel** [gcanti/tcomb-form-native#405]
- tcomb-form-native v0.6.10
- react-native v0.48.4

I have my form:
`<Form
            ref={form => {
              this.form = form;
            }}
            type={Patient}
            options={options}
            styles={styles.form}
          />`

and my button:
`<MyCustomButton label="CREATE" onPress={this.onPress} />`
`onPress() {
    var value = this.form.getValue();
    if (value) {
      console.log(value);
    }
  }`

but when I click on my button `this.form` is always undefined.

What am I doing wrong?
Is this the correct way to do it?

**Comment by zorobabel** [comment]
@jonatasdaniel I have the same proble, It's driving me crazy, how did you fixed it?

**Comment by zorobabel** [comment]
Solution:

#356
