### ISSUE TITLE
Validation settings in case of  custom template 

### ISSUE THREAD

**Issue by sajjidakr** [gcanti/tcomb-form-native#407]
### Version
- tcomb-form-native v0.6.10
- react-native v0.45

### Expected behaviour
I am using custom template locally in a file in order to add a vector icon in an input field. But my validations stopped working ... 

### Actual behaviour
Only design should impact other than that functionality should work as it is

**Comment by alvaromb** [comment]
Please post your template code to see if there's something missing there.

**Comment by rohitpotato** [comment]
How did you resolve this?
