### ISSUE TITLE
placeholders for string and number type fields but labels for dates

### ISSUE THREAD

**Issue by pgmemk** [gcanti/tcomb-form-native#41]
```
options: {
  auto: 'placeholders'
}
```
It looks great with placeholders BUT **date** type fields are loosing their label and there is no way to identify them

Is it possible to add **auto** option override for specific field something like this for example
```
options: {
  fields: {
     expires: {
        auto: 'labels' 
    }
  }
}
```
or ignore placeholders setting for dates alltogether

**Comment by gcanti** [comment]
> Is it possible to add auto option override for specific field

Sure

**Comment by gcanti** [comment]
Just published v0.2.3 with a fix

**Comment by pgmemk** [comment]
Thank you :)

On Thu, Jul 23, 2015 at 12:25 PM, Giulio Canti <notifications@github.com>
wrote:

> Just published v0.2.3 with a fix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gcanti/tcomb-form-native/issues/41#issuecomment-124158721>
> .
>



-- 
Ellen Katsnelson
Lead Developer

**Comment by pgmemk** [comment]
The new feature that overrides auto for specific field does not work for
enums.


On Thu, Jul 23, 2015 at 1:49 PM, Ellen Katsnelson <
ellen.katsnelson@lablz.com> wrote:

> Thank you :)
>
> On Thu, Jul 23, 2015 at 12:25 PM, Giulio Canti <notifications@github.com>
> wrote:
>
>> Just published v0.2.3 with a fix
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gcanti/tcomb-form-native/issues/41#issuecomment-124158721>
>> .
>>
>
>
>
> --
> Ellen Katsnelson
> Lead Developer
>
>


-- 
Ellen Katsnelson
Lead Developer

**Comment by gcanti** [comment]
Could you elaborate a little bit on your issue?
I tested the following snippet and it works as expected

```js
var Countries = t.enums.of('IT US');

var FormType = t.struct({
  name: t.Str,
  country: Countries
});

var options = {
  auto: 'placeholders',
  fields: {
    country: {
      auto: 'labels'
    }
  }
};
```

I see "Name" as placeholder of the textbox and "Country" as label of the select

**Comment by pgmemk** [comment]
Works great. I had a typo error for 'labels' that I could not see :)

I have a different problem though.

I have

    var currency = t.enums({
      USD: '$',
      GBR: '£',
      CNY: '¥'
    });

    var money = t.struct({
       value: t.Num,
       currency: currency
    });

And then I have

  var options = {
     auto: 'placeholders'
  }

  var model = t.struct({
     price: money
  });

The label for the '*price*' field is not showing.
How do I assign *auto: 'labels'* (or any other option) for sub-struct?

I tried to do something like

var options = {       // this is for the parent struct
   auto: 'placeholders'
   price: {
      options: {
         value: 'labels'
      }
   }
}
and it didn't work.

[image: Inline image 4]

**Comment by gcanti** [comment]
Nested forms are not well supported at the moment (I'll try to add support for nested forms as soon as I find the time). In the meanwhile is it an option flattening the fields of your form?

**Comment by pgmemk** [comment]
I tried with specific options for sub-struct and without and they did not
change the way sub-struct fields were displayed.

I found temporary work around for the case I needed sub-struct for for now
:) just using the t.Str instead of sub-struct and putting logic in a
description and onSubmit.

There is some strange behavior with date types and enums (anything that is
displayed as a picker). When you set value in it and then focus in some
other non-picker field for example text field the value in the picker gets
reset to the original value



On Tue, Jul 28, 2015 at 11:15 AM, Giulio Canti <notifications@github.com>
wrote:

> Nested forms are not well supported at the moment (I'll try to add support
> for nested forms as soon as I find the time). In the meanwhile is it an
> option flattening the fields of your form?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gcanti/tcomb-form-native/issues/41#issuecomment-125647919>
> .
>



-- 
Ellen Katsnelson
Lead Developer

**Comment by gcanti** [comment]
Weird, if you can put up a gist containing a minimal test case reproducing that strange behavior, I can try to help you out. Anyway, in case your form is re-rendered for some reason, this can be helpful:
https://github.com/gcanti/tcomb-form-native#adding-a-default-value-and-listen-to-changes
(i.e. when a form is re-rendered you must handle the `value` and `onChange` props)
