### ISSUE TITLE
Form doesn't show up in iOs release build

### ISSUE THREAD

**Issue by enguerranws** [gcanti/tcomb-form-native#412]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.10
- react-native v0.48.3

### Actual behaviour

When I run my app in dev mode, everything is fine, when I run the release build, in Simulator or in device.

Any things to consider before building to release?

**Comment by alvaromb** [comment]
Nope, should work everything. Please send us an example if it's still happening.
