### ISSUE TITLE
Bad styles for enum type between iOS / Android

### ISSUE THREAD

**Issue by outaTiME** [gcanti/tcomb-form-native#417]
Hi guys, 
I'm using a simple form with an enum type and it renders different in iOS / Android (I know it's a different component).  

1. Picker height is 44px and marginBottom is 4px when it should be 36px  as all textinputs and 5px (respectively) 
2. Border is hidden in Android (I assume it's a theme of android's own customization) why not look for an alternative option like a placeholder picker (NativeBase) to preserve compatibility on both devices.

Here is a side by side comparison:

<img width="1055" alt="screen shot 2017-10-23 at 11 51 15" src="https://user-images.githubusercontent.com/140472/31914154-f4dce212-b81f-11e7-9600-63507b9abd79.png">

For the first item I solved customizing the styles:

```js
stylesheet: {
  ...Form.stylesheet,
  pickerContainer: {
    ...Form.stylesheet.pickerContainer,
    normal: {
      ...Form.stylesheet.pickerContainer.normal,
      marginBottom: 5,
    },
    error: {
      ...Form.stylesheet.pickerContainer.error.normal,
      marginBottom: 5,
    }
  },
  pickerTouchable: {
    ...Form.stylesheet.pickerTouchable,
    normal: {
      ...Form.stylesheet.pickerTouchable.normal,
      height: 34 // took borderWidth
    },
    error: {
      ...Form.stylesheet.pickerTouchable.error,
      height: 34 // took borderWidth
    }
  }
}
```

**Comment by Metroxe** [comment]
is there a solution for the number 2 item?

>2. Border is hidden in Android (I assume it's a theme of android's own customization) why not look for an alternative option like a placeholder picker (NativeBase) to preserve compatibility on both devices.

**Comment by alvaromb** [comment]
Default styles are default values just to be able to run and visualize the form. Everybody should drop their custom styles for any kind of app, but if you feel they should be changed please send us a PR :)
