### ISSUE TITLE
When custom label no i18n optional text added

### ISSUE THREAD

**Issue by outaTiME** [gcanti/tcomb-form-native#418]
Hi guys, 
When i add an custom label for field the i18n optional text is not applied. Should it not be applied? otherwise you would have to add the "optional" text to each of the fields manually regardless of the definition of the model.

Here the getLabel method:
https://github.com/gcanti/tcomb-form-native/blob/master/lib/components.js#L153

**Comment by karlguillotte** [comment]
I have the same issue!
