### ISSUE TITLE
Better pickers for enums & dates

### ISSUE THREAD

**Issue by outaTiME** [gcanti/tcomb-form-native#423]
Hi guys, it will awesome to take pickers like this for component rendering normalization between iOS and Android, here a few ideas:

https://github.com/markuswind/react-native-select-input-ios
https://github.com/xgfe/react-native-datepicker

In iOS those components comes from bottom with modal half-size, in Android uses modal dialogs, this facilitates styling issues and fits perfectly to both devices ... 

Thanks !!!

**Comment by alvaromb** [comment]
Hi @outaTiME! Thanks for these wonderful examples. @gcanti's goal is to not have any other external dependencies for this library. However, you could provide specific templates or factories, just like here https://github.com/APSL/react-native-floating-label, with those date inputs included.

**Comment by Dannnyho** [comment]
thanks for the sharing, can show me the way to implement custom picker for tcomb-form?
