### ISSUE TITLE
add support for nested forms

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb-form-native#43]

**Comment by whokilledtheelectricmonk** [comment]
Would this allow creating forms from structs with nested objects?

**Comment by gadiel** [comment]
any news for this feature?

**Comment by gcanti** [comment]
Hi,
Working on this right now...

> Would this allow creating forms from structs with nested objects?

Yep!

**Comment by gcanti** [comment]
Released in [v0.3.1](https://github.com/gcanti/tcomb-form-native/releases/tag/v0.3.1)
