### ISSUE TITLE
testIDs missing from fields

### ISSUE THREAD

**Issue by StevePotter** [gcanti/tcomb-form-native#432]
We have a comprehensive test system that relies on test IDs.  So, for example, we cannot tell it to press a checkbox due to lack of test ID.  Right now I can work around it by customizing the templates but that shouldn't be necessary.

### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.11
- react-native v0.50.2

### Expected behaviour
Adding a test ID to a field options should put the test ID on the input field

### Actual behaviour
TestIDs are ignored

### Steps to reproduce

1. Put testID in an input field
2. Put a debugger on a template
3. Notice testID is never addressed

The answer would be to modify templates to support test IDs.  For now I have to use custom templates.  I would be happy to submit a PR for this.  Would you accept it?

**Comment by LuisRizo** [comment]
I can confirm that any option that is not recognized by the library is simply ignored and not passed to the templates. I tried with iconNames and other names.

```
options = {
  templates: InputRow,
  fields: {
    name: {
      label: 'First Name',
      userField: 'fname', //This field is not passed to InputRow
      iconName: 'ios-person', //Same for this one
    },
 ...
}
```

**Comment by StevePotter** [comment]
Yeah @LuisRizo we ended up having to customize the templates to include the testID.  @alvaromb @gcanti you appear to be the main contributors.  Our organization uses testID for our testing system and we'd like to see testID support built into the library.  I would be happy to personally write  the PR for this but I don't want to waste my time.  If I submitted a PR that added testID support, would you accept it (provided it was up to standards of course)?

**Comment by gcanti** [comment]
@StevePotter I just did the initial porting from tcomb-form, however I'm not a mobile developer so I can't maintain this library anymore. 

> I would be happy to personally write the PR

And I would be happy to add you as a collaborator

@alvaromb?

**Comment by alvaromb** [comment]
I will gladly review the PR!

Sorry about the lack of response but I've been out of Github for a several weeks trying to recover from "maintainer burnout" :)

**Comment by LuisRizo** [comment]
Suggested workaround

```
fieldProps: {
  name: {
    userField: 'fname',
    iconName: 'ios-person',
    testId: 123
  }
}
options = {
  fields: {
    name: {
      label: 'First Name',
      template: (t) => InputRow({...t, ...fieldProps.name}), //InputRow (React Component) now has the regular locals and iconName, testId and any other field passed.
    },
 ...
}
```

**Comment by alvaromb** [comment]
Please send a PR for this.
