### ISSUE TITLE
borderBottomColor

### ISSUE THREAD

**Issue by mschipperheyn** [gcanti/tcomb-form-native#44]
I'm trying to style the border of text fields more "material design" style. However, specifying borderBottomColor, etc doesn't seem to be working. Any suggestions?

**Comment by gcanti** [comment]
Duplicated?

https://github.com/gcanti/tcomb-form-native/issues/37

**Comment by alvaromb** [comment]
You can change the parent ``<View />`` of the text input and add the border there. I've done this with a custom stylesheet:

```js
formGroup: {
    normal: {
      marginBottom: 10,
      paddingTop: 20,
      borderBottomColor: 'gray',
      borderBottomWidth: 1,
    },
    error: {
      marginBottom: 10
    }
  },
```
