### ISSUE TITLE
How to change boolean button color

### ISSUE THREAD

**Issue by fithaN** [gcanti/tcomb-form-native#445]
How to change the color of the boolean button from green to something else

**Comment by jovanxua** [comment]
In the documentation, following options are supported for Switch:
disabled
onTintColor
thumbTintColor
tintColor

However, if you set thumbTintColor with a static color, thumbTintColor in both on and off status will have the same color.

I will try to help you create a dynamic one.

Example:

OFF:
![image](https://user-images.githubusercontent.com/26292093/35313076-6bfe0962-00f9-11e8-82b4-fe787182faf2.png)

ON:
![image](https://user-images.githubusercontent.com/26292093/35313088-78eb93f6-00f9-11e8-9e76-b4a6a5efa991.png)

1. Set-up your struct
let TestStruct= t.struct({
  testSwtitch: t.Boolean
});

2. Create your form
<Form 
              ref='form'
              type={TestStruct} 
              value={this.state._value}
              onChange={this.onChange}
              options={options}
/>

3. Create your initial
constructor(props){
    super(props);
    this.state={
      _value: null,
      _thumbColor: 'blue'
    }
  }

4. Set-up your field options (Under render function)
let options = {
      fields: {
        testSwtitch:{
          onTintColor: "yellow",
          tintColor: "black",
          thumbTintColor: this.state._thumbColor,
        }
      }
    };    

5. Lastly, create onChange function to listen to switch value
  onChange = (value) => {
    if(value.testSwtitch){
      this.setState({_value: value, _thumbColor: 'red'});
    }
    else{
      this.setState({_value: value, _thumbColor: 'blue'});
    }
  }

:)
