### ISSUE TITLE
ios - change datepicker calendar type

### ISSUE THREAD

**Issue by muthuraman007** [gcanti/tcomb-form-native#446]
### Version

- tcomb-form-native v0.6.7
- react-native v0.50

### Expected behaviour
Tcomb form with date field. Need to change the calendar type  to chinese, buddhist,gregorian.
If i set calendar to type= **chinese**, need to display that chinese calendar when i click on tcomb date component.

### Actual behaviour
Instead of displaying that chinese calendar. it display the normal calendar

### Steps to reproduce

1. Create Tcomb form
2. Add  date field
3. set calendar = 'chinese'

**Comment by muthuraman007** [comment]
@gcanti @alvaromb  Need your help

**Comment by alvaromb** [comment]
Sorry, cannot see any 'chinese' option here http://facebook.github.io/react-native/docs/datepickerios.html, which is what this library uses.
