### ISSUE TITLE
Add required field additional string

### ISSUE THREAD

**Issue by hrlarsen** [gcanti/tcomb-form-native#46]
Would like to see that required fields may also hold an additional string like optional have " (optional)".

Alterations to index.js:

t.form.Form.i18n = {
  optional: ' (optional)',
  required: ''
};

Alterations to components.js

line 100: return ctx.label + (this.typeInfo.isMaybe ? this.getI18n().optional : this.getI18n().required);

**Comment by gcanti** [comment]
Good idea :+1:

**Comment by gcanti** [comment]
Do you want to submit a PR?

**Comment by hrlarsen** [comment]
Naa, if you just add it, I'm happy
