### ISSUE TITLE
Is there any stable version for react-native: 0.50.0 and grater ?

### ISSUE THREAD

**Issue by skjangid** [gcanti/tcomb-form-native#461]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.?.?
- react-native v0.?.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by skjangid** [comment]
I am using "npm install tcomb-form-native" and error is bellow

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!

my react native version is 
react-native-cli: 2.0.1
react-native: 0.51.0

**Comment by arnoldbird** [comment]
My versions are working...

react-native 0.54
tomb-form-native ^0.6.11

I'm using the expo SDK v26, which incorporates react-native 0.54.

**Comment by alvaromb** [comment]
Currently using this lib with 0.55. Please try to reinstall your deps.
