### ISSUE TITLE
t.Str with default value not editable

### ISSUE THREAD

**Issue by hrlarsen** [gcanti/tcomb-form-native#47]
Hi

I currently have a form in which I fill in information from the beginning, because I use it like a "edit" tool. But I found that when a form is created with a t.Str the value is not editable! When typing, the value resets back to the value set at the beginning, though the value given by both onChange callback and by getValue() has changes (though only those within the last frame). But this is not the case if the field is optional, then everything works fine.

recreate :
```javascript
var Person = t.struct({
  name: t.Str,              // a required string
  otherName: t.maybe(t.Str)
});


var Test = React.createClass({
  getInitialState: function() {
    return{
      value:{name:'test', otherName:'test'}
    }
  }

  render: function(){
  console.log("Render ", this.state.value);
    <Form
    ref="form"
    type={Person}
    value={this.state.value}
    onChange={this.onChange}
     />
  },

  onChange: function(value)
    {
        console.log("OnChange ", value);
        this.setState({value: value});
    }
});
```

**Comment by gcanti** [comment]
Weird. Which version of react-native are you using?

**Comment by hrlarsen** [comment]
0.9.0

**Comment by gcanti** [comment]
Just published v0.2.5 (upgrade to react-native v0.9), could you please verify if your issue is fixed?

**Comment by hrlarsen** [comment]
I can confirm that the issue is fixed, thanks!

**Comment by gcanti** [comment]
Great, thanks for your feedback
