### ISSUE TITLE
Adding onValueChange option for Select component and onDateChange option for DatePicker component

### ISSUE THREAD

**Issue by Cassendra4** [gcanti/tcomb-form-native#478]
### Version

Tell us which versions you are using:

- tcomb-form-native : ^0.6.11
- react-native : 0.52.0

### Expected behaviour

I need to store the data in AsyncStorage after user selects an item from the select component and a date from the DatePicker component before submitting the form. 

### Actual behaviour

There is no way to reach the above-expected behavior just like onEndEditing option in TextInput

### Steps to reproduce

1. Add a DatePick Component and a Select Component
2. Try to retrieve the value inserted by the user before submitting the form.

**Comment by ltankey** [comment]
What stops you simply looking at what's changing in `onChange` that you supply to the Form?

**Comment by Cassendra4** [comment]
@ltankey, what I'm trying to do here is get the values as they enter and store them to `Asyncstorage`.  `onChange` can't be used in this case as the form is not submitted yet.

**Comment by ltankey** [comment]
`onChange` fires on input change, which includes when a user selects something from a select box or date field. The default select widget does not auto-collapse -- perhaps this is what you mean? You can change the template used for select boxes (i.e. [a modal selector](https://github.com/peacechen/react-native-modal-selector)) if you don't want the widgets to remain open.

**Comment by alvaromb** [comment]
You should use the `getValue` function @Cassendra4
