### ISSUE TITLE
Problem date format on datepicker (mode "datetime") on Android

### ISSUE THREAD

**Issue by smoczynskicitiz** [gcanti/tcomb-form-native#479]
Hello !

### Version

- tcomb-form-native v0.6.11
- react-native v0.55.3

### Expected behaviour

On Android, when I want to format a date (mode "datetime"), the date format configured appears.

### Actual behaviour

On Android, the date format given is not take into account. The default date format appaers.

No problem on iOS.

### Steps to reproduce

1. Create a form and add a t.Date
2. Configure the format date

`
...
 departureDate: {

          mode: "datetime",
          config: {
            format: date =>
              strings("book_time_slot.departure_date_label") +
              " " +
              moment(date).format("DD/MM/YYYY HH:mm")
          },
...
        },
...
`

3. Run on Android

Screenshot iOS (working) : 

<img width="362" alt="capture d ecran 2018-04-27 a 09 10 53" src="https://user-images.githubusercontent.com/38459808/39350456-875e786a-49fe-11e8-939d-fd9c481d4c74.png">

Screenshot Android (not working) : 

<img width="264" alt="capture d ecran 2018-04-27 a 09 28 44" src="https://user-images.githubusercontent.com/38459808/39350482-9bb245d0-49fe-11e8-833f-6e35266ba11b.png">

Am I missing something ?

**Comment by ltankey** [comment]
Yes, it's weird, but you need to specify:
```
          config: {
            format: date => moment(date).format('dddd, MMMM Do YYYY, h:mm a'),
            dateFormat: date => moment(date).format('dddd, MMMM Do YYYY'),
            timeFormat: date => moment(date).format('h:mm a'),
          },
```

Where format is used by iOS and `dateFormat` and `timeFormat` is used by Android

**Comment by alvaromb** [comment]
Thanks @ltankey!

Also, relevant: https://github.com/gcanti/tcomb-form-native/pull/484

**Comment by bhavana-jain** [comment]
is there any way we can show date and time together. also can we invoke timepicker once date is selected?
