### ISSUE TITLE
Show saved or current  date and time in Form.

### ISSUE THREAD

**Issue by rabindrachhachan** [gcanti/tcomb-form-native#480]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.11
- react-native v0.51.0

### Expected behaviour
let say I have a  Recorded_Date and  Recorded_Time field in Form value, If the Form is saved before, It should show the Date Picker and the Time Picker field , filled with value  which 
was saved before . If the Form  is new, it should show the Date Picker and Time Picker  field ,filled with current date and time.

Tell us what should happen
If I open a saved Form,  It is throwing TypeError: locals.value.toDateString is not a function.

### Actual behaviour
let say I have a  Recorded_Date and  Recorded_Time field in Form value, If the Form is saved before, It should show the Date Picker and the Time Picker field , filled with value  which 
was saved before . If the Form  is new, it should show the Date Picker and Time Picker  field ,filled with current date and time.

Tell us what happens instead
If I open a saved Form,  It is throwing TypeError: locals.value.toDateString is not a function.
### Steps to reproduce

1.
const Record = t.struct({
    Recorded_Date : t.Date,
    Recorded_Time: t.Date,
})

const options = {
 fields: {
          Recorded_Date: {
                   label: 'Date',
                   mode: 'date',
                   config: {
                          format: (date) => moment(date).format('DD-MMM-YYYY'),
                    },
        },
        Recorded_Time: {
            label: 'Time',
            mode: 'time',
            config: {
                   format: (date) => moment(date).format('HH:MM A'),
            },
        },
}
}
2.
class Report extends Component {
    constructor(props){
        super(props);
        const value = {}
        this.state ={
            value: {
                    Recorded_Date: '02-May-2018',// these data can be set from an api  response.
                    Recorded_Time: '05:26 pm'
             }
        } 
    }

  render(){
          return (
           < Form
                         ref="form"
                         type={Record}
                         options={options}
                         value={this.state.value}
               />  
          )
     }
}
3.

If you test the above code, It is throwing TypeError: locals.value.toDateString is not a function. And date and time picker work for current time and date, if I don't pass the value for Form.
I want to show filled Form (saved date and time)if it was saved on server before, or generate new Form( current date and time). Currently I am not able to open the saved Form, due to TypeError: locals.value.toDateString.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by ltankey** [comment]
Have you tried returning a `new Date(value)` from the transformer format function? Something like:
```
transformer: {
  format: (value) => {
    if (t.Nil.is(value)) return new Date();
    if ((typeof value) === 'string') return new Date(value);
    return value
  },
  parse: str => str,
}
```

**Comment by rabindrachhachan** [comment]
@ltankey , Thanks. It worked. I missed the transformer function from the document.

**Comment by alvaromb** [comment]
Relevant: https://github.com/gcanti/tcomb-form-native/pull/484

**Comment by Dgs-asohail4** [comment]
@alvaromb i have time in format hh:mm:ss, using the transformer above giving me "invalid date", i have change the code to 

`transformer: {
        format: (value) => {
          if (t.Nil.is(value)) return new Date();
          if ((typeof value) === 'string'){ return moment(value).format('hh:mm:ss')};
          return value
        },
        parse: str => str,
      },`

Now its giving me the same error, any direction how can i display the default time?
