### ISSUE TITLE
Can't output a textarea

### ISSUE THREAD

**Issue by arnoldbird** [gcanti/tcomb-form-native#481]
Sorry to crosspost, but I am stumped.  I also added this issue in tcomb-form:  https://github.com/gcanti/tcomb-form/issues/414

### Version

Tell us which versions you are using:

"tcomb": "^3.2.25",
"tcomb-form-native": "^0.6.11"
"react": "^16.3.0",

### Expected behaviour

Textarea in form output.

### Actual behaviour

Textbox in form output.

### Steps to reproduce

When I specify a textarea, I still get a textbox.  What might I be doing wrong? 

```
var props = {
      notes: t.maybe(t.String)
}
```

```
fields: {
        notes: {
          type: 'textarea',
          autoCapitalize: 'none',
          autoCorrect: false
        }
}
```

Thanks.

**Comment by ltankey** [comment]
You need to specify some options to make it multiline and change its appearance:

```
        comment: {
          multiline: true,
          stylesheet: {
            ...Form.stylesheet,
            textbox: {
              ...Form.stylesheet.textbox,
              normal: {
                ...Form.stylesheet.textbox.normal,
                height: 200,
                textAlignVertical: 'top',
              },
              error: {
                ...Form.stylesheet.textbox.error,
                height: 200,
              },
            },
          },
        },
```

**Comment by arnoldbird** [comment]
Thank you!
