### ISSUE TITLE
Looses input values when the keyboard is closed (Android)

### ISSUE THREAD

**Issue by joshuachinemezu** [gcanti/tcomb-form-native#485]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.?.?
- react-native v0.?.?

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by alvaromb** [comment]
Please, respect the issue template.
