### ISSUE TITLE
Looses input values when the keyboard is closed (Android)

### ISSUE THREAD

**Issue by joshuachinemezu** [gcanti/tcomb-form-native#486]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.11
- react-native v0.54.2

### Expected behaviour

I expected that the values in the input form will be retained

### Actual behaviour

It looses the input values when the keyboard is closed

### Steps to reproduce

1. Test on android and close the keyboard before submitting the form
### Stack trace and console log
No error is seen

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
```

**Comment by alvaromb** [comment]
Please post some source code.

**Comment by joshuachinemezu** [comment]
import React, { Component } from "react";
import { View, StyleSheet, Button } from "react-native";

import t from "tcomb-form-native"; // 0.6.9

const Form = t.form.Form;

const User = t.struct({
  email: t.String,
  username: t.maybe(t.String),
  password: t.String,
  terms: t.Boolean
});

const options = {
  auto: "placeholders",
  fields: {
    email: {
      error:
        "Without an email address how are you going to reset your password when you forget it?"
    },
    password: {
      error:
        "Choose something you use on a dozen other sites or something you won't remember"
    },
    terms: {
      label: "Agree to Terms"
    }
  }
};

export default class App extends Component {
  getInitialState() {
    return { value: null };
  }

  onChange(value) {
    this.setState({ value });
  }

  handleSubmit = () => {
    var value = this._form.getValue();
    alert(value);
    console.log("value: ", value);
  };

  render() {
    return (
      <View style={styles.container}>
        <Form
          type={User}
          options={options}
          ref={c => (this._form = c)}
          value={this.state.value}
          onChange={this.onChange.bind(this)}
        />
        <Button title="Sign Up!" onPress={this.handleSubmit} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    marginTop: 50,
    padding: 20,
    backgroundColor: "#ffffff"
  }
});

**Comment by gujral1997** [comment]
I am facing the same issue. Need urgent help

**Comment by gujral1997** [comment]
@joshuachinemezu  Do you started facing this issue after updating  react-native?

**Comment by gujral1997** [comment]
@alvaromb need urgent help

**Comment by joshuachinemezu** [comment]
@gujral1997 .. I think using React.createClass instead of `class ... extends Component fixed the problem for me, though later used snowflake for the project. It's a nice boilerplate and they are also making use of https://github.com/gcanti/tcomb-form-native. The repo url for snowflake is https://github.com/bartonhammond/snowflake... The default for the backend of the boilerplate is Hapi and the Parse server but I configured mine and I am using CodeIgniter(PHP Framework) for the backend, you can give it a trial. Nice boilerplate I must say
Heads up redux is used for state management in snowflake

**Comment by wouterNL** [comment]
Same issue. Any fixes?

**Comment by joshuachinemezu** [comment]
@wouterNL I had to use redux to maintain the user inputs. I think @gcanti should add a state management to be maintaining the inputs in the default tcomb package

**Comment by alvaromb** [comment]
@gujral1997 asking for "urgent help" will not bring you urgent help in an issue. Please try to use StackOverflow for this kind of questions.

**Comment by alvaromb** [comment]
This is weird, because you can use `Form` as a controlled component by responding to the form changes saving them into the `state`.

I think your error comes from another part of your source code, not related to this library.

**Comment by joshuachinemezu** [comment]
@alvaromb Please do you have any working code. Hope you won't mind sharing so I can use it as a guide for debugging my source code

**Comment by joshuachinemezu** [comment]
I think same issue has also been opened #492 again... Please do help with your approach to solving this issue

**Comment by wouterNL** [comment]
@alvaromb It works fine on iOS, but on android it just automatically clears the fields as soon as you tap on another field or close the keyboard

**Comment by MSchmidt** [comment]
It's weird that it works on iOS, since this is a regular state issue. It shouldn't work unless you keep track of the form state. It may work if no other component is triggering a re-render. But when you start to have more nested components you will eventually run into this issue.

So if you are not using global state management like redux, then keep track within the parent component:
```
<Form
  ref="form"
  type={Person}
  options={this.formOptions}
  value={this.state.formValue}
  onChange={(formValue) => this.setState({formValue})}
/>
```
`value` and `onChange` are the important options here.

**Comment by poeticDev** [comment]
Thanks  @mschmidt. I will check it out and give you feedback on it
