### ISSUE TITLE
Cannot read property 'is' of undefined (React Native v0.10.0)

### ISSUE THREAD

**Issue by MikaelCarpenter** [gcanti/tcomb-form-native#49]
Just updated React Native to 0.10.0 and tcomb-form-native to 2.4.0. Now when I try to load a screen containing a tcomb form I get `Cannot read property 'is' of undefined`

The top of the stack trace is:
```
Form.render
http://localhost:8081/index.ios.bundle:54433
```

**Comment by gcanti** [comment]
Hi,
I'm afraid I can't fix this: react-native 0.10 seems to require XCode 6.3+ which, in turn, requires Yosemite (I can't upgrade).
But I'll gladly accept a PR from anyone is willing to take over this repo.

**Comment by alvaromb** [comment]
@MikaelCarpenter I'm trying to reproduce the issue, but the simple example I put is working fine with React Native 0.10.0. I want to solve this issue so feel free to add something that breaks in [this repo](https://github.com/alvaromb/react-native-tcomb-form-example) and I'll check out as soon as I can :sunglasses:.

**Comment by buhe** [comment]
+1

**Comment by jonaswindey** [comment]
Do you still have this with react-native 0.11? 

Could you post your code?

**Comment by alvaromb** [comment]
This is our fork for 0.10.0 https://github.com/APSL/tcomb-form-native, but as I said before, we couldn't find the issue with 0.10.0 yet, so it only has the ``package.json`` version pointing to 0.10.0.

I would really appreciate to keep ``tcomb-form-native`` up to date, so please report any issues you have with the latest versions of React Native and the library and I'll do my best to fix it.

**Comment by gcanti** [comment]
> I would really appreciate to keep tcomb-form-native up to date

@alvaromb thanks for doing that. Feel free to send PRs.

Btw, I could publish a new version with `"react-native": ">=0.9.0"` in package.json, what do you think?

**Comment by jonaswindey** [comment]
Yes, my fork with an updated package.json also works correctly, so I think you can update it, @gcanti

**Comment by alvaromb** [comment]
@gcanti it's ok with me. I couldn't find any problems whatsoever with ``tcomb-form-native`` and 0.10.0, but other users have reported issues so I didn't sent a PR with the version changes.

**Comment by gcanti** [comment]
Done https://github.com/gcanti/tcomb-form-native/releases/tag/v0.2.7
