### ISSUE TITLE
Style for focused textinput's

### ISSUE THREAD

**Issue by baseio** [gcanti/tcomb-form-native#50]
Hi,

Thanks for this awesome lib!!

The addition of a new style "type" for focused textinputs would be amazing, sth along the lines of a slightly thicker border maybe, to supplement the "normal" and "error" types.

Doable?

**Comment by alvaromb** [comment]
Hello @baseio!

This can be done easily with custom templates or factories. Please take this code as an example https://github.com/APSL/react-native-floating-label and ping me if you need further info.

**Comment by koenpunt** [comment]
"easily" isn't really a truth here, because there's a lot of code involved if one only wants to effect say a border color on focus..
