### ISSUE TITLE
Numbers model not compatible with French rational numbers

### ISSUE THREAD

**Issue by GodefroyClair** [gcanti/tcomb-form-native#517]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.11
- react-native v0.54.2

Only tested so far on ios

### Expected behaviour

Accept comas as a decimal delimiter for Numbers for French keyboard.

### Actual behaviour

Can't validate a form if I put a comma instead of a dot (the comma is the only choice on Iphone virtual keypad)

### Steps to reproduce

1. Create a form with t.Numbers in the model
2. Use it on an Iphone set to French keyboard
3. You can't validate

Thank you for your help

PS : Thanks for the great job otherwise!!

**Comment by GodefroyClair** [comment]
sorry found previous same question

**Comment by CharlyPoppins** [comment]
link ?
