### ISSUE TITLE
The properties over 'passProps' are not reactive.

### ISSUE THREAD

**Issue by sandcforge** [gcanti/tcomb-form-native#53]
let firstRoute = {
        name: 'XXX',
        component:   ItemListPage,
        rightCorner: AddItemIcon,
        rightCornerProps: {_onPressNewItemIcon: this._onPressNewItemIcon},
        passProps: {_itemData: this.state._itemData,
                    newItemModalVisible: this.state.newItemModalVisible,
                    }
      };

      return (
        <Router
          firstRoute={firstRoute}
          headerStyle={styles.header}
          />

      );

I can render the value of 'newItemModalVisible' in the 1st route. but the value is not updated when 'newItemModalVisible' is updated.

Does anyone have the same issue?

Thanks,
Chen

**Comment by alvaromb** [comment]
Does this have anything to do with ``tcomb-form-native``? Looks more like a ``Navigator`` issue.

**Comment by sandcforge** [comment]
1) I did not use that tcomb-form-native. 
2) This is how I update 'this.state._itemData'.

    let tmpData = this.state._itemData;
    tmpData.push(  {
      id: guid() ,
      name: 'Coach',
      type: 'Bag',
      mount: 3,
      price: 400,
      description: 'coach description',
      thumb: 'http://facebook.github.io/react/img/logo_og.png',
      url: 'xxx'
    } );
    this.setState({_itemData: tmpData});

I cannot do it like this

this.setState({_itemData: this.state._itemData.push({...})});

**Comment by gcanti** [comment]
> I did not use that tcomb-form-native

Seems you are posting in the wrong repo
