### ISSUE TITLE
How to show only the placeholders?

### ISSUE THREAD

**Issue by nobady90** [gcanti/tcomb-form-native#535]
### Version
- tcomb-form-native v0.6.18
- react-native v0.57.1

### Expected behaviour

Show only the placeholders of the fields.

### Actual behaviour

the 'undefined' appear.

### Steps to reproduce
I simply tried all the ways described in the readme:

`var options = {
  auto: 'placeholders'
};`

labels continue to appear, even if I say `label: null` or `label: ''` in every single field.

I also tried with `auto: 'none'` but if not specific the label always comes out `undefined`
Where am I doing wrong?
Thanks guys!

**Comment by alvaromb** [comment]
Will tackle this today, we had problems with placeholders since the last two versions.

**Comment by alvaromb** [comment]
Sorry for the inconveniences, please try the new release: https://github.com/gcanti/tcomb-form-native/releases/tag/v0.6.19

**Comment by nobady90** [comment]
Hi @alvaromb , yeppa, I tried and it works correctly ! :+1: 
A useful thing could also be to implement the option 'errorPlaceholderTextColor' to change color in case of error in validation do not you think?
Reading this issue #215 , it was solved by using another library ... but it would be nice to have everything using only tcomb-form-native no?
thanks for the support!
