### ISSUE TITLE
onChange handler receives unparsed value

### ISSUE THREAD

**Issue by karlguillotte** [gcanti/tcomb-form-native#542]
Not sure if it is the intended behavior, but it looks like that the value received by the `onChange` handler is never parsed (e.g. `this.getTransformer().parse(value)`). This behavior is fine for `<Textbox>` that handles `t.String`, I am expecting to get a string. However, I am not sure it is fine when the `<Texbox>` handles `t.Number`, I would expect to get a number. Curious to know your thoughts on that. 

Thanks!

https://github.com/gcanti/tcomb-form-native/blob/cb70ddf0a2a900094fdf3809ae6dd0afa84b719f/lib/components.js#L93

**Comment by bradjones1** [comment]
For anyone hitting this issue while trying to do something like validating on change, the [README](https://github.com/gcanti/tcomb-form-native#adding-a-default-value-and-listen-to-changes) covers this, though it may not be obvious on a more cursory reading:

Specifically, the value passed on the `onChange` callback:

> contains the current raw value of the form (can be an invalid value for your model)

So in your callback you would need to both store the value in the state (so as to persist) but do validation against the form ref directly:

```javascript
  onFormChange(value) {
    const formValid = this.form.validate();
    this.setState({
      formIsValid: formValid.isValid(),
      formValue: value,
    });
  }
```
