### ISSUE TITLE
t.Maybe(type) adds (Optional) text to label

### ISSUE THREAD

**Issue by martinshhh** [gcanti/tcomb-form-native#544]
### Version

Tell us which versions you are using:

- tcomb-form-native v0.6.20
- react-native v0.56.0

### Expected behaviour
Not sure if I'm missing something but changing the label manually on the options doesn't remove the "(optional)" text.

Is there a way to remove this or is not supported?

Thanks.

**Comment by martinshhh** [comment]
Solution: pass i18n on the options object and set "optional" param to whatever you want
```
const options = {
  i18n: {
    optional: ''
  },
}
```

**Comment by ishigamii** [comment]
@gcanti It seems the readme should be updated with this solution cause this works and the solution in the readme doesn't. 
The current readme solution is not working for me : 
```
t.form.Form.i18n = {
  optional: '',
  required: ' (required)' // inverting the behaviour: adding a postfix to the required fields
};
```
Furthermore you also need  : 
```
    required: '',
```
otherwise you will get undefined text in your label which is not wanted. Should be default to ''.

**Comment by gcanti** [comment]
@Ishigamii Thanks for the report but I don't maintain this library anymore (maybe someone else could verify). Cheers.

**Comment by ishigamii** [comment]
my bad sorry @alvaromb maybe ?

**Comment by WeeCoopTech** [comment]
Hi, 
the solution you propose doesn't work for me. I still have ' (optional) ' after the label of my field. 
There is no way to remove it ?
