### ISSUE TITLE
Map value to enum

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#56]
I'm curious about one thing that I don't know if it's a bug or feature. Let's assume that I have an enum inside a form and I want to map some API response to the enum values:

```js
const Types = t.enums({
  1: 'Type 1',
  2: 'Type 2',
})
const Form = t.struct({
  type: Types
})
```

The API response is like this:

```json
{"type": 1}
```

Passing this as the form's value results in a non-selected picker component. However, if I parse the ``type`` value to an string using ``String()``, the picker does have the right type selected.

Is this a bug or a feature? If it's something that can be solved in ``tcomb`` or ``tcomb-form-native``, please let me know and I'll gladly provide a PR as soon as I can.

**Comment by gcanti** [comment]
Hi @alvaromb,
enums are strings. When you type something like this:

```js
{
  1: 'Type 1',
  2: 'Type 2',
}
```

JavaScript will coerce the keys to strings. As a waorkaround you could format / parse the type value to / from a string explicity or you could define a custom transformer (https://github.com/gcanti/tcomb-form-native#transformers) for that field

**Comment by alvaromb** [comment]
Yes, I know that JS will convert keys to string, but I expected the matching between the value object and the Form to do the same. Currently I'm parsing values, but I wanted to know if this could be managed in some other way.

**Comment by gcanti** [comment]
>  but I expected the matching between the value object and the Form to do the same

I guess you could change the format function in the default transfomer:

https://github.com/gcanti/tcomb-form-native/blob/master/lib/components.js#L307

```js
format: value => Nil.is(value) && nullOption ? nullOption.value : String(value), // <= ensure a string
```

**Comment by alvaromb** [comment]
Thanks @gcanti! I'll try that. Are you interested in a PR or it's better to keep it as a local fix?

**Comment by gcanti** [comment]
> Are you interested in a PR

:+1:

**Comment by machard** [comment]
What do you think about setting `option.text` from the map key and `option.value`from the associated map value ?
that way it allows to have any type of `value`. and only text `text`

I currently use this durty monkey patching to reverse text/value in enums

```
var getOptions = t.form.Select.prototype.getOptions;
t.form.Select.prototype.getOptions = function() {
  return getOptions.call(this).map(option => ({text: option.value, value: option.text}));
};


// for example now my enums are like
t.enums({
  Male: 0,
  Female: 1
})
```
