### ISSUE TITLE
Can Anyone Help me To Set Values to state after submitting form

### ISSUE THREAD

**Issue by SheikSena** [gcanti/tcomb-form-native#564]
import React from 'react';
import { Image, Platform, ScrollView, StyleSheet, View, Button } from 'react-native';
import t from 'tcomb-form-native';

const Form = t.form.Form;

const User = t.struct({
  username: t.String,
  password: t.String,
  organization: t.String,
});

const options = {
  fields: {
    username: {
      label: 'UserName',
      error:'Please Enter UserName'
    },
    password:{
      error:'Please Enter Password'
    },
    organization:{
      error:'Please Enter Organization Name'
    }
  },
};

export default class HomeScreen extends React.Component {

  state = {
    username: '',
    password: '',
    organization: '',
  };
  
  static navigationOptions = {
    header: null,
  };
  
  render() {
    return (
      <View style={styles.form}>
        <Form
          type={User}
          ref={c => this._form = c} // assign a ref 
          options={options} // pass the options via props
          value={this.state.value}
        />
        <Button
          title="LOGIN"
          color="#336699"
          onPress={this.handleSubmit}
        />
      </View>
    );
  }

  handleSubmit = () => {
    const value = this._form.getValue(); // use that ref to get the form value
    // console.log('value: ', value);
    this.setState(value);
    console.log(this.state.username);
  }

}

const styles = StyleSheet.create({
  form: {
    justifyContent: 'center',
    marginTop: 50,
    padding: 20,
    backgroundColor: '#ffffff',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  contentContainer: {
    paddingTop: 30,
  },
  welcomeContainer: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  welcomeImage: {
    width: 100,
    height: 80,
    resizeMode: 'contain',
    marginTop: 3,
    marginLeft: -10,
  },

  homeScreenFilename: {
    marginVertical: 7,
  },
  codeHighlightText: {
    color: 'rgba(96,100,109, 0.8)',
  },
  codeHighlightContainer: {
    backgroundColor: 'rgba(0,0,0,0.05)',
    borderRadius: 3,
    paddingHorizontal: 4,
  },
  tabBarInfoContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    ...Platform.select({
      ios: {
        shadowColor: 'black',
        shadowOffset: { height: -3 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
      },
      android: {
        elevation: 20,
      },
    }),
    alignItems: 'center',
    backgroundColor: '#fbfbfb',
    paddingVertical: 20,
  },
  tabBarInfoText: {
    fontSize: 17,
    color: 'rgba(96,100,109, 1)',
    textAlign: 'center',
  },
  navigationFilename: {
    marginTop: 5,
  }
});

**Comment by SheikSena** [comment]
I am New To react native

**Comment by anishh1** [comment]
Hi, what was the outcome to this?
