### ISSUE TITLE
SwitchIOS is not supported n this Platform

### ISSUE THREAD

**Issue by DrMabuse23** [gcanti/tcomb-form-native#60]
Hey what about Android any plans about this ?

**Comment by Qard** [comment]
:+1: I also need an Android-supported switch.

**Comment by alvaromb** [comment]
This could be achieved with react-native v0.13.0 & onwards https://github.com/facebook/react-native/commit/36cbe74f990369c793966b052bee4af3f2f4e401.

Will try to start integrating this, but that would also mean dropping support for older react-native versions. Any problem about doing that @gcanti? Should we still support v0.12.0 and older?

**Comment by gcanti** [comment]
> Any problem about doing that @gcanti?

Not at all

**Comment by leeight** [comment]
+1

**Comment by DrMabuse23** [comment]
+1

**Comment by kanerogers** [comment]
Any update on this? I'm happy to pitch in.

**Comment by Iragne** [comment]
+1

**Comment by cnjon** [comment]
+1

**Comment by minibikini** [comment]
+1

**Comment by alvaromb** [comment]
Will try to tackle this issue during the week.

**Comment by dgilperez** [comment]
Hurra!

**Comment by alvaromb** [comment]
This is my top priority but I'm on parental leave and unfortunately I don't have a lot of time to check into it. I've started to work in this and I should have a working version soon :)

**Comment by dgilperez** [comment]
:baby:'s come first. React forms can wait.

**Comment by dangnelson** [comment]
+1

**Comment by alvaromb** [comment]
Back to work, sorry for the delay. Working on this right now.

**Comment by alvaromb** [comment]
![3772717](https://cloud.githubusercontent.com/assets/289640/12262752/0783af0a-b92a-11e5-9759-44496463c7a3.jpg)

Ok, sorry for the delay. I've been very busy with the :baby:, work and other unrelated things.

The PR was very easy, but needs to drop ``react-native`` support below 0.13.0.

@gcanti take a look at this one and @all please let us know if the ``react-native`` version represents a problem for you.

**Comment by gcanti** [comment]
@alvaromb For me it's ok. Alas from now on I can't review other PRs (I'm stuck with RN v0.9.0), sorry.

**Comment by alvaromb** [comment]
Ok, do you want me to bump the RN version under ``package.json``?

**Comment by gcanti** [comment]
Sure. This library should evolve ignoring my (hopefully momentary) incapabilities ;-)
