### ISSUE TITLE
Avoid Keyboard?

### ISSUE THREAD

**Issue by justinmakaila** [gcanti/tcomb-form-native#62]
Does this automatically handle moving forms up and down to avoid the keyboard?

**Comment by alvaromb** [comment]
No, but we've been discussing this issue here https://github.com/facebook/react-native/issues/3195

**Comment by anshul** [comment]
@alvaromb Are there any good solutions for the general case?

**Comment by alvaromb** [comment]
Well, not yet but I managed to solve the scrolling using my scroll component: https://github.com/apsl/react-native-keyboard-aware-scroll-view.

My solution is explained here: https://github.com/facebook/react-native/issues/3195#issuecomment-146518331

Let me know if you need something else!
