### ISSUE TITLE
Pass in config options to custom template through options

### ISSUE THREAD

**Issue by dajomu** [gcanti/tcomb-form-native#63]
Hi,

I've created a form with tcomb-form and I'm converting it over to tcomb-form-native.
In my old version of the form I was passing configuration options through a config option -

```javascript
const ComposeForm = (model, attachment, onBodyFocus, onBodyBlur) => ({
  fields: {
    community: {
      nullOption: {value: '', text: 'Choose a community'},
      template: linkInput,
      config: {
        to: 'composeCommunities',
        replace: true,
        onBodyBlur,
      },
    },
......
```

When I look for locals.config in my custom template I can't find it.

I notice this is still available for react tcomb, but there isn't any mention of this in native tcomb form docs, specifically -
[https://github.com/gcanti/tcomb-form-native#templates](https://github.com/gcanti/tcomb-form-native#templates)
```javascript
{
  stylesheet: Object, // the styles to be applied
  hasError: boolean,  // true if there is a validation error
  error: ?string,     // the optional error message to be displayed
  label: string,      // the label to be displayed
  help: ?string,      // the optional help message to be displayed
  value: boolean,     // the current value of the checkbox
  onChange: Function, // the event handler to be called when the value changes

  ...other input options here...

}
```

Has this functionality not been implemented in native tcomb forms yet?

**Comment by gcanti** [comment]
> Has this functionality not been implemented in native tcomb forms yet?

Yep. Do you want to send a PR?

**Comment by dajomu** [comment]
Will do skipper (will hopefully create one this afternoon when I get the time)!

**Comment by dajomu** [comment]
Hi, PR submitted:
https://github.com/gcanti/tcomb-form-native/pull/64
