### ISSUE TITLE
Support for Android DatePicker

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#67]
Currently we support ``DatePickerIOS``. We should have a similar component for Android.

**Comment by leeight** [comment]
+1

**Comment by brunoksato** [comment]
+1

**Comment by cnjon** [comment]
+1

**Comment by taf2** [comment]
+1

**Comment by alvaromb** [comment]
I have a fully functional date factory for ``tcomb-form-native``, but it uses https://github.com/nucleartux/react-native-date because the native date picker component isn't open source in RN yet (or it hasn't been supported, I don't know if it's in their roadmap).

We want to release 0.4.0 with full Android support so a date picker component is needed, but in this case we should depend on third-party libs. How do you feel about that @gcanti?

**Comment by gcanti** [comment]
In general my advice would be to keep factories, templates and stylesheets in their own repos and then configure `tcomb-form-native`:

```js
// import just the core
var t = require('./lib');
// i18n
var i18n = require('./lib/i18n/en');
// custom templates
var templates = require('mytemplates');
// custom stylesheets
var stylesheet = require('mystylesheets');

// configure...
t.form.Form.templates = templates;
t.form.Form.stylesheet = stylesheet;
t.form.Form.i18n = i18n;
```

**Comment by alvaromb** [comment]
In this scenario, @gcanti, where we cannot have pair functionality between iOS and Android platforms, should we keep this factories outside ``tcomb-form-native``?

It's perfect for me to have those factories outside, but we should add that info into ``README`` for the next release in order to provide full Android support.

**Comment by sdg9** [comment]
@alvaromb do you mind posting your date factory solution? I'm working on the same thing also use react-native-date and am brand new to tcomb-form-native, having trouble wiring callback result from react-native-date to value in tcomb template.  I know it has to be something really simple just bugging me since I don't have any examples to work off of.

**Comment by alvaromb** [comment]
Sure @sdg9!

I'll set up a repo for that factory today ;)

**Comment by alvaromb** [comment]
I have a very busy day, so I don't know if I'll be able to put a repo for that today. Here you have the snippet of the Android DatePicker, using https://github.com/nucleartux/react-native-date

```es6
import React, {
  View,
  Text,
  TouchableNativeFeedback,
  NativeModules
} from 'react-native'
import t from 'tcomb-form-native'
import moment from 'moment'

const TcombDatePicker = t.form.DatePicker

export default class DatePicker extends TcombDatePicker {
  _handleClick (locals) {
    NativeModules.DateAndroid.showDatepicker(() => {}, (y, m, d) => {
      locals.onChange(new Date(y, m, d))
    })
  }

  getTemplate () {
    var self = this
    return function (locals) {
      let formattedDate
      if (locals.mode === 'date') {
        formattedDate = moment(locals.value).format('DD/MM/YYYY')
      } else if (locals.mode === 'time') {
        formattedDate = moment(locals.value).format('h:mm:ss')
      } else {
        formattedDate = moment(locals.value).format('DD/MM/YYYY, h:mm:ss')
      }
      let controlLabelStyle = locals.stylesheet.controlLabel.normal
      let textboxBackground = locals.stylesheet.textbox.normal.backgroundColor
      if (locals.hasError) {
        controlLabelStyle = locals.stylesheet.controlLabel.error
      }
      return (
        <View style={[styles.container, {backgroundColor: textboxBackground}]}>
          <TouchableNativeFeedback onPress={self._handleClick.bind(self, locals)}
            background={TouchableNativeFeedback.Ripple()}>
            <View style={[styles.header, styles.textContainer]}>
              <Text style={[styles.label, controlLabelStyle]}>
                {locals.label}
              </Text>
              <Text style={styles.value}>
                {formattedDate}
              </Text>
            </View>
          </TouchableNativeFeedback>
        </View>
      )
    }
  }
}

const styles = React.StyleSheet.create({
  container: {
    flex: 1,
    marginBottom: 10,
  },
  textContainer: {
    flexDirection: 'row',
    paddingLeft: 5,
    paddingRight: 5,
  },
  label: {
    flex: 1,
    fontSize: 16,
    alignSelf: 'center',
    marginTop: 7,
  },
  value: {
    width: 95,
    fontSize: 16,
    textAlign: 'right',
    alignSelf: 'center',
    color: '#666',
  },
  header: {
    flex: 1,
    height: 44,
  },
})
```

**Comment by sdg9** [comment]
Awesome thanks for the example got mine working now!

**Comment by gcanti** [comment]
@alvaromb just a tip: you are re-defining the template for each re-rendering, what about something like this (not tested but you get the idea):

```js

// define the template only once
function myTemplate(locals) {
  let formattedDate

  ...

  <TouchableNativeFeedback onPress={locals.handleClick}

  ...
}

export default class DatePicker extends TcombDatePicker {

  // overriding getLocals adding a custom handler
  getLocals() {
    const locals = super.getLocals()
    locals.handleClick = () => {
      NativeModules.DateAndroid.showDatepicker(() => {}, (y, m, d) => {
        locals.onChange(new Date(y, m, d))
      })
    }
    return locals
  }

  // return the template
  getTemplate() {
    return myTemplate
  }

}

```

**Comment by gcanti** [comment]
Actually I think you might even avoid a custom factory, just define a template. Am I missing something?

```js
function myTemplate(locals) {

  const handleClick = () => {
    NativeModules.DateAndroid.showDatepicker(() => {}, (y, m, d) => {
      locals.onChange(new Date(y, m, d))
    })
  }

  let formattedDate

  ...

  <TouchableNativeFeedback onPress={handleClick}

  ...
}

```

**Comment by alvaromb** [comment]
No, you're absolutely right @gcanti, that can be done with a template. I was using factories by default every time I needed to customise something. Will change that! :)

**Comment by gcanti** [comment]
In general the way I see `tcomb-form-native` when we come to customization is:

there are 3 levels of customization

- Stylesheets
- Templates
- Factories

**Stylesheets**

I'm ok with the default layout and the default widgets but I want different colors / borders / padding etc..

**Templates**

I wanna hack the layout **or** integrate 3rd party widgets

**Factories**

I want to handle new types (for example a `RegExp`) **or** handle new options **or** I wrote a custom template and a custom transformer and I want to pack them together in a factory

Granted, those are not strict rules, just my mental map.

**Comment by alvaromb** [comment]
Android ``DatePicker`` will land into React Native 0.20 https://github.com/facebook/react-native/commit/9a0539d2c48c528d44ddb53d6ea8343890b0ddaa

This means that we're going to release ``tcomb-form-native`` 0.4 when RN 0.20 gets published. /cc @gcanti

**Comment by radiegtya** [comment]
0.20 published guys. Any update about this? :D

**Comment by alvaromb** [comment]
Yes!

I'll work on this today in the afternoon.

Thanks for your patience, family time 😅

Enviado desde mi iPhone

**Comment by radiegtya** [comment]
Have a good time :)

**Comment by alvaromb** [comment]
@gcanti Android's ``TimePickerAndroid`` and ``DatePickerAndroid`` are very different from ``DatePickerIOS``. As you can see here https://github.com/facebook/react-native/blob/9a0539d2c48c528d44ddb53d6ea8343890b0ddaa/Examples/UIExplorer/DatePickerAndroidExample.js#L49, you don't use them as a component, but call them in an imperative way.

I would like to fit this component into ``tcomb-form-native`` with some consensus. My choice would be add a ``TouchableNativeFeedback`` that opens the pickers. What do you think?

**Comment by kanerogers** [comment]
Sounds good to me, @alvaromb

**Comment by alvaromb** [comment]
True, @kanerogers, but both components are different. ``DatePickerIOS`` is displayed directly in the form as a picker. That's not the case of ``TimePickerAndroid`` or ``DatePickerAndroid``; both open a dialog to select the input, so they will be displayed in a different way.

**Comment by kanerogers** [comment]
Very good point @alvaromb. 

I think that a `TouchableHighlight` is a good place to start - perhaps you could push that to a branch and we can take a look to see how it feels?

**Comment by alvaromb** [comment]
Ok, I'll push my interpretation of how the component should be and you will be able to test it installing directly from Github with ``npm i gcanti/tcomb-form-native#0.4`` or similar.

**Comment by kanerogers** [comment]
Sounds good to me! :+1:

**Comment by gcanti** [comment]
> My choice would be add a `TouchableNativeFeedback` that opens the pickers

If I undestand something like this (pseudocode)?

```
<TouchableNativeFeedback>  // <= clicking this will open the picker
  <label>Birth date</label>
  <text>1973-11-30</text> // <= problem: how to format this date?
</TouchableNativeFeedback>
```

**Comment by alvaromb** [comment]
Yes, I was thinking about something like that. 

We can use the device locale to format the date, but it is a bit PITA to do it without a library. Maybe we should provide a way (i.e. a function) to let the user format the ``Date`` instance.

Regarding the code organisation, we should have ``datepicker.ios.js`` and ``datepicker.android.js`` with the separate implementations. The ``require`` under ``index.js`` will choose one or another depending on the platform.

**Comment by kanerogers** [comment]
Sounds good to me!

**Comment by gcanti** [comment]
`TimePickerAndroid` and `DatePickerAndroid` are not yet documented (or I'm missing something?) and 0.21 was pre-released yesterday. How do you guys comply with this pace?

/rant

> Maybe we should provide a way (i.e. a function) to let the user format the Date instance.

Yep. Maybe contained in an optional `config` object as in `tcomb-form` in order to avoid name collisions with future official fields:

```js
function mytemplate(locals) {
  ...
  const formattedDate = locals.config.format(locals.value)
  ...
}

const options = {
  fields: {
    birthDate: {
      template: mytemplate,
      config: { // <= tcomb-form-native will guarantee to pass this object (as it is) to the template
        format: date => date.toISOFormat(),
        ...other custom options required by mytemplate...
      }
    }
  }
}
```

> The require under index.js will choose one or another depending on the platform

I'm afraid a dynamic require would break again the webpack support. What about pushing the burden to the user?

```js
// tcomb-form-native configuration

import t from 'tcomb-form-native'
import androidDatepicker from 'tcomb-form-native/lib/templates/bootstrap/datepicker.android'

// default t.form.Form.templates.datepicker is missing
t.form.Form.templates.datepicker = androidDatepicker
```

**Comment by alvaromb** [comment]
> TimePickerAndroid and DatePickerAndroid are not yet documented (or I'm missing something?) and 0.21 was pre-released yesterday. How do you guys comply with this pace?

It's not documented, but it has been released for 0.20. Yep, a two week release cycle is insane. I'm now the only responsible for mobile development at my company and I have to deal with +5 apps in both platforms and regular RN updates ¯\_(ツ)_/¯ 

+1 for the optional config.

> I'm afraid a dynamic require would break again the webpack support. What about pushing the burden to the user?

I don't use webpack and I don't really understand why people is using it with RN apps (I would love to read an article about the pros-cons and why that's better than the official tooling though). 

Dynamic require is a super powerful feature for multiplatform apps; in our experience with three iOS & Android apps in React Native, this has become the most used way to share a codebase for the two platforms with some custom modules. In fact, is one of the official ways to build a multiplatform app. But, if we have to support webpack, I would prefer to use ``Platform.OS === 'ios'`` --if possible-- and select one or another component automatically. Ideally, defining a struct and rendering it under iOS or Android should generate their respective form without any other additional config.

**Comment by gcanti** [comment]
> Dynamic require is a super powerful feature for multiplatform apps

Certainly you are more experienced than me so I take your word. Let's ignore webpack for now.

**Comment by alvaromb** [comment]
I'm writing an article in our engineering blog about the best practices that we've found for building multiplatform apps, and this has been one of the most used.

However, before dumping webpack support, I would like to deeply understand why some people is using it with RN. My point is that top priority should be easy support for multiplatform form generation, and then it should be agnostic about the development stack. We can ignore webpack right now, but I'm completely open to discuss solutions that would work with it.

**Comment by kanerogers** [comment]
I've been using dynamic require in our Multiplatform app since we launched
Android support in September, and have found it to keep code quite clean.

Perhaps we go ahead with this path, and then if there's feedback that we
need webpack support, we can go back to checking Platform.OS?

In my humble opinion, the most important thing is just to get something out
there - right now, Android users can't take advantage of this amazing
library!

K

**Comment by alvaromb** [comment]
Ok, give me some time and I'll try to put an example between today and tomorrow.

**Comment by alvaromb** [comment]
However, keep in mind @kanerogers that you actually **can** use this library with Android right now. Just pass a custom template or factory for Android in a ``t.Date`` field.

Of course the good thing is to do this out of the box, so give me today and tomorrow to send a PR with a first implementation.

**Comment by gcanti** [comment]
> Android users can't take advantage of this amazing library

Thanks @kanerogers. Just a clarification though: since `react-native` supports android, `tcomb-form-native` has always been usable by android developers, it's just a matter of writing your own templates (here all the credit goes to @alvaromb who is willing to write the **default ones**).

**Comment by kanerogers** [comment]
You guys are definitely right! But it's those default templates that make
the library that extra bit more incredible. 🤓

**Comment by alvaromb** [comment]
Brace yourselves, first version of ``TimePickerAndroid`` and ``DatePickerAndroid`` is here https://github.com/gcanti/tcomb-form-native/pull/121

Sorry, tried to rebase previous stuff but I ended messing things up. 

Basically, as @gcanti proposed, there is an optional ``config`` object for the field options that can handle two key-values:

| Key | Value |
-------|----------
| ``mode`` | Can take ``time`` or ``date``. Chooses which picker should the library render. Optional, defaults to ``date``. |
| ``format`` | A ``(date) => String(date)`` kind of function to provide a custom date format parsing to display the value. Optional, defaults to ``(date) => String(date)``.

Also, there's room for a new ``background`` local for ``TouchableNativeFeedback``.

The component doesn't have any style applied, looks like the screenshots below:

<img width="671" alt="screen shot 2016-02-23 at 22 43 42" src="https://cloud.githubusercontent.com/assets/289640/13267709/04af0c2c-da7f-11e5-8a82-31fdca3dd23e.png">
<img width="671" alt="screen shot 2016-02-23 at 22 43 44" src="https://cloud.githubusercontent.com/assets/289640/13267711/04dc47d2-da7f-11e5-8919-9a7379aae10d.png">
<img width="671" alt="screen shot 2016-02-23 at 22 44 18" src="https://cloud.githubusercontent.com/assets/289640/13267710/04d6f0de-da7f-11e5-9f04-01f6903bc9e0.png">

Please provide some feedback to finish the ``0.4`` release.

Thanks for your patience.

**Comment by alvaromb** [comment]
Just FYI, you can install and test it running ``npm i apse/tcomb-form-native#android_04``.

**Comment by kanerogers** [comment]
Thanks for this! I'll check it out ASAP. :-)

K

**Comment by alvaromb** [comment]
Sorry I just closed previous PR due to un-squashed merge commits. This is the right one: https://github.com/gcanti/tcomb-form-native/pull/122

**Comment by kanerogers** [comment]
Thanks! Sorry I haven't had a chance to check this out - will do in the
next 24 hours.

K
