### ISSUE TITLE
struct state management

### ISSUE THREAD

**Issue by machard** [gcanti/tcomb-form-native#70]
Hi,

I think there is problem here :
https://github.com/gcanti/tcomb-form-native/blob/master/lib/components.js#L382

Shouldn't it be `this.setState({value});` ?

**Comment by gcanti** [comment]
Yep, there's a PR for that (and for your other issue)
Thanks for pointing out.

https://github.com/gcanti/tcomb-form-native/pull/69

**Comment by machard** [comment]
Cool, thx!

**Comment by gcanti** [comment]
Could you please help us to test it out with your use cases before merging?

**Comment by machard** [comment]
yes it works with my use cases, thx!

**Comment by gcanti** [comment]
Great, thanks for your help
