### ISSUE TITLE
refinement does not work

### ISSUE THREAD

**Issue by pgmemk** [gcanti/tcomb-form-native#71]
I tried to use 'refinement' function as it is described in your example but got 
```
t.refinement is not a function
```
and indeed there is no **refinement** function in your code. 

Please advise

**Comment by gcanti** [comment]
You can use `refinement` in v0.3

https://github.com/gcanti/tcomb-form-native/releases/tag/v0.3.0

**Comment by pgmemk** [comment]
Thank you
ᐧ

On Mon, Nov 9, 2015 at 2:24 PM, Giulio Canti <notifications@github.com>
wrote:

> Closed #71 <https://github.com/gcanti/tcomb-form-native/issues/71>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gcanti/tcomb-form-native/issues/71#event-458879102>.
>



-- 
Ellen Katsnelson
Lead Developer
