### ISSUE TITLE
How to add a repeat password validate?!

### ISSUE THREAD

**Issue by Yidada** [gcanti/tcomb-form-native#73]
It's seems like I can validate the repeat password input value, cause the validate option is declare outside  the Component so I can't get the first password user input and validate the repeat password is same to the last one. How to solve this problem?

**Comment by alvaromb** [comment]
Try this, @Yidada https://github.com/gcanti/tcomb-form-native#disable-a-field-based-on-another-fields-value

:smiley:

**Comment by Yidada** [comment]
Thanks a lot,It's really helpful  for me, I can handle the button to control user's behavior.but what if I want to trigger an error text to tell my user they must correct their input,It's there something I can do for this?

**Comment by alvaromb** [comment]
Sure! You can customize the error, take a look: https://github.com/gcanti/tcomb-form-native#error-messages

**Comment by valar7068** [comment]
handleSubmit = () => {
        const { password, repassword } = this.state;
        // perform all neccassary validations
        if (this.state.password != '' && this.state.repassword != '') {
            if(password !== repassword) {
                alert("Passwords don't match");
            }
        }
    }
