### ISSUE TITLE
Array Implementation

### ISSUE THREAD

**Issue by gadiel** [gcanti/tcomb-form-native#76]
Would love to see support for Array Objects or Array Strings

**Comment by msalguero** [comment]
+1

**Comment by DennisMG** [comment]
+1

**Comment by alvaromb** [comment]
Hello!

Sorry but could you explain exactly what do you mean with array objects or array strings? Letting a user select from a list of strings, for example?

**Comment by gcanti** [comment]
Maybe something like this? (a [tcomb-form](https://github.com/gcanti/tcomb-form) feature):

https://gcanti.github.io/resources/tcomb-form/playground/playground.html

Choose the "7. Lists" example in the dropdown to the left

(the playground is outdated but should give an idea)

**Comment by alvaromb** [comment]
So it's basically a list of text inputs?

**Comment by gcanti** [comment]
Closing in favour of #80
