### ISSUE TITLE
Value Updation

### ISSUE THREAD

**Issue by shubham-daffodilsw** [gcanti/tcomb-form-native#77]
I am giving a state named options to the form respective to the options property .
  < Form ref="form"
   type={this.state.type}               
options={this.state.options}
         onChange={this.onChange} />

The options updates when i Assign a new options object to my options state 
this.setState({
                    options:{
                   name:'shubham'
                     }})
but wont update when i update my previous options object.
i.e.  
                var newOptions = this.state.options ;
                   newOptions.name = 'shubham'
                     options:{
                   name:newOptions
                     }})

But the same easily works in other components in React-Native .

**Comment by gcanti** [comment]
> but wont update when i update my previous options object

Yep. It's by design, see the **Warning** here https://github.com/gcanti/tcomb-form-native#adding-a-default-value-and-listen-to-changes
