### ISSUE TITLE
this.props.keyboardType undefined

### ISSUE THREAD

**Issue by tarrencev** [gcanti/tcomb-form-native#8]
Hi, 

I'm trying to implement a view using the tcomb-forms and am running into the issue below:

message: undefined is not an object (evaluating 'keyboardTypeConsts[
      crossPlatformKeyboardTypeMap[this.props.keyboardType] ||
      this.props.keyboardType
    ]')"

I'm simply trying to recreate the form described in the readme. Any idea what might be causing this?

**Comment by tarrencev** [comment]
Fixed by updating, my bad

**Comment by alvinwoon** [comment]
Still having this issue in 1.6 (readme example)

**Comment by gcanti** [comment]
@alvinwoon react-native v0.3.4?

**Comment by alvinwoon** [comment]
ah drats. 0.3.7

![image](https://cloud.githubusercontent.com/assets/1026383/7040989/9fe4ce5e-de07-11e4-99db-0fd7e0584f05.png)
