### ISSUE TITLE
Lists & Tuples

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb-form-native#80]
Should we plan to support lists and tuples with ``tcomb-form-native``?

**Comment by gcanti** [comment]
In tcomb-form there is support for lists if somebody wants to try:

https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L610

Tuples are not supported in tcomb-form, so currently I have no idea what kind of effort would be required.

**Comment by carbureted** [comment]
What would be necessary to get lists off the ground?

**Comment by gcanti** [comment]
@carbureted AFAIK technically:

- design a default template for `List`s solving the following problems:
  - how to add records
  - how to remove records
  - how to sort records
- port the relevant `tcomb-form` code (https://github.com/gcanti/tcomb-form/blob/master/src/components.js#L621)

**Comment by alvaromb** [comment]
This is not the same as multi-select, right?

**Comment by gcanti** [comment]
@alvaromb not exactly. I mean, once you have support for lists you can use it also for implementing multi selects, but you can also manage lists of text boxes, list of structs, etc.. It's a valuable feature on the web (`tcomb-form` added support for lists from the very beginning) but you have more real estate there.

**Comment by alvaromb** [comment]
I'm interested into bringing lists into `tcomb-form-native`, mainly for having out-of-the-box support for multi-selects. Will try to do that next week if possible.

**Comment by gcanti** [comment]
@alvaromb ok! And if I find some spare time, I'll try to put up some code to help you out (list support was the most challenging implementation in `tcomb-form`)
