### ISSUE TITLE
The fields focus not working for first time

### ISSUE THREAD

**Issue by shubham-daffodilsw** [gcanti/tcomb-form-native#81]
when a field is  focused  and then focus  any other field then this will focus the new field for a moment but suddenly the field got blurred .(on that moment the keyboard got hidden which appear due to very first focus.  )

**Comment by alvaromb** [comment]
Can you post a code example?

**Comment by shubham-daffodilsw** [comment]
Actually that was because of Scroll view keyboardShouldPersistTaps .
