### ISSUE TITLE
v0.16.0 Warning: Form(...): React component classes must extend React.Component.

### ISSUE THREAD

**Issue by adriansprod** [gcanti/tcomb-form-native#83]
Since upgrading to RN v0.16.0 a yellow warning is triggered when using tcomb-form-native. Looks like t.form.Form is not recognised as extending React.Component

**Comment by gcanti** [comment]
Hi @adriansprod, thanks for reporting

**Comment by adriansprod** [comment]
thanks for fixing!

**Comment by alvaromb** [comment]
@gcanti this release is not available in npm yet, isn't it?

**Comment by gcanti** [comment]
@alvaromb not yet. Do you want to add something? Otherwise I proceed with a patch release

**Comment by alvaromb** [comment]
Not now. I'm setting a Github repo with some factories I would like to add or document how to add to ``tcomb-form-native``. I'll send you as soon as I have some of them ready.

**Comment by gcanti** [comment]
Ok, released in https://github.com/gcanti/tcomb-form-native/releases/tag/v0.3.3

**Comment by alvaromb** [comment]
:shipit: :rocket:
