### ISSUE TITLE
Error in "npm start" [tcomb-form-native 0.3.3] + [react-native 0.17.0-rc] + [node 5.2.0]

### ISSUE THREAD

**Issue by rockvic** [gcanti/tcomb-form-native#86]
Error building DependencyGraph:
 Error: Naming collision detected: /Users/IMD/App/victor/JustPlay/JP/node_modules/tcomb-form-native/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/IMD/App/victor/JustPlay/JP/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
    at HasteMap._updateHasteMap (HasteMap.js:123:13)
    at HasteMap.js:94:28
    at tryCallOne (/Users/IMD/App/victor/JustPlay/JP/node_modules/promise/lib/core.js:37:12)
    at /Users/IMD/App/victor/JustPlay/JP/node_modules/promise/lib/core.js:103:15
    at flush (/Users/IMD/App/victor/JustPlay/JP/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
~

**Comment by alvaromb** [comment]
Will have to check compatibility with rn-0.17 and up. I guess you cannot run a simple example, am I right?

**Comment by gcanti** [comment]
Ralated https://github.com/gcanti/tcomb-form-native/pull/85

**Comment by gcanti** [comment]
Closing as per d15c2b1
