### ISSUE TITLE
Unable to resolve module ./lib/templates/bootstrap

### ISSUE THREAD

**Issue by lrettig** [gcanti/tcomb-form-native#94]
I just installed tcomb-form-native version 0.3.3. I get this fatal error when trying to use a Form:

![screen shot 2016-01-08 at 17 11 25](https://cloud.githubusercontent.com/assets/3316532/12210849/10ea09d8-b62b-11e5-981d-5d0696a5ad71.png)

My code is below, if it's helpful, but it's very standard.

I worked around this by changing line 3 of `tcomb-native-form/index.js` as follows:

`var templates = require('./lib/templates/bootstrap');`
to
`var templates = require('./lib/templates/bootstrap/index');`

```javascript
var t = require('tcomb-form-native');

var Form = t.form.Form;

var CreditCard = t.struct({
  number: t.Number,
  exp_month: t.Number,
  exp_year: t.Number,
  cvc: t.Number,
  rememberMe: t.Boolean
});

var MyComponent = React.createClass({

  render: function() {
    return (
      <View style={styles.container}>
        {/* display */}
        <Form
          ref="form"
          type={CreditCard}
          options={options}
        />
      </View>
    );
  }
```

**Comment by lrettig** [comment]
The formatting also seems broken, and I'm getting two strange warnings about `Failed propType: Invariant Violation`, see below.

![image](https://cloud.githubusercontent.com/assets/3316532/12211546/d9b231c0-b62f-11e5-942d-b7394e969f3d.png)

**Comment by lrettig** [comment]
The formatting issue was fixed by adding `justifyContent: 'center'` to the container style, but the warnings persist. I wonder if these are related to the first issue I mentioned or if the issue is separate.

Thanks.

**Comment by alvaromb** [comment]
Which version of RN are you using, @lrettig ?

**Comment by lrettig** [comment]
hi @alvaromb, 0.16.0. Thanks for taking a look.

**Comment by gcanti** [comment]
This issue is fairly old and there hasn't much activity on it. Closing, but please re-open if it still occurs.
