### ISSUE TITLE
How to change form based on selection?

### ISSUE THREAD

**Issue by GrumpyPants** [gcanti/tcomb-form-native#97]
I really love this package by the way. It really simplifies form building. However, i'm having trouble implementing a dynamic form. For example say I have an iospicker. Depending on which option is selected in this picker I want the next component to either be a checkbox or a textbox. This is a simplified example but the gist is there. How can I create a dynamic form based on the selection of a component? 

Creating a separate domain model and swapping out the form type does the trick but is this the best way to go about creating a dynamic form? It seems strange that I would have to create a different domain model for every possible combination of my form.

**Comment by gcanti** [comment]
> For example say I have an iospicker. Depending on which option is selected in this picker I want the next component to either be a checkbox or a textbox

Hi,

It's possible using a statefull component:

```js
const Country = t.enums({
  'IT': 'Italy',
  'US': 'Unisted States'
}, 'Country');

var AwesomeProject = React.createClass({

  // returns the suitable type based on the form value
  getType(value) {
    if (value.country === 'IT') {
      return t.struct({
        country: Country,
        rememebrMe: t.Boolean
      });
    } else if (value.country === 'US') {
      return t.struct({
        country: Country,
        name: t.String
      });
    } else {
      return t.struct({
        country: Country
      });
    }
  },

  getInitialState() {
    const value = {};
    return { value, type: this.getType(value) };
  },

  onChange(value) {
    // recalculate the type only if strictly necessary
    const type = value.country !== this.state.value.country ?
      this.getType(value) :
      this.state.type;
    this.setState({ value, type });
  },

  onPress() {
    var value = this.refs.form.getValue();
    if (value) {
      console.log(value);
    }
  },

  render() {

    return (
      <View style={styles.container}>
        <t.form.Form
          ref="form"
          type={this.state.type}
          value={this.state.value}
          onChange={this.onChange}
        />
        <TouchableHighlight style={styles.button} onPress={this.onPress} underlayColor='#99d9f4'>
          <Text style={styles.buttonText}>Save</Text>
        </TouchableHighlight>
      </View>
    );
  }
});
```

**Note**. The output is obviously different (HTML) but since the principles are the same, for more examples you can see the issues of `tcomb-form`: https://github.com/gcanti/tcomb-form/issues?utf8=✓&q=label%3A%22dynamic+forms%22+is%3Aall+

**Comment by GrumpyPants** [comment]
Perfect, this is exactly what I need. Thanks.
