### ISSUE TITLE
React Native 0.18.0-rc

### ISSUE THREAD

**Issue by dangnelson** [gcanti/tcomb-form-native#99]
I just tried upgrading to React Native 0.18.0-rc and am getting an npm error:

├── UNMET PEER DEPENDENCY react-native@0.18.0-rc
└── tcomb-form-native@0.3.3 

Not sure how to resolve this...

**Comment by dangnelson** [comment]
Tried the follow and it didn't seem to resolve the problem:
      rm -rf ./node_modules
      npm cache clean
      npm install

**Comment by alvaromb** [comment]
@gcanti maybe we should think about dropping the ``react-native`` peer dependency/dependency in the next release. Some folks are already doing that https://github.com/oblador/react-native-vector-icons/pull/69

**Comment by alvaromb** [comment]
@dangnelson ``react-native@0.18.0-rc`` is not in the required dependencies. We're going to release a version today, so I think we're adding it explicitly or dropping RN from deps.

**Comment by gcanti** [comment]
@alvaromb ok, we could move RN from package.json (basically https://github.com/gcanti/tcomb-form-native/pull/85) to the README file so people is able to know which react native versions are supported.

**Comment by alvaromb** [comment]
Ok, I can do that. I'll ping you when I have all the pending stuff ready to release.

**Comment by gcanti** [comment]
Closing as per d15c2b1
